//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit";
//-------------------------------------------------------------------------
#include "Core/TypeSystem/Types.h"
#include "Core/TypeSystem/Info/TypeEnumInfo.h"
//-------------------------------------------------------------------------

//-------------------------------------------------------------------------
// Includes

#include "e:/engineproject/solarengine/src/engine/core/_Generated/AutoGenerated/customeditoraliasattribute.typeinfo.h"
#include "e:/engineproject/solarengine/src/engine/core/_Generated/AutoGenerated/customeditorattribute.typeinfo.h"
#include "e:/engineproject/solarengine/src/engine/core/_Generated/AutoGenerated/editordisplayattribute.typeinfo.h"
#include "e:/engineproject/solarengine/src/engine/core/_Generated/AutoGenerated/editororderattribute.typeinfo.h"
#include "e:/engineproject/solarengine/src/engine/core/_Generated/AutoGenerated/enums.typeinfo.h"
#include "e:/engineproject/solarengine/src/engine/core/_Generated/AutoGenerated/headerattribute.typeinfo.h"
#include "e:/engineproject/solarengine/src/engine/core/_Generated/AutoGenerated/hideineditorattribute.typeinfo.h"
#include "e:/engineproject/solarengine/src/engine/core/_Generated/AutoGenerated/itype.typeinfo.h"
#include "e:/engineproject/solarengine/src/engine/core/_Generated/AutoGenerated/object.typeinfo.h"
#include "e:/engineproject/solarengine/src/engine/core/_Generated/AutoGenerated/readonlyattribute.typeinfo.h"
#include "e:/engineproject/solarengine/src/engine/core/_Generated/AutoGenerated/spaceattribute.typeinfo.h"
#include "e:/engineproject/solarengine/src/engine/core/_Generated/AutoGenerated/testmeta.typeinfo.h"
#include "e:/engineproject/solarengine/src/engine/core/_Generated/AutoGenerated/variable.typeinfo.h"
#include "e:/engineproject/solarengine/src/engine/core/_Generated/AutoGenerated/visibleifattribute.typeinfo.h"

//-------------------------------------------------------------------------
// Registration functions

namespace SE
{
    class SECoreTyper final : public ITyper
    {
    protected:
        void RegisterTypes() override
        {
            // Meta
        

            // Type
            Types::RegisterTypeID(StableID::Generate<::SE::Object>(), TypeID(SE_TEXT("SE::Object")));
            TTypeCompositeInfo<::SE::Object>::RegisterType();

            // Enum
            Types::RegisterTypeID(StableID::Generate<::SE::CursorLockMode>(), TypeID(SE_TEXT("SE::CursorLockMode")));
            TTypeEnumInfo<::SE::CursorLockMode>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::MouseButton>(), TypeID(SE_TEXT("SE::MouseButton")));
            TTypeEnumInfo<::SE::MouseButton>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::GamepadAxis>(), TypeID(SE_TEXT("SE::GamepadAxis")));
            TTypeEnumInfo<::SE::GamepadAxis>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::GamepadButton>(), TypeID(SE_TEXT("SE::GamepadButton")));
            TTypeEnumInfo<::SE::GamepadButton>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::InputActionMode>(), TypeID(SE_TEXT("SE::InputActionMode")));
            TTypeEnumInfo<::SE::InputActionMode>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::InputActionState>(), TypeID(SE_TEXT("SE::InputActionState")));
            TTypeEnumInfo<::SE::InputActionState>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::InputGamepadIndex>(), TypeID(SE_TEXT("SE::InputGamepadIndex")));
            TTypeEnumInfo<::SE::InputGamepadIndex>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::InputAxisType>(), TypeID(SE_TEXT("SE::InputAxisType")));
            TTypeEnumInfo<::SE::InputAxisType>::RegisterType();
        }

        void UnregisterTypes() override
        {
            // Meta
        

            // Type
            TTypeCompositeInfo<::SE::Object>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Object>(), TypeID(SE_TEXT("SE::Object")));

            // Enum
            TTypeEnumInfo<::SE::CursorLockMode>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::CursorLockMode>(), TypeID(SE_TEXT("SE::CursorLockMode")));
            TTypeEnumInfo<::SE::MouseButton>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::MouseButton>(), TypeID(SE_TEXT("SE::MouseButton")));
            TTypeEnumInfo<::SE::GamepadAxis>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::GamepadAxis>(), TypeID(SE_TEXT("SE::GamepadAxis")));
            TTypeEnumInfo<::SE::GamepadButton>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::GamepadButton>(), TypeID(SE_TEXT("SE::GamepadButton")));
            TTypeEnumInfo<::SE::InputActionMode>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::InputActionMode>(), TypeID(SE_TEXT("SE::InputActionMode")));
            TTypeEnumInfo<::SE::InputActionState>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::InputActionState>(), TypeID(SE_TEXT("SE::InputActionState")));
            TTypeEnumInfo<::SE::InputGamepadIndex>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::InputGamepadIndex>(), TypeID(SE_TEXT("SE::InputGamepadIndex")));
            TTypeEnumInfo<::SE::InputAxisType>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::InputAxisType>(), TypeID(SE_TEXT("SE::InputAxisType")));
        }
    };

    SE_TYPER_REGISTER(SECoreTyper);
}
