//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Level/Actor.h
//-------------------------------------------------------------------------
#pragma warning disable CS0108
#pragma warning disable CS8603
#pragma warning disable CS8625
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using SE.Interop;

namespace SE
{
    [NativeMarshalling(typeof(ActorMarshaller))]
    public unsafe partial class Actor : SE.SceneObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Actor"/>.
        /// </summary>
        public Actor() : base()
        {
        }


        [LibraryImport("SERuntime", EntryPoint = "Actor_GetName", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial string Internal_GetName(IntPtr __obj);

        [LibraryImport("SERuntime", EntryPoint = "Actor_SetName", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_SetName(IntPtr __obj, string value);

        public string Name
        {
            get { return Internal_GetName(__unmanagedPtr); }
            set { Internal_SetName(__unmanagedPtr, value); }
        }

        [LibraryImport("SERuntime", EntryPoint = "Actor_GetScene", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial IntPtr Internal_GetScene(IntPtr __obj);

        /// <summary>
        /// &lt;summary&gt; Gets the scene object which contains this actor. &lt;/summary&gt;
        /// </summary>
        public SE.Scene Scene
        {
            get { return (SE.Scene)SE.Interop.ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(Internal_GetScene(__unmanagedPtr)); }
        }

        [LibraryImport("SERuntime", EntryPoint = "Actor_GetChildrenCount", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial int Internal_GetChildrenCount(IntPtr __obj);

        /// <summary>
        /// &lt;summary&gt; Gets amount of child actors. &lt;/summary&gt;
        /// </summary>
        public int ChildrenCount
        {
            get { return Internal_GetChildrenCount(__unmanagedPtr); }
        }

        [LibraryImport("SERuntime", EntryPoint = "Actor_GetIsActive", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static partial bool Internal_GetIsActive(IntPtr __obj);

        /// <summary>
        /// &lt;summary&gt; Gets value indicating if actor is active in the scene. &lt;/summary&gt;
        /// </summary>
        public bool IsActive
        {
            get { return Internal_GetIsActive(__unmanagedPtr); }
        }

        [LibraryImport("SERuntime", EntryPoint = "Actor_GetChild", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial IntPtr Internal_GetChild(IntPtr __obj, int index);

        /// <summary>
        /// &lt;summary&gt; Gets the child actor at the given index. &lt;/summary&gt; &lt;param name="index"&gt;The child actor index.&lt;/param&gt; &lt;returns&gt;The child actor (always valid).&lt;/returns&gt;
        /// </summary>
        public SE.Actor  GetChild(int index)
        {
            return (SE.Actor)SE.Interop.ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(Internal_GetChild(__unmanagedPtr, index));
        }

        [CustomMarshaller(typeof(Actor), MarshalMode.ManagedToUnmanagedIn, typeof(ActorMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Actor), MarshalMode.ElementIn, typeof(ActorMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Actor), MarshalMode.ManagedToUnmanagedOut, typeof(ActorMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Actor), MarshalMode.UnmanagedToManagedIn, typeof(ActorMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Actor), MarshalMode.ElementOut, typeof(ActorMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Actor), MarshalMode.ManagedToUnmanagedRef, typeof(ActorMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(Actor), MarshalMode.UnmanagedToManagedRef, typeof(ActorMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(Actor), MarshalMode.ElementRef, typeof(ActorMarshaller))]
        internal struct ActorMarshaller
        {
            #pragma warning disable 1591
            public static class NativeToManaged
            {
                public static Actor ConvertToManaged(IntPtr unmanaged) => Unsafe.As<Actor>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(Actor managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public static class ManagedToNative
            {
                public static Actor ConvertToManaged(IntPtr unmanaged) => Unsafe.As<Actor>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(Actor managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public struct Bidirectional
            {
                ManagedHandleMarshaller.Bidirectional marsh;
                public void FromManaged(Actor managed) => marsh.FromManaged(managed);
                public IntPtr ToUnmanaged() => marsh.ToUnmanaged();
                public void FromUnmanaged(IntPtr unmanaged) => marsh.FromUnmanaged(unmanaged);
                public Actor ToManaged() => Unsafe.As<Actor>(marsh.ToManaged());
                public void Free() => marsh.Free();
            }
            internal static Actor ConvertToManaged(IntPtr unmanaged) => Unsafe.As<Actor>(ManagedHandleMarshaller.ConvertToManaged(unmanaged));
            internal static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.Free(unmanaged);
            internal static Actor ToManaged(IntPtr managed) => Unsafe.As<Actor>(ManagedHandleMarshaller.ToManaged(managed));
            internal static IntPtr ToNative(Actor managed) => ManagedHandleMarshaller.ToNative(managed);
        #pragma warning restore 1591
        }

    }
}

namespace SE
{
    [NativeMarshalling(typeof(RenderActorMarshaller))]
    public unsafe abstract partial class RenderActor : SE.Actor
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RenderActor"/>.
        /// </summary>
        protected RenderActor() : base()
        {
        }


        [CustomMarshaller(typeof(RenderActor), MarshalMode.ManagedToUnmanagedIn, typeof(RenderActorMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(RenderActor), MarshalMode.ElementIn, typeof(RenderActorMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(RenderActor), MarshalMode.ManagedToUnmanagedOut, typeof(RenderActorMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(RenderActor), MarshalMode.UnmanagedToManagedIn, typeof(RenderActorMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(RenderActor), MarshalMode.ElementOut, typeof(RenderActorMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(RenderActor), MarshalMode.ManagedToUnmanagedRef, typeof(RenderActorMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(RenderActor), MarshalMode.UnmanagedToManagedRef, typeof(RenderActorMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(RenderActor), MarshalMode.ElementRef, typeof(RenderActorMarshaller))]
        internal struct RenderActorMarshaller
        {
            #pragma warning disable 1591
            public static class NativeToManaged
            {
                public static RenderActor ConvertToManaged(IntPtr unmanaged) => Unsafe.As<RenderActor>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(RenderActor managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public static class ManagedToNative
            {
                public static RenderActor ConvertToManaged(IntPtr unmanaged) => Unsafe.As<RenderActor>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(RenderActor managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public struct Bidirectional
            {
                ManagedHandleMarshaller.Bidirectional marsh;
                public void FromManaged(RenderActor managed) => marsh.FromManaged(managed);
                public IntPtr ToUnmanaged() => marsh.ToUnmanaged();
                public void FromUnmanaged(IntPtr unmanaged) => marsh.FromUnmanaged(unmanaged);
                public RenderActor ToManaged() => Unsafe.As<RenderActor>(marsh.ToManaged());
                public void Free() => marsh.Free();
            }
            internal static RenderActor ConvertToManaged(IntPtr unmanaged) => Unsafe.As<RenderActor>(ManagedHandleMarshaller.ConvertToManaged(unmanaged));
            internal static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.Free(unmanaged);
            internal static RenderActor ToManaged(IntPtr managed) => Unsafe.As<RenderActor>(ManagedHandleMarshaller.ToManaged(managed));
            internal static IntPtr ToNative(RenderActor managed) => ManagedHandleMarshaller.ToNative(managed);
        #pragma warning restore 1591
        }

    }
}

