//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Resource/Asset.h
//-------------------------------------------------------------------------
#pragma warning disable CS0108
#pragma warning disable CS8603
#pragma warning disable CS8625
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using SE.Interop;

namespace SE
{
    /// <summary>
    /// &lt;summary&gt; Asset objects base class. &lt;/summary&gt;
    /// </summary>
    [NativeMarshalling(typeof(AssetMarshaller))]
    public unsafe partial class Asset : SE.Object
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Asset"/>.
        /// </summary>
        public Asset() : base()
        {
        }


        [LibraryImport("SERuntime", EntryPoint = "Asset_GetReferencesCount", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial int Internal_GetReferencesCount(IntPtr __obj);

        /// <summary>
        /// &lt;summary&gt; Gets asset's reference count. Asset will be automatically unloaded when this reaches zero. &lt;/summary&gt;
        /// </summary>
        public int  GetReferencesCount()
        {
            return Internal_GetReferencesCount(__unmanagedPtr);
        }

        [CustomMarshaller(typeof(Asset), MarshalMode.ManagedToUnmanagedIn, typeof(AssetMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Asset), MarshalMode.ElementIn, typeof(AssetMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Asset), MarshalMode.ManagedToUnmanagedOut, typeof(AssetMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Asset), MarshalMode.UnmanagedToManagedIn, typeof(AssetMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Asset), MarshalMode.ElementOut, typeof(AssetMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Asset), MarshalMode.ManagedToUnmanagedRef, typeof(AssetMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(Asset), MarshalMode.UnmanagedToManagedRef, typeof(AssetMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(Asset), MarshalMode.ElementRef, typeof(AssetMarshaller))]
        internal struct AssetMarshaller
        {
            #pragma warning disable 1591
            public static class NativeToManaged
            {
                public static Asset ConvertToManaged(IntPtr unmanaged) => Unsafe.As<Asset>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(Asset managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public static class ManagedToNative
            {
                public static Asset ConvertToManaged(IntPtr unmanaged) => Unsafe.As<Asset>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(Asset managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public struct Bidirectional
            {
                ManagedHandleMarshaller.Bidirectional marsh;
                public void FromManaged(Asset managed) => marsh.FromManaged(managed);
                public IntPtr ToUnmanaged() => marsh.ToUnmanaged();
                public void FromUnmanaged(IntPtr unmanaged) => marsh.FromUnmanaged(unmanaged);
                public Asset ToManaged() => Unsafe.As<Asset>(marsh.ToManaged());
                public void Free() => marsh.Free();
            }
            internal static Asset ConvertToManaged(IntPtr unmanaged) => Unsafe.As<Asset>(ManagedHandleMarshaller.ConvertToManaged(unmanaged));
            internal static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.Free(unmanaged);
            internal static Asset ToManaged(IntPtr managed) => Unsafe.As<Asset>(ManagedHandleMarshaller.ToManaged(managed));
            internal static IntPtr ToNative(Asset managed) => ManagedHandleMarshaller.ToNative(managed);
        #pragma warning restore 1591
        }

    }
}

