//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Render/Assets/Texture/CubeTexture.h
//-------------------------------------------------------------------------
#pragma warning disable CS0108
#pragma warning disable CS8603
#pragma warning disable CS8625
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using SE.Interop;

namespace SE
{
    /// <summary>
    /// &lt;summary&gt; Cube texture asset contains 6 images that is usually stored on a GPU as a cube map (one slice per each axis direction). &lt;/summary&gt;
    /// </summary>
    [NativeMarshalling(typeof(CubeTextureMarshaller))]
    public unsafe partial class CubeTexture : SE.TextureBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CubeTexture"/>.
        /// </summary>
        public CubeTexture() : base()
        {
        }


        [CustomMarshaller(typeof(CubeTexture), MarshalMode.ManagedToUnmanagedIn, typeof(CubeTextureMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(CubeTexture), MarshalMode.ElementIn, typeof(CubeTextureMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(CubeTexture), MarshalMode.ManagedToUnmanagedOut, typeof(CubeTextureMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(CubeTexture), MarshalMode.UnmanagedToManagedIn, typeof(CubeTextureMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(CubeTexture), MarshalMode.ElementOut, typeof(CubeTextureMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(CubeTexture), MarshalMode.ManagedToUnmanagedRef, typeof(CubeTextureMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(CubeTexture), MarshalMode.UnmanagedToManagedRef, typeof(CubeTextureMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(CubeTexture), MarshalMode.ElementRef, typeof(CubeTextureMarshaller))]
        internal struct CubeTextureMarshaller
        {
            #pragma warning disable 1591
            public static class NativeToManaged
            {
                public static CubeTexture ConvertToManaged(IntPtr unmanaged) => Unsafe.As<CubeTexture>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(CubeTexture managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public static class ManagedToNative
            {
                public static CubeTexture ConvertToManaged(IntPtr unmanaged) => Unsafe.As<CubeTexture>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(CubeTexture managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public struct Bidirectional
            {
                ManagedHandleMarshaller.Bidirectional marsh;
                public void FromManaged(CubeTexture managed) => marsh.FromManaged(managed);
                public IntPtr ToUnmanaged() => marsh.ToUnmanaged();
                public void FromUnmanaged(IntPtr unmanaged) => marsh.FromUnmanaged(unmanaged);
                public CubeTexture ToManaged() => Unsafe.As<CubeTexture>(marsh.ToManaged());
                public void Free() => marsh.Free();
            }
            internal static CubeTexture ConvertToManaged(IntPtr unmanaged) => Unsafe.As<CubeTexture>(ManagedHandleMarshaller.ConvertToManaged(unmanaged));
            internal static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.Free(unmanaged);
            internal static CubeTexture ToManaged(IntPtr managed) => Unsafe.As<CubeTexture>(ManagedHandleMarshaller.ToManaged(managed));
            internal static IntPtr ToNative(CubeTexture managed) => ManagedHandleMarshaller.ToNative(managed);
        #pragma warning restore 1591
        }

    }
}

