#pragma once
//*************************************************************************
// This is an auto-generated file - DO NOT edit
//*************************************************************************
#include "E:/EngineProject/SolarEngine/Src/Engine//Runtime/Core/Platform/Defines.h"
#include "Runtime/Core/Scripting/ManagedCLR/CLRUtils.h"
#include "Runtime/Core/Scripting/ScriptingObject.h"
#include "Runtime/Core/Scripting/Internal/InternalCalls.h"
#include "Runtime/Core/Scripting/ScriptingType.h"

//-------------------------------------------------------------------------
// Bindings
//-------------------------------------------------------------------------
//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Core/Platform/Defines.h
//-------------------------------------------------------------------------
#include "E:/EngineProject/SolarEngine/Src/Engine//Runtime/Core/Platform/Defines.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/BindingsInterop.h"
#include "Runtime/Core/Scripting/ManagedCLR/CLRUtils.h"
#include "Runtime/Core/Scripting/Scripting.h"
#include "Runtime/Core/Scripting/Binary/ManagedBinaryModule.h"
#include "Runtime/Core/Scripting/ScriptingObject.h"
#include "Runtime/Core/Scripting/Internal/InternalCalls.h"
#include "Runtime/Core/Scripting/ScriptingType.h"

namespace SE
{
class PlatformTypeInternal
{
public:
    static ScriptingType::EnumItem Items[];
};

ScriptingType::EnumItem PlatformTypeInternal::Items[] = {
    { (uint64)::SE::PlatformType::Windows, "Windows" },
    { (uint64)::SE::PlatformType::XboxOne, "XboxOne" },
    { (uint64)::SE::PlatformType::UWP, "UWP" },
    { (uint64)::SE::PlatformType::Linux, "Linux" },
    { (uint64)::SE::PlatformType::PS4, "PS4" },
    { (uint64)::SE::PlatformType::XboxScarlett, "XboxScarlett" },
    { (uint64)::SE::PlatformType::Android, "Android" },
    { (uint64)::SE::PlatformType::Switch, "Switch" },
    { (uint64)::SE::PlatformType::PS5, "PS5" },
    { (uint64)::SE::PlatformType::Mac, "Mac" },
    { (uint64)::SE::PlatformType::iOS, "iOS" },
    { 0, nullptr }
};

inline ScriptingTypeInitializer PlatformType_TypeInitializer(
    (BinaryModule*)GetBinaryModuleSERuntime(),
    StringAnsiView("SE::PlatformType", ARRAY_SIZE("SE::PlatformType") - 1),
    sizeof(::SE::PlatformType),
    StableID::Generate<::SE::PlatformType>(),
    PlatformTypeInternal::Items
);

}
namespace SE
{
class ArchitectureTypeInternal
{
public:
    static ScriptingType::EnumItem Items[];
};

ScriptingType::EnumItem ArchitectureTypeInternal::Items[] = {
    { (uint64)::SE::ArchitectureType::AnyCPU, "AnyCPU" },
    { (uint64)::SE::ArchitectureType::x86, "x86" },
    { (uint64)::SE::ArchitectureType::x64, "x64" },
    { (uint64)::SE::ArchitectureType::ARM, "ARM" },
    { (uint64)::SE::ArchitectureType::ARM64, "ARM64" },
    { 0, nullptr }
};

inline ScriptingTypeInitializer ArchitectureType_TypeInitializer(
    (BinaryModule*)GetBinaryModuleSERuntime(),
    StringAnsiView("SE::ArchitectureType", ARRAY_SIZE("SE::ArchitectureType") - 1),
    sizeof(::SE::ArchitectureType),
    StableID::Generate<::SE::ArchitectureType>(),
    ArchitectureTypeInternal::Items
);

}
