//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Core/Platform/Defines.h
//-------------------------------------------------------------------------
#pragma warning disable CS0108
#pragma warning disable CS8603
#pragma warning disable CS8625
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using SE.Interop;

namespace SE
{
    /// <summary>
    /// &lt;summary&gt; The platform the game is running. &lt;/summary&gt;
    /// </summary>
    public enum PlatformType : int
    {
        /// <summary>
        /// &lt;summary&gt; Running on Windows. &lt;/summary&gt;
        /// </summary>
        Windows = 1,
        /// <summary>
        /// &lt;summary&gt; Running on Xbox One. &lt;/summary&gt;
        /// </summary>
        XboxOne = 2,
        /// <summary>
        /// &lt;summary&gt; Running Windows Store App (Universal Windows Platform). &lt;/summary&gt; API_ENUM(Attributes = "EditorDisplay(null, \"UWP")")
        /// </summary>
        UWP = 3,
        /// <summary>
        /// &lt;summary&gt; Running on Linux system. &lt;/summary&gt;
        /// </summary>
        Linux = 4,
        /// <summary>
        /// &lt;summary&gt; Running on PlayStation 4. &lt;/summary&gt; API_ENUM(Attributes = "EditorDisplay(null, \"PS4")")
        /// </summary>
        PS4 = 5,
        /// <summary>
        /// &lt;summary&gt; Running on Xbox Series X. &lt;/summary&gt;
        /// </summary>
        XboxScarlett = 6,
        /// <summary>
        /// &lt;summary&gt; Running on Android. &lt;/summary&gt;
        /// </summary>
        Android = 7,
        /// <summary>
        /// &lt;summary&gt; Running on Switch. &lt;/summary&gt;
        /// </summary>
        Switch = 8,
        /// <summary>
        /// &lt;summary&gt; Running on PlayStation 5. &lt;/summary&gt; API_ENUM(Attributes = "EditorDisplay(null, \"PS5")")
        /// </summary>
        PS5 = 9,
        /// <summary>
        /// &lt;summary&gt; Running on Mac. &lt;/summary&gt;
        /// </summary>
        Mac = 10,
        /// <summary>
        /// &lt;summary&gt; Running on iPhone. &lt;/summary&gt; API_ENUM(Attributes = "EditorDisplay(null, \"iOS")")
        /// </summary>
        iOS = 11
    }
}

namespace SE
{
    /// <summary>
    /// &lt;summary&gt; The platform architecture types. &lt;/summary&gt;
    /// </summary>
    public enum ArchitectureType : int
    {
        /// <summary>
        /// &lt;summary&gt; Anything or not important. &lt;/summary&gt;
        /// </summary>
        AnyCPU = 0,
        /// <summary>
        /// &lt;summary&gt; The x86 32-bit. &lt;/summary&gt;
        /// </summary>
        x86 = 1,
        /// <summary>
        /// &lt;summary&gt; The x86 64-bit. &lt;/summary&gt;
        /// </summary>
        x64 = 2,
        /// <summary>
        /// &lt;summary&gt; The ARM 32-bit. &lt;/summary&gt;
        /// </summary>
        ARM = 3,
        /// <summary>
        /// &lt;summary&gt; The ARM 64-bit. &lt;/summary&gt;
        /// </summary>
        ARM64 = 4
    }
}

