//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Input/Enums.h
//-------------------------------------------------------------------------
#pragma warning disable CS0108
#pragma warning disable CS8603
#pragma warning disable CS8625
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using SE.Interop;

namespace SE
{
    /// <summary>
    /// &lt;summary&gt; Hardware mouse cursor behavior. &lt;/summary&gt;
    /// </summary>
    public enum CursorLockMode : int
    {
        /// <summary>
        /// &lt;summary&gt; The default mode. &lt;/summary&gt;
        /// </summary>
        None = 0,
        /// <summary>
        /// &lt;summary&gt; Cursor position is locked to the center of the game window. &lt;/summary&gt;
        /// </summary>
        Locked = 1,
        /// <summary>
        /// &lt;summary&gt; Cursor position is confined to the bounds of the game window. &lt;/summary&gt;
        /// </summary>
        Clipped = 2
    }
}

namespace SE
{
    /// <summary>
    /// &lt;summary&gt; Mouse buttons types. &lt;/summary&gt;
    /// </summary>
    public enum MouseButton : int
    {
        /// <summary>
        /// &lt;summary&gt; No button. &lt;/summary&gt;
        /// </summary>
        None = 0,
        /// <summary>
        /// &lt;summary&gt; Left button. &lt;/summary&gt;
        /// </summary>
        Left = 1,
        /// <summary>
        /// &lt;summary&gt; Middle button. &lt;/summary&gt;
        /// </summary>
        Middle = 2,
        /// <summary>
        /// &lt;summary&gt; Right button. &lt;/summary&gt;
        /// </summary>
        Right = 3,
        /// <summary>
        /// &lt;summary&gt; Extended button 1 (or XButton1). &lt;/summary&gt;
        /// </summary>
        Extended1 = 4,
        /// <summary>
        /// &lt;summary&gt; Extended button 2 (or XButton2). &lt;/summary&gt;
        /// </summary>
        Extended2 = 5,
        /// <summary>
        /// &lt;summary&gt; Extended button 2 (or XButton2). &lt;/summary&gt;
        /// </summary>
        MAX = 6
    }
}

namespace SE
{
    /// <summary>
    /// &lt;summary&gt; Axis for gamepad. &lt;/summary&gt;
    /// </summary>
    public enum GamepadAxis : int
    {
        /// <summary>
        /// &lt;summary&gt; No axis. &lt;/summary&gt;
        /// </summary>
        None = 0,
        /// <summary>
        /// &lt;summary&gt; The X-Axis of the left thumb stick. &lt;/summary&gt;
        /// </summary>
        LeftStickX = 1,
        /// <summary>
        /// &lt;summary&gt; The Y-Axis of the left thumb stick. &lt;/summary&gt;
        /// </summary>
        LeftStickY = 2,
        /// <summary>
        /// &lt;summary&gt; The X-Axis of the right thumb stick. &lt;/summary&gt;
        /// </summary>
        RightStickX = 3,
        /// <summary>
        /// &lt;summary&gt; The Y-Axis of the right thumb stick. &lt;/summary&gt;
        /// </summary>
        RightStickY = 4,
        /// <summary>
        /// &lt;summary&gt; The left trigger. &lt;/summary&gt;
        /// </summary>
        LeftTrigger = 5,
        /// <summary>
        /// &lt;summary&gt; The right trigger. &lt;/summary&gt;
        /// </summary>
        RightTrigger = 6,
        /// <summary>
        /// &lt;summary&gt; The right trigger. &lt;/summary&gt;
        /// </summary>
        MAX = 7
    }
}

namespace SE
{
    /// <summary>
    /// &lt;summary&gt; Buttons for gamepad. &lt;/summary&gt;
    /// </summary>
    public enum GamepadButton : int
    {
        /// <summary>
        /// &lt;summary&gt; No buttons. &lt;/summary&gt;
        /// </summary>
        None = 0,
        /// <summary>
        /// &lt;summary&gt; PadUp button (DPad / Directional Pad). &lt;/summary&gt;
        /// </summary>
        DPadUp = 1,
        /// <summary>
        /// &lt;summary&gt; PadDown button (DPad / Directional Pad). &lt;/summary&gt;
        /// </summary>
        DPadDown = 2,
        /// <summary>
        /// &lt;summary&gt; PadLeft button (DPad / Directional Pad). &lt;/summary&gt;
        /// </summary>
        DPadLeft = 3,
        /// <summary>
        /// &lt;summary&gt; PadRight button (DPad / Directional Pad). &lt;/summary&gt;
        /// </summary>
        DPadRight = 4,
        /// <summary>
        /// &lt;summary&gt; Start button. &lt;/summary&gt;
        /// </summary>
        Start = 5,
        /// <summary>
        /// &lt;summary&gt; Back button. &lt;/summary&gt;
        /// </summary>
        Back = 6,
        /// <summary>
        /// &lt;summary&gt; Left thumbstick button. &lt;/summary&gt;
        /// </summary>
        LeftThumb = 7,
        /// <summary>
        /// &lt;summary&gt; Right thumbstick button. &lt;/summary&gt;
        /// </summary>
        RightThumb = 8,
        /// <summary>
        /// &lt;summary&gt; Left shoulder button. &lt;/summary&gt;
        /// </summary>
        LeftShoulder = 9,
        /// <summary>
        /// &lt;summary&gt; Right shoulder button. &lt;/summary&gt;
        /// </summary>
        RightShoulder = 10,
        /// <summary>
        /// &lt;summary&gt; Left trigger button. &lt;/summary&gt;
        /// </summary>
        LeftTrigger = 11,
        /// <summary>
        /// &lt;summary&gt; Right trigger button. &lt;/summary&gt;
        /// </summary>
        RightTrigger = 12,
        /// <summary>
        /// &lt;summary&gt; A (face button down). &lt;/summary&gt;
        /// </summary>
        A = 13,
        /// <summary>
        /// &lt;summary&gt; B (face button right). &lt;/summary&gt;
        /// </summary>
        B = 14,
        /// <summary>
        /// &lt;summary&gt; X (face button left). &lt;/summary&gt;
        /// </summary>
        X = 15,
        /// <summary>
        /// &lt;summary&gt; Y (face button up). &lt;/summary&gt;
        /// </summary>
        Y = 16,
        /// <summary>
        /// &lt;summary&gt; The left stick up. &lt;/summary&gt;
        /// </summary>
        LeftStickUp = 17,
        /// <summary>
        /// &lt;summary&gt; The left stick down. &lt;/summary&gt;
        /// </summary>
        LeftStickDown = 18,
        /// <summary>
        /// &lt;summary&gt; The left stick left. &lt;/summary&gt;
        /// </summary>
        LeftStickLeft = 19,
        /// <summary>
        /// &lt;summary&gt; The left stick right. &lt;/summary&gt;
        /// </summary>
        LeftStickRight = 20,
        /// <summary>
        /// &lt;summary&gt; The right stick up. &lt;/summary&gt;
        /// </summary>
        RightStickUp = 21,
        /// <summary>
        /// &lt;summary&gt; The right stick down. &lt;/summary&gt;
        /// </summary>
        RightStickDown = 22,
        /// <summary>
        /// &lt;summary&gt; The right stick left. &lt;/summary&gt;
        /// </summary>
        RightStickLeft = 23,
        /// <summary>
        /// &lt;summary&gt; The right stick right. &lt;/summary&gt;
        /// </summary>
        RightStickRight = 24,
        /// <summary>
        /// &lt;summary&gt; The right stick right. &lt;/summary&gt;
        /// </summary>
        MAX = 25
    }
}

namespace SE
{
    /// <summary>
    /// &lt;summary&gt; The input action event trigger modes. &lt;/summary&gt;
    /// </summary>
    public enum InputActionMode : int
    {
        /// <summary>
        /// &lt;summary&gt; User is pressing the key/button. &lt;/summary&gt;
        /// </summary>
        Pressing = 0,
        /// <summary>
        /// &lt;summary&gt; User pressed the key/button (but wasn't pressing it in the previous frame). &lt;/summary&gt;
        /// </summary>
        Press = 1,
        /// <summary>
        /// &lt;summary&gt; User released the key/button (was pressing it in the previous frame). &lt;/summary&gt;
        /// </summary>
        Release = 2
    }
}

namespace SE
{
    /// <summary>
    /// &lt;summary&gt; The input action event phases. &lt;/summary&gt;
    /// </summary>
    public enum InputActionState : int
    {
        /// <summary>
        /// &lt;summary&gt; The key/button is not assigned. &lt;/summary&gt;
        /// </summary>
        None = 0,
        /// <summary>
        /// &lt;summary&gt; The key/button is waiting for input. &lt;/summary&gt;
        /// </summary>
        Waiting = 1,
        /// <summary>
        /// &lt;summary&gt; User is pressing the key/button. &lt;/summary&gt;
        /// </summary>
        Pressing = 2,
        /// <summary>
        /// &lt;summary&gt; User pressed the key/button (but wasn't pressing it in the previous frame). &lt;/summary&gt;
        /// </summary>
        Press = 3,
        /// <summary>
        /// &lt;summary&gt; User released the key/button (was pressing it in the previous frame). &lt;/summary&gt;
        /// </summary>
        Release = 4
    }
}

namespace SE
{
    /// <summary>
    /// &lt;summary&gt; The input gamepad index. &lt;/summary&gt;
    /// </summary>
    public enum InputGamepadIndex : int
    {
        /// <summary>
        /// &lt;summary&gt; All detected gamepads. &lt;/summary&gt;
        /// </summary>
        All = -1,
        /// <summary>
        /// &lt;summary&gt; The gamepad no. 0. &lt;/summary&gt;
        /// </summary>
        Gamepad0 = 0,
        /// <summary>
        /// &lt;summary&gt; The gamepad no. 1. &lt;/summary&gt;
        /// </summary>
        Gamepad1 = 1,
        /// <summary>
        /// &lt;summary&gt; The gamepad no. 2. &lt;/summary&gt;
        /// </summary>
        Gamepad2 = 2,
        /// <summary>
        /// &lt;summary&gt; The gamepad no. 3. &lt;/summary&gt;
        /// </summary>
        Gamepad3 = 3,
        /// <summary>
        /// &lt;summary&gt; The gamepad no. 4. &lt;/summary&gt;
        /// </summary>
        Gamepad4 = 4,
        /// <summary>
        /// &lt;summary&gt; The gamepad no. 5. &lt;/summary&gt;
        /// </summary>
        Gamepad5 = 5
    }
}

namespace SE
{
    /// <summary>
    /// &lt;summary&gt; The input axes types. &lt;/summary&gt;
    /// </summary>
    public enum InputAxisType : int
    {
        /// <summary>
        /// &lt;summary&gt; The mouse X-Axis (mouse delta position scaled by the sensitivity). &lt;/summary&gt;
        /// </summary>
        MouseX = 0,
        /// <summary>
        /// &lt;summary&gt; The mouse Y-Axis (mouse delta position scaled by the sensitivity). &lt;/summary&gt;
        /// </summary>
        MouseY = 1,
        /// <summary>
        /// &lt;summary&gt; The mouse wheel (mouse wheel delta scaled by the sensitivity). &lt;/summary&gt;
        /// </summary>
        MouseWheel = 2,
        /// <summary>
        /// &lt;summary&gt; The gamepad X-Axis of the left thumb stick. &lt;/summary&gt;
        /// </summary>
        GamepadLeftStickX = 3,
        /// <summary>
        /// &lt;summary&gt; The gamepad Y-Axis of the left thumb stick. &lt;/summary&gt;
        /// </summary>
        GamepadLeftStickY = 4,
        /// <summary>
        /// &lt;summary&gt; The gamepad X-Axis of the right thumb stick. &lt;/summary&gt;
        /// </summary>
        GamepadRightStickX = 5,
        /// <summary>
        /// &lt;summary&gt; The gamepad Y-Axis of the right thumb stick. &lt;/summary&gt;
        /// </summary>
        GamepadRightStickY = 6,
        /// <summary>
        /// &lt;summary&gt; The gamepad left trigger. &lt;/summary&gt;
        /// </summary>
        GamepadLeftTrigger = 7,
        /// <summary>
        /// &lt;summary&gt; The gamepad right trigger. &lt;/summary&gt;
        /// </summary>
        GamepadRightTrigger = 8,
        /// <summary>
        /// &lt;summary&gt; The keyboard only mode. For key inputs. &lt;/summary&gt;
        /// </summary>
        KeyboardOnly = 9,
        /// <summary>
        /// &lt;summary&gt; Pad X axis - left/right (DPad / Directional Pad). &lt;/summary&gt;
        /// </summary>
        GamepadDPadX = 10,
        /// <summary>
        /// &lt;summary&gt; Pad Y axis - up/down (DPad / Directional Pad). &lt;/summary&gt;
        /// </summary>
        GamepadDPadY = 11
    }
}

