//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Render/2D/Font.h
//-------------------------------------------------------------------------
#pragma warning disable CS0108
#pragma warning disable CS8603
#pragma warning disable CS8625
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using SE.Interop;

namespace SE
{
        [CustomMarshaller(typeof(TextRange), MarshalMode.ManagedToUnmanagedIn, typeof(TextRangeMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(TextRange), MarshalMode.UnmanagedToManagedOut, typeof(TextRangeMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(TextRange), MarshalMode.ElementIn, typeof(TextRangeMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(TextRange), MarshalMode.ManagedToUnmanagedOut, typeof(TextRangeMarshaller.NativeToManaged))]
        [CustomMarshaller(typeof(TextRange), MarshalMode.UnmanagedToManagedIn, typeof(TextRangeMarshaller.NativeToManaged))]
        [CustomMarshaller(typeof(TextRange), MarshalMode.ElementOut, typeof(TextRangeMarshaller.NativeToManaged))]
        [CustomMarshaller(typeof(TextRange), MarshalMode.ManagedToUnmanagedRef, typeof(TextRangeMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(TextRange), MarshalMode.UnmanagedToManagedRef, typeof(TextRangeMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(TextRange), MarshalMode.ElementRef, typeof(TextRangeMarshaller))]
        internal static partial class TextRangeMarshaller
        {
            [StructLayout(LayoutKind.Sequential)]
            internal unsafe struct TextRangeInternal
            {
                public int StartIndex;
                public int EndIndex;
            }

            public static TextRange ConvertToManaged(TextRangeInternal unmanaged)
            {
                var result = new TextRange();
                result.StartIndex = unmanaged.StartIndex;
                result.EndIndex = unmanaged.EndIndex;
                return result;
            }

            public static TextRangeInternal ConvertToUnmanaged(TextRange managed)
            {
                var result = new TextRangeInternal();
                result.StartIndex = managed.StartIndex;
                result.EndIndex = managed.EndIndex;
                return result;
            }

            public static void Free(TextRangeInternal unmanaged) { }

            public static class ManagedToNative
            {
                public static TextRange ConvertToManaged(TextRangeInternal unmanaged) => TextRangeMarshaller.ConvertToManaged(unmanaged);
                public static TextRangeInternal ConvertToUnmanaged(TextRange managed) => TextRangeMarshaller.ConvertToUnmanaged(managed);
                public static void Free(TextRangeInternal unmanaged) => TextRangeMarshaller.Free(unmanaged);
            }

            public static class NativeToManaged
            {
                public static TextRange ConvertToManaged(TextRangeInternal unmanaged) => TextRangeMarshaller.ConvertToManaged(unmanaged);
                public static TextRangeInternal ConvertToUnmanaged(TextRange managed) => TextRangeMarshaller.ConvertToUnmanaged(managed);
                public static void Free(TextRangeInternal unmanaged) => TextRangeMarshaller.Free(unmanaged);
            }

            public ref struct Bidirectional
            {
                private TextRangeInternal unmanaged;
                private TextRange managed;

                public Bidirectional(TextRange managed)
                {
                    this.managed = managed;
                    unmanaged = TextRangeMarshaller.ConvertToUnmanaged(managed);
                }

                public void FromManaged(TextRange managed) => this.managed = managed;
                public TextRangeInternal ToUnmanaged() { unmanaged = TextRangeMarshaller.ConvertToUnmanaged(managed); return unmanaged; }
                public void FromUnmanaged(TextRangeInternal unmanaged) => this.unmanaged = unmanaged;
                public TextRange ToManaged()
                {
                    managed = TextRangeMarshaller.ConvertToManaged(unmanaged);
                    return managed;
                }
                public void Free() { }
            }
        }

    /// <summary>
    /// &lt;summary&gt; The text range. &lt;/summary&gt;
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    [NativeMarshalling(typeof(TextRangeMarshaller))]
    public unsafe partial struct TextRange
    {
        /// <summary>
        /// &lt;summary&gt; The start index (inclusive). &lt;/summary&gt;
        /// </summary>
        public int StartIndex;

        /// <summary>
        /// &lt;summary&gt; The end index (exclusive). &lt;/summary&gt;
        /// </summary>
        public int EndIndex;

        public static TextRange Default => new TextRange();

    }
}

namespace SE
{
    /// <summary>
    /// &lt;summary&gt; Represents font object that can be using during text rendering (it uses Font Asset but with pre-cached data for chosen font properties). &lt;/summary&gt;
    /// </summary>
    [NativeMarshalling(typeof(FontMarshaller))]
    public unsafe partial class Font : SE.Object
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Font"/>.
        /// </summary>
        public Font() : base()
        {
        }


        [LibraryImport("SERuntime", EntryPoint = "Font_GetAsset", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial IntPtr Internal_GetAsset(IntPtr __obj);

        [LibraryImport("SERuntime", EntryPoint = "Font_GetSize", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial float Internal_GetSize(IntPtr __obj);

        [LibraryImport("SERuntime", EntryPoint = "Font_GetHeight", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial int Internal_GetHeight(IntPtr __obj);

        [LibraryImport("SERuntime", EntryPoint = "Font_GetAscender", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial int Internal_GetAscender(IntPtr __obj);

        [LibraryImport("SERuntime", EntryPoint = "Font_GetDescender", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial int Internal_GetDescender(IntPtr __obj);

        [LibraryImport("SERuntime", EntryPoint = "Font_GetLineGap", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial int Internal_GetLineGap(IntPtr __obj);

        [LibraryImport("SERuntime", EntryPoint = "Font_CacheText", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_CacheText(IntPtr __obj, string text);

        [LibraryImport("SERuntime", EntryPoint = "Font_Invalidate", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_Invalidate(IntPtr __obj);

        [LibraryImport("SERuntime", EntryPoint = "Font_MeasureText", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial SE.Float2 Internal_MeasureText(IntPtr __obj, string text, ref SE.TextLayoutOptions layout);

        [LibraryImport("SERuntime", EntryPoint = "Font_HitTestText", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial int Internal_HitTestText(IntPtr __obj, string text, ref SE.Float2 location, ref SE.TextLayoutOptions layout);

        [LibraryImport("SERuntime", EntryPoint = "Font_GetCharPosition", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial SE.Float2 Internal_GetCharPosition(IntPtr __obj, string text, int index, ref SE.TextLayoutOptions layout);

        /// <summary>
        /// &lt;summary&gt; Gets parent font asset that contains font family used by this font. &lt;/summary&gt;
        /// </summary>
        public SE.FontAsset  GetAsset()
        {
            return (SE.FontAsset)SE.Interop.ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(Internal_GetAsset(__unmanagedPtr));
        }

        /// <summary>
        /// &lt;summary&gt; Gets font size. &lt;/summary&gt;
        /// </summary>
        public float  GetSize()
        {
            return Internal_GetSize(__unmanagedPtr);
        }

        /// <summary>
        /// &lt;summary&gt; Gets characters height. &lt;/summary&gt;
        /// </summary>
        public int  GetHeight()
        {
            return Internal_GetHeight(__unmanagedPtr);
        }

        /// <summary>
        /// &lt;summary&gt; Gets the largest vertical distance above the baseline for any character in the font. &lt;/summary&gt;
        /// </summary>
        public int  GetAscender()
        {
            return Internal_GetAscender(__unmanagedPtr);
        }

        /// <summary>
        /// &lt;summary&gt; Gets the largest vertical distance below the baseline for any character in the font. &lt;/summary&gt;
        /// </summary>
        public int  GetDescender()
        {
            return Internal_GetDescender(__unmanagedPtr);
        }

        /// <summary>
        /// &lt;summary&gt; Gets the line gap property. &lt;/summary&gt;
        /// </summary>
        public int  GetLineGap()
        {
            return Internal_GetLineGap(__unmanagedPtr);
        }

        /// <summary>
        /// &lt;summary&gt; Caches the given text to prepared for the rendering. &lt;/summary&gt; &lt;param name="text"&gt;The text witch characters to cache.&lt;/param&gt;
        /// </summary>
        public void  CacheText(string text)
        {
            Internal_CacheText(__unmanagedPtr, text);
        }

        /// <summary>
        /// &lt;summary&gt; Invalidates all cached dynamic font atlases using this font. Can be used to reload font characters after changing font asset options. &lt;/summary&gt;
        /// </summary>
        public void  Invalidate()
        {
            Internal_Invalidate(__unmanagedPtr);
        }

        /// <summary>
        /// &lt;summary&gt; Measures minimum size of the rectangle that will be needed to draw given text. &lt;/summary&gt; &lt;param name="text"&gt;The input text to test.&lt;/param&gt; &lt;param name="layout"&gt;The layout properties.&lt;/param&gt; &lt;returns&gt;The minimum size for that text and fot to render properly.&lt;/returns&gt;
        /// </summary>
        public SE.Float2  MeasureText(string text, ref SE.TextLayoutOptions layout)
        {
            return Internal_MeasureText(__unmanagedPtr, text, ref layout);
        }

        /// <summary>
        /// &lt;summary&gt; Calculates hit character index at given location. &lt;/summary&gt; &lt;param name="text"&gt;The input text to test.&lt;/param&gt; &lt;param name="location"&gt;The input location to test.&lt;/param&gt; &lt;param name="layout"&gt;The text layout properties.&lt;/param&gt; &lt;returns&gt;The selected character position index (can be equal to text length if location is outside of the layout rectangle).&lt;/returns&gt;
        /// </summary>
        public int  HitTestText(string text, ref SE.Float2 location, ref SE.TextLayoutOptions layout)
        {
            return Internal_HitTestText(__unmanagedPtr, text, ref location, ref layout);
        }

        /// <summary>
        /// &lt;summary&gt; Calculates character position for given text and character index. &lt;/summary&gt; &lt;param name="text"&gt;The input text to test.&lt;/param&gt; &lt;param name="index"&gt;The text position to get coordinates of.&lt;/param&gt; &lt;param name="layout"&gt;The text layout properties.&lt;/param&gt; &lt;returns&gt;The character position (upper left corner which can be used for a caret position).&lt;/returns&gt;
        /// </summary>
        public SE.Float2  GetCharPosition(string text, int index, ref SE.TextLayoutOptions layout)
        {
            return Internal_GetCharPosition(__unmanagedPtr, text, index, ref layout);
        }

        [CustomMarshaller(typeof(Font), MarshalMode.ManagedToUnmanagedIn, typeof(FontMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Font), MarshalMode.ElementIn, typeof(FontMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Font), MarshalMode.ManagedToUnmanagedOut, typeof(FontMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Font), MarshalMode.UnmanagedToManagedIn, typeof(FontMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Font), MarshalMode.ElementOut, typeof(FontMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Font), MarshalMode.ManagedToUnmanagedRef, typeof(FontMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(Font), MarshalMode.UnmanagedToManagedRef, typeof(FontMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(Font), MarshalMode.ElementRef, typeof(FontMarshaller))]
        internal struct FontMarshaller
        {
            #pragma warning disable 1591
            public static class NativeToManaged
            {
                public static Font ConvertToManaged(IntPtr unmanaged) => Unsafe.As<Font>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(Font managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public static class ManagedToNative
            {
                public static Font ConvertToManaged(IntPtr unmanaged) => Unsafe.As<Font>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(Font managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public struct Bidirectional
            {
                ManagedHandleMarshaller.Bidirectional marsh;
                public void FromManaged(Font managed) => marsh.FromManaged(managed);
                public IntPtr ToUnmanaged() => marsh.ToUnmanaged();
                public void FromUnmanaged(IntPtr unmanaged) => marsh.FromUnmanaged(unmanaged);
                public Font ToManaged() => Unsafe.As<Font>(marsh.ToManaged());
                public void Free() => marsh.Free();
            }
            internal static Font ConvertToManaged(IntPtr unmanaged) => Unsafe.As<Font>(ManagedHandleMarshaller.ConvertToManaged(unmanaged));
            internal static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.Free(unmanaged);
            internal static Font ToManaged(IntPtr managed) => Unsafe.As<Font>(ManagedHandleMarshaller.ToManaged(managed));
            internal static IntPtr ToNative(Font managed) => ManagedHandleMarshaller.ToNative(managed);
        #pragma warning restore 1591
        }

    }
}

