//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Render/2D/FontAsset.h
//-------------------------------------------------------------------------
#pragma warning disable CS0108
#pragma warning disable CS8603
#pragma warning disable CS8625
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using SE.Interop;

namespace SE
{
    /// <summary>
    /// &lt;summary&gt; Font asset contains glyph collection and cached data used to render text. &lt;/summary&gt;
    /// </summary>
    [NativeMarshalling(typeof(FontAssetMarshaller))]
    public unsafe partial class FontAsset : SE.BinaryAsset
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FontAsset"/>.
        /// </summary>
        public FontAsset() : base()
        {
        }


        [LibraryImport("SERuntime", EntryPoint = "FontAsset_CreateFont", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial IntPtr Internal_CreateFont(IntPtr __obj, float size);

        /// <summary>
        /// &lt;summary&gt; Creates the font object of given characters size. &lt;/summary&gt; &lt;param name="size"&gt;The font characters size.&lt;/param&gt; &lt;returns&gt;The created font object.&lt;/returns&gt;
        /// </summary>
        public SE.Font  CreateFont(float size)
        {
            return (SE.Font)SE.Interop.ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(Internal_CreateFont(__unmanagedPtr, size));
        }

        [CustomMarshaller(typeof(FontAsset), MarshalMode.ManagedToUnmanagedIn, typeof(FontAssetMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(FontAsset), MarshalMode.ElementIn, typeof(FontAssetMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(FontAsset), MarshalMode.ManagedToUnmanagedOut, typeof(FontAssetMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(FontAsset), MarshalMode.UnmanagedToManagedIn, typeof(FontAssetMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(FontAsset), MarshalMode.ElementOut, typeof(FontAssetMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(FontAsset), MarshalMode.ManagedToUnmanagedRef, typeof(FontAssetMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(FontAsset), MarshalMode.UnmanagedToManagedRef, typeof(FontAssetMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(FontAsset), MarshalMode.ElementRef, typeof(FontAssetMarshaller))]
        internal struct FontAssetMarshaller
        {
            #pragma warning disable 1591
            public static class NativeToManaged
            {
                public static FontAsset ConvertToManaged(IntPtr unmanaged) => Unsafe.As<FontAsset>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(FontAsset managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public static class ManagedToNative
            {
                public static FontAsset ConvertToManaged(IntPtr unmanaged) => Unsafe.As<FontAsset>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(FontAsset managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public struct Bidirectional
            {
                ManagedHandleMarshaller.Bidirectional marsh;
                public void FromManaged(FontAsset managed) => marsh.FromManaged(managed);
                public IntPtr ToUnmanaged() => marsh.ToUnmanaged();
                public void FromUnmanaged(IntPtr unmanaged) => marsh.FromUnmanaged(unmanaged);
                public FontAsset ToManaged() => Unsafe.As<FontAsset>(marsh.ToManaged());
                public void Free() => marsh.Free();
            }
            internal static FontAsset ConvertToManaged(IntPtr unmanaged) => Unsafe.As<FontAsset>(ManagedHandleMarshaller.ConvertToManaged(unmanaged));
            internal static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.Free(unmanaged);
            internal static FontAsset ToManaged(IntPtr managed) => Unsafe.As<FontAsset>(ManagedHandleMarshaller.ToManaged(managed));
            internal static IntPtr ToNative(FontAsset managed) => ManagedHandleMarshaller.ToNative(managed);
        #pragma warning restore 1591
        }

    }
}

