#pragma once
//*************************************************************************
// This is an auto-generated file - DO NOT edit
//*************************************************************************
#include "E:/EngineProject/SolarEngine/Src/Engine//Runtime/Render/2D/Font.h"
#include "Runtime/Core/Scripting/ManagedCLR/CLRUtils.h"
#include "Runtime/Core/Scripting/ScriptingObject.h"
#include "Runtime/Core/Scripting/Internal/InternalCalls.h"
#include "Runtime/Core/Scripting/ScriptingType.h"

//-------------------------------------------------------------------------
// Bindings
//-------------------------------------------------------------------------
//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Render/2D/Font.h
//-------------------------------------------------------------------------
#include "E:/EngineProject/SolarEngine/Src/Engine//Runtime/Render/2D/Font.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/BindingsInterop.h"
#include "Runtime/Core/Scripting/ManagedCLR/CLRUtils.h"
#include "Runtime/Core/Scripting/Scripting.h"
#include "Runtime/Core/Scripting/Binary/ManagedBinaryModule.h"
#include "Runtime/Core/Scripting/ScriptingObject.h"
#include "Runtime/Core/Scripting/Internal/InternalCalls.h"
#include "Runtime/Core/Scripting/ScriptingType.h"

namespace SE
{
class TextRangeInternal
{
public:
    static void InitRuntime()
    {
    }

    static void Ctor(void* ptr)
    {
        new(ptr)::SE::TextRange();
    }

    static void Dtor(void* ptr)
    {
        ((::SE::TextRange*)ptr)->~TextRange();
    }

    static void Copy(void* dst, void* src)
    {
        *(::SE::TextRange*)dst = *(::SE::TextRange*)src;
    }

    static CLRObject* Box(void* ptr)
    {
        return ::SE::CLRUtils::Box(*static_cast<::SE::TextRange*>(ptr), ::SE::TextRange::TypeInitializer.GetClass());
    }

    static void Unbox(void* ptr, CLRObject* managed)
    {
        *static_cast<::SE::TextRange*>(ptr) = ::SE::CLRUtils::Unbox<::SE::TextRange>(managed);
    }

    static void GetField(void* ptr, const String& name, Variant& value)
    {
        if (name == SE_TEXT("StartIndex"))
        {
            value = Variant(((::SE::TextRange*)ptr)->StartIndex);
        }
        else if (name == SE_TEXT("EndIndex"))
        {
            value = Variant(((::SE::TextRange*)ptr)->EndIndex);
        }
    }

    static void SetField(void* ptr, const String& name, const Variant& value)
    {
        if (name == SE_TEXT("StartIndex"))
        {
            ((::SE::TextRange*)ptr)->StartIndex = (int32)value;
        }
        else if (name == SE_TEXT("EndIndex"))
        {
            ((::SE::TextRange*)ptr)->EndIndex = (int32)value;
        }
    }
};

ScriptingTypeInitializer TextRange::TypeInitializer(
    (BinaryModule*)GetBinaryModuleSERuntime(),
    StringAnsiView("SE.TextRange", ARRAY_SIZE("SE.TextRange") - 1),
    sizeof(::SE::TextRange),
    &TextRangeInternal::InitRuntime,
    &TextRangeInternal::Ctor, &TextRangeInternal::Dtor, &TextRangeInternal::Copy,
    &TextRangeInternal::Box, &TextRangeInternal::Unbox, &TextRangeInternal::GetField, &TextRangeInternal::SetField,
    nullptr
);
}

namespace SE
{
class FontInternal
{
public:
#if defined(_MSC_VER)
    DLLEXPORT static void* GetAsset(::SE::Font* __obj)
#else
    static void* GetAsset(::SE::Font* __obj)
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(Font_GetAsset)
#endif
        if (__obj == nullptr)
        {
            return {};
        }
        return ScriptingObject::ToManaged(reinterpret_cast<ScriptingObject*>(__obj->GetAsset()));
    }
#if defined(_MSC_VER)
    DLLEXPORT static float GetSize(::SE::Font* __obj)
#else
    static float GetSize(::SE::Font* __obj)
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(Font_GetSize)
#endif
        if (__obj == nullptr)
        {
            return {};
        }
        return __obj->GetSize();
    }
#if defined(_MSC_VER)
    DLLEXPORT static int32 GetHeight(::SE::Font* __obj)
#else
    static int32 GetHeight(::SE::Font* __obj)
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(Font_GetHeight)
#endif
        if (__obj == nullptr)
        {
            return {};
        }
        return __obj->GetHeight();
    }
#if defined(_MSC_VER)
    DLLEXPORT static int32 GetAscender(::SE::Font* __obj)
#else
    static int32 GetAscender(::SE::Font* __obj)
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(Font_GetAscender)
#endif
        if (__obj == nullptr)
        {
            return {};
        }
        return __obj->GetAscender();
    }
#if defined(_MSC_VER)
    DLLEXPORT static int32 GetDescender(::SE::Font* __obj)
#else
    static int32 GetDescender(::SE::Font* __obj)
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(Font_GetDescender)
#endif
        if (__obj == nullptr)
        {
            return {};
        }
        return __obj->GetDescender();
    }
#if defined(_MSC_VER)
    DLLEXPORT static int32 GetLineGap(::SE::Font* __obj)
#else
    static int32 GetLineGap(::SE::Font* __obj)
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(Font_GetLineGap)
#endif
        if (__obj == nullptr)
        {
            return {};
        }
        return __obj->GetLineGap();
    }
#if defined(_MSC_VER)
    DLLEXPORT static void CacheText(::SE::Font* __obj, CLRString** text)
#else
    static void CacheText(::SE::Font* __obj, CLRString** text)
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(Font_CacheText)
#endif
        if (__obj == nullptr)
        {
            return;
        }
        __obj->CacheText(CLRUtils::ToString((CLRString*)*text));
    }
#if defined(_MSC_VER)
    DLLEXPORT static void Invalidate(::SE::Font* __obj)
#else
    static void Invalidate(::SE::Font* __obj)
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(Font_Invalidate)
#endif
        if (__obj == nullptr)
        {
            return;
        }
        __obj->Invalidate();
    }
#if defined(_MSC_VER)
    DLLEXPORT static ::SE::Float2 MeasureText(::SE::Font* __obj, CLRString** text, ::SE::TextLayoutOptions* layout)
#else
    static ::SE::Float2 MeasureText(::SE::Font* __obj, CLRString** text, ::SE::TextLayoutOptions* layout)
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(Font_MeasureText)
#endif
        if (__obj == nullptr)
        {
            return {};
        }
        return __obj->MeasureText(CLRUtils::ToString((CLRString*)*text), *layout);
    }
#if defined(_MSC_VER)
    DLLEXPORT static int32 HitTestText(::SE::Font* __obj, CLRString** text, ::SE::Float2* location, ::SE::TextLayoutOptions* layout)
#else
    static int32 HitTestText(::SE::Font* __obj, CLRString** text, ::SE::Float2* location, ::SE::TextLayoutOptions* layout)
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(Font_HitTestText)
#endif
        if (__obj == nullptr)
        {
            return {};
        }
        return __obj->HitTestText(CLRUtils::ToString((CLRString*)*text), *location, *layout);
    }
#if defined(_MSC_VER)
    DLLEXPORT static ::SE::Float2 GetCharPosition(::SE::Font* __obj, CLRString** text, int32 index, ::SE::TextLayoutOptions* layout)
#else
    static ::SE::Float2 GetCharPosition(::SE::Font* __obj, CLRString** text, int32 index, ::SE::TextLayoutOptions* layout)
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(Font_GetCharPosition)
#endif
        if (__obj == nullptr)
        {
            return {};
        }
        return __obj->GetCharPosition(CLRUtils::ToString((CLRString*)*text), index, *layout);
    }
    static void InitRuntime()
    {
    }
};

ScriptingTypeInitializer Font::TypeInitializer(
    (BinaryModule*)GetBinaryModuleSERuntime(),
    StringAnsiView("SE.Font", ARRAY_SIZE("SE.Font") - 1),
    sizeof(::SE::Font),
    &FontInternal::InitRuntime,
    &ScriptingType::DefaultSpawn, 
    &::SE::ScriptingObject::TypeInitializer,
    nullptr,
    nullptr
);

// Plain-C exports
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(void*) Font_GetAsset(void* __obj)
{
    return FontInternal::GetAsset((::SE::Font*)__obj);
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(float) Font_GetSize(void* __obj)
{
    return FontInternal::GetSize((::SE::Font*)__obj);
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(int32) Font_GetHeight(void* __obj)
{
    return FontInternal::GetHeight((::SE::Font*)__obj);
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(int32) Font_GetAscender(void* __obj)
{
    return FontInternal::GetAscender((::SE::Font*)__obj);
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(int32) Font_GetDescender(void* __obj)
{
    return FontInternal::GetDescender((::SE::Font*)__obj);
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(int32) Font_GetLineGap(void* __obj)
{
    return FontInternal::GetLineGap((::SE::Font*)__obj);
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(void) Font_CacheText(void* __obj, CLRString** text)
{
    FontInternal::CacheText((::SE::Font*)__obj, text);
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(void) Font_Invalidate(void* __obj)
{
    FontInternal::Invalidate((::SE::Font*)__obj);
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(::SE::Float2) Font_MeasureText(void* __obj, CLRString** text, ::SE::TextLayoutOptions* layout)
{
    return FontInternal::MeasureText((::SE::Font*)__obj, text, layout);
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(int32) Font_HitTestText(void* __obj, CLRString** text, ::SE::Float2* location, ::SE::TextLayoutOptions* layout)
{
    return FontInternal::HitTestText((::SE::Font*)__obj, text, location, layout);
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(::SE::Float2) Font_GetCharPosition(void* __obj, CLRString** text, int32 index, ::SE::TextLayoutOptions* layout)
{
    return FontInternal::GetCharPosition((::SE::Font*)__obj, text, index, layout);
}
#endif
}

