//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Render/2D/FontTextureAtlas.h
//-------------------------------------------------------------------------
#pragma warning disable CS0108
#pragma warning disable CS8603
#pragma warning disable CS8625
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using SE.Interop;

namespace SE
{
    /// <summary>
    /// &lt;summary&gt; Texture resource that contains an atlas of cached font glyphs. &lt;/summary&gt;
    /// </summary>
    [NativeMarshalling(typeof(FontTextureAtlasMarshaller))]
    public unsafe partial class FontTextureAtlas : SE.Texture
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FontTextureAtlas"/>.
        /// </summary>
        public FontTextureAtlas() : base()
        {
        }


        [CustomMarshaller(typeof(FontTextureAtlas), MarshalMode.ManagedToUnmanagedIn, typeof(FontTextureAtlasMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(FontTextureAtlas), MarshalMode.ElementIn, typeof(FontTextureAtlasMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(FontTextureAtlas), MarshalMode.ManagedToUnmanagedOut, typeof(FontTextureAtlasMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(FontTextureAtlas), MarshalMode.UnmanagedToManagedIn, typeof(FontTextureAtlasMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(FontTextureAtlas), MarshalMode.ElementOut, typeof(FontTextureAtlasMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(FontTextureAtlas), MarshalMode.ManagedToUnmanagedRef, typeof(FontTextureAtlasMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(FontTextureAtlas), MarshalMode.UnmanagedToManagedRef, typeof(FontTextureAtlasMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(FontTextureAtlas), MarshalMode.ElementRef, typeof(FontTextureAtlasMarshaller))]
        internal struct FontTextureAtlasMarshaller
        {
            #pragma warning disable 1591
            public static class NativeToManaged
            {
                public static FontTextureAtlas ConvertToManaged(IntPtr unmanaged) => Unsafe.As<FontTextureAtlas>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(FontTextureAtlas managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public static class ManagedToNative
            {
                public static FontTextureAtlas ConvertToManaged(IntPtr unmanaged) => Unsafe.As<FontTextureAtlas>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(FontTextureAtlas managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public struct Bidirectional
            {
                ManagedHandleMarshaller.Bidirectional marsh;
                public void FromManaged(FontTextureAtlas managed) => marsh.FromManaged(managed);
                public IntPtr ToUnmanaged() => marsh.ToUnmanaged();
                public void FromUnmanaged(IntPtr unmanaged) => marsh.FromUnmanaged(unmanaged);
                public FontTextureAtlas ToManaged() => Unsafe.As<FontTextureAtlas>(marsh.ToManaged());
                public void Free() => marsh.Free();
            }
            internal static FontTextureAtlas ConvertToManaged(IntPtr unmanaged) => Unsafe.As<FontTextureAtlas>(ManagedHandleMarshaller.ConvertToManaged(unmanaged));
            internal static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.Free(unmanaged);
            internal static FontTextureAtlas ToManaged(IntPtr managed) => Unsafe.As<FontTextureAtlas>(ManagedHandleMarshaller.ToManaged(managed));
            internal static IntPtr ToNative(FontTextureAtlas managed) => ManagedHandleMarshaller.ToNative(managed);
        #pragma warning restore 1591
        }

    }
}

