#pragma once
//*************************************************************************
// This is an auto-generated file - DO NOT edit
//*************************************************************************
#include "E:/EngineProject/SolarEngine/Src/Engine//Runtime/Graphics/Base/GPUBuffer.h"
#include "Runtime/Core/Scripting/ManagedCLR/CLRUtils.h"
#include "Runtime/Core/Scripting/ScriptingObject.h"
#include "Runtime/Core/Scripting/Internal/InternalCalls.h"
#include "Runtime/Core/Scripting/ScriptingType.h"

//-------------------------------------------------------------------------
// Bindings
//-------------------------------------------------------------------------
//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Graphics/Base/GPUBuffer.h
//-------------------------------------------------------------------------
#include "E:/EngineProject/SolarEngine/Src/Engine//Runtime/Graphics/Base/GPUBuffer.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/BindingsInterop.h"
#include "Runtime/Core/Scripting/ManagedCLR/CLRUtils.h"
#include "Runtime/Core/Scripting/Scripting.h"
#include "Runtime/Core/Scripting/Binary/ManagedBinaryModule.h"
#include "Runtime/Core/Scripting/ScriptingObject.h"
#include "Runtime/Core/Scripting/Internal/InternalCalls.h"
#include "Runtime/Core/Scripting/ScriptingType.h"

namespace SE
{
class GPUBufferViewInternal
{
public:
    static void InitRuntime()
    {
    }
};

ScriptingTypeInitializer GPUBufferView::TypeInitializer(
    (BinaryModule*)GetBinaryModuleSERuntime(),
    StringAnsiView("SE.GPUBufferView", ARRAY_SIZE("SE.GPUBufferView") - 1),
    sizeof(::SE::GPUBufferView),
    &GPUBufferViewInternal::InitRuntime,
    &ScriptingType::DefaultSpawn, 
    &::SE::GPUResourceView::TypeInitializer,
    nullptr,
    nullptr
);
}

namespace SE
{
class GPUBufferInternal
{
public:
    static void InitRuntime()
    {
    }
};

ScriptingTypeInitializer GPUBuffer::TypeInitializer(
    (BinaryModule*)GetBinaryModuleSERuntime(),
    StringAnsiView("SE.GPUBuffer", ARRAY_SIZE("SE.GPUBuffer") - 1),
    sizeof(::SE::GPUBuffer),
    &GPUBufferInternal::InitRuntime,
    (ScriptingType::SpawnHandler)&::SE::GPUBuffer::Spawn,
    &::SE::GPUResource::TypeInitializer,
    nullptr,
    nullptr
);
}

