//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Graphics/Base/GPUResource.h
//-------------------------------------------------------------------------
#pragma warning disable CS0108
#pragma warning disable CS8603
#pragma warning disable CS8625
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using SE.Interop;

namespace SE
{
    [NativeMarshalling(typeof(GPUResourceViewMarshaller))]
    public unsafe abstract partial class GPUResourceView : SE.Object
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GPUResourceView"/>.
        /// </summary>
        protected GPUResourceView() : base()
        {
        }


        [CustomMarshaller(typeof(GPUResourceView), MarshalMode.ManagedToUnmanagedIn, typeof(GPUResourceViewMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(GPUResourceView), MarshalMode.ElementIn, typeof(GPUResourceViewMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(GPUResourceView), MarshalMode.ManagedToUnmanagedOut, typeof(GPUResourceViewMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(GPUResourceView), MarshalMode.UnmanagedToManagedIn, typeof(GPUResourceViewMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(GPUResourceView), MarshalMode.ElementOut, typeof(GPUResourceViewMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(GPUResourceView), MarshalMode.ManagedToUnmanagedRef, typeof(GPUResourceViewMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(GPUResourceView), MarshalMode.UnmanagedToManagedRef, typeof(GPUResourceViewMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(GPUResourceView), MarshalMode.ElementRef, typeof(GPUResourceViewMarshaller))]
        internal struct GPUResourceViewMarshaller
        {
            #pragma warning disable 1591
            public static class NativeToManaged
            {
                public static GPUResourceView ConvertToManaged(IntPtr unmanaged) => Unsafe.As<GPUResourceView>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(GPUResourceView managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public static class ManagedToNative
            {
                public static GPUResourceView ConvertToManaged(IntPtr unmanaged) => Unsafe.As<GPUResourceView>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(GPUResourceView managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public struct Bidirectional
            {
                ManagedHandleMarshaller.Bidirectional marsh;
                public void FromManaged(GPUResourceView managed) => marsh.FromManaged(managed);
                public IntPtr ToUnmanaged() => marsh.ToUnmanaged();
                public void FromUnmanaged(IntPtr unmanaged) => marsh.FromUnmanaged(unmanaged);
                public GPUResourceView ToManaged() => Unsafe.As<GPUResourceView>(marsh.ToManaged());
                public void Free() => marsh.Free();
            }
            internal static GPUResourceView ConvertToManaged(IntPtr unmanaged) => Unsafe.As<GPUResourceView>(ManagedHandleMarshaller.ConvertToManaged(unmanaged));
            internal static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.Free(unmanaged);
            internal static GPUResourceView ToManaged(IntPtr managed) => Unsafe.As<GPUResourceView>(ManagedHandleMarshaller.ToManaged(managed));
            internal static IntPtr ToNative(GPUResourceView managed) => ManagedHandleMarshaller.ToNative(managed);
        #pragma warning restore 1591
        }

    }
}

namespace SE
{
    [NativeMarshalling(typeof(GPUResourceMarshaller))]
    public unsafe abstract partial class GPUResource : SE.Object
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GPUResource"/>.
        /// </summary>
        protected GPUResource() : base()
        {
        }


        [CustomMarshaller(typeof(GPUResource), MarshalMode.ManagedToUnmanagedIn, typeof(GPUResourceMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(GPUResource), MarshalMode.ElementIn, typeof(GPUResourceMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(GPUResource), MarshalMode.ManagedToUnmanagedOut, typeof(GPUResourceMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(GPUResource), MarshalMode.UnmanagedToManagedIn, typeof(GPUResourceMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(GPUResource), MarshalMode.ElementOut, typeof(GPUResourceMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(GPUResource), MarshalMode.ManagedToUnmanagedRef, typeof(GPUResourceMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(GPUResource), MarshalMode.UnmanagedToManagedRef, typeof(GPUResourceMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(GPUResource), MarshalMode.ElementRef, typeof(GPUResourceMarshaller))]
        internal struct GPUResourceMarshaller
        {
            #pragma warning disable 1591
            public static class NativeToManaged
            {
                public static GPUResource ConvertToManaged(IntPtr unmanaged) => Unsafe.As<GPUResource>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(GPUResource managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public static class ManagedToNative
            {
                public static GPUResource ConvertToManaged(IntPtr unmanaged) => Unsafe.As<GPUResource>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(GPUResource managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public struct Bidirectional
            {
                ManagedHandleMarshaller.Bidirectional marsh;
                public void FromManaged(GPUResource managed) => marsh.FromManaged(managed);
                public IntPtr ToUnmanaged() => marsh.ToUnmanaged();
                public void FromUnmanaged(IntPtr unmanaged) => marsh.FromUnmanaged(unmanaged);
                public GPUResource ToManaged() => Unsafe.As<GPUResource>(marsh.ToManaged());
                public void Free() => marsh.Free();
            }
            internal static GPUResource ConvertToManaged(IntPtr unmanaged) => Unsafe.As<GPUResource>(ManagedHandleMarshaller.ConvertToManaged(unmanaged));
            internal static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.Free(unmanaged);
            internal static GPUResource ToManaged(IntPtr managed) => Unsafe.As<GPUResource>(ManagedHandleMarshaller.ToManaged(managed));
            internal static IntPtr ToNative(GPUResource managed) => ManagedHandleMarshaller.ToNative(managed);
        #pragma warning restore 1591
        }

    }
}

