//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Graphics/Textures/GPUSampler.h
//-------------------------------------------------------------------------
#pragma warning disable CS0108
#pragma warning disable CS8603
#pragma warning disable CS8625
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using SE.Interop;

namespace SE
{
    /// <summary>
    /// &lt;summary&gt; GPU texture sampler object. &lt;/summary&gt; &lt;seealso cref="GPUResource" /&gt;
    /// </summary>
    [NativeMarshalling(typeof(GPUSamplerMarshaller))]
    public unsafe sealed partial class GPUSampler : SE.GPUResource
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GPUSampler"/>.
        /// </summary>
        public GPUSampler() : base()
        {
        }


        [CustomMarshaller(typeof(GPUSampler), MarshalMode.ManagedToUnmanagedIn, typeof(GPUSamplerMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(GPUSampler), MarshalMode.ElementIn, typeof(GPUSamplerMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(GPUSampler), MarshalMode.ManagedToUnmanagedOut, typeof(GPUSamplerMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(GPUSampler), MarshalMode.UnmanagedToManagedIn, typeof(GPUSamplerMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(GPUSampler), MarshalMode.ElementOut, typeof(GPUSamplerMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(GPUSampler), MarshalMode.ManagedToUnmanagedRef, typeof(GPUSamplerMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(GPUSampler), MarshalMode.UnmanagedToManagedRef, typeof(GPUSamplerMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(GPUSampler), MarshalMode.ElementRef, typeof(GPUSamplerMarshaller))]
        internal struct GPUSamplerMarshaller
        {
            #pragma warning disable 1591
            public static class NativeToManaged
            {
                public static GPUSampler ConvertToManaged(IntPtr unmanaged) => Unsafe.As<GPUSampler>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(GPUSampler managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public static class ManagedToNative
            {
                public static GPUSampler ConvertToManaged(IntPtr unmanaged) => Unsafe.As<GPUSampler>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(GPUSampler managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public struct Bidirectional
            {
                ManagedHandleMarshaller.Bidirectional marsh;
                public void FromManaged(GPUSampler managed) => marsh.FromManaged(managed);
                public IntPtr ToUnmanaged() => marsh.ToUnmanaged();
                public void FromUnmanaged(IntPtr unmanaged) => marsh.FromUnmanaged(unmanaged);
                public GPUSampler ToManaged() => Unsafe.As<GPUSampler>(marsh.ToManaged());
                public void Free() => marsh.Free();
            }
            internal static GPUSampler ConvertToManaged(IntPtr unmanaged) => Unsafe.As<GPUSampler>(ManagedHandleMarshaller.ConvertToManaged(unmanaged));
            internal static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.Free(unmanaged);
            internal static GPUSampler ToManaged(IntPtr managed) => Unsafe.As<GPUSampler>(ManagedHandleMarshaller.ToManaged(managed));
            internal static IntPtr ToNative(GPUSampler managed) => ManagedHandleMarshaller.ToNative(managed);
        #pragma warning restore 1591
        }

    }
}

