//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Graphics/Shaders/GPUShader.h
//-------------------------------------------------------------------------
#pragma warning disable CS0108
#pragma warning disable CS8603
#pragma warning disable CS8625
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using SE.Interop;

namespace SE
{
    [NativeMarshalling(typeof(GPUShaderMarshaller))]
    public unsafe sealed partial class GPUShader : SE.GPUResource
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GPUShader"/>.
        /// </summary>
        public GPUShader() : base()
        {
        }


        [CustomMarshaller(typeof(GPUShader), MarshalMode.ManagedToUnmanagedIn, typeof(GPUShaderMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(GPUShader), MarshalMode.ElementIn, typeof(GPUShaderMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(GPUShader), MarshalMode.ManagedToUnmanagedOut, typeof(GPUShaderMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(GPUShader), MarshalMode.UnmanagedToManagedIn, typeof(GPUShaderMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(GPUShader), MarshalMode.ElementOut, typeof(GPUShaderMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(GPUShader), MarshalMode.ManagedToUnmanagedRef, typeof(GPUShaderMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(GPUShader), MarshalMode.UnmanagedToManagedRef, typeof(GPUShaderMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(GPUShader), MarshalMode.ElementRef, typeof(GPUShaderMarshaller))]
        internal struct GPUShaderMarshaller
        {
            #pragma warning disable 1591
            public static class NativeToManaged
            {
                public static GPUShader ConvertToManaged(IntPtr unmanaged) => Unsafe.As<GPUShader>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(GPUShader managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public static class ManagedToNative
            {
                public static GPUShader ConvertToManaged(IntPtr unmanaged) => Unsafe.As<GPUShader>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(GPUShader managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public struct Bidirectional
            {
                ManagedHandleMarshaller.Bidirectional marsh;
                public void FromManaged(GPUShader managed) => marsh.FromManaged(managed);
                public IntPtr ToUnmanaged() => marsh.ToUnmanaged();
                public void FromUnmanaged(IntPtr unmanaged) => marsh.FromUnmanaged(unmanaged);
                public GPUShader ToManaged() => Unsafe.As<GPUShader>(marsh.ToManaged());
                public void Free() => marsh.Free();
            }
            internal static GPUShader ConvertToManaged(IntPtr unmanaged) => Unsafe.As<GPUShader>(ManagedHandleMarshaller.ConvertToManaged(unmanaged));
            internal static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.Free(unmanaged);
            internal static GPUShader ToManaged(IntPtr managed) => Unsafe.As<GPUShader>(ManagedHandleMarshaller.ToManaged(managed));
            internal static IntPtr ToNative(GPUShader managed) => ManagedHandleMarshaller.ToNative(managed);
        #pragma warning restore 1591
        }

    }
}

