//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Resource/JsonAsset.h
//-------------------------------------------------------------------------
#pragma warning disable CS0108
#pragma warning disable CS8603
#pragma warning disable CS8625
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using SE.Interop;

namespace SE
{
    /// <summary>
    /// &lt;summary&gt; Base class for all Json-format assets. &lt;/summary&gt; &lt;seealso cref="Asset" /&gt;
    /// </summary>
    [NativeMarshalling(typeof(JsonAssetBaseMarshaller))]
    public unsafe abstract partial class JsonAssetBase : SE.Asset
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JsonAssetBase"/>.
        /// </summary>
        protected JsonAssetBase() : base()
        {
        }


        [CustomMarshaller(typeof(JsonAssetBase), MarshalMode.ManagedToUnmanagedIn, typeof(JsonAssetBaseMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(JsonAssetBase), MarshalMode.ElementIn, typeof(JsonAssetBaseMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(JsonAssetBase), MarshalMode.ManagedToUnmanagedOut, typeof(JsonAssetBaseMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(JsonAssetBase), MarshalMode.UnmanagedToManagedIn, typeof(JsonAssetBaseMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(JsonAssetBase), MarshalMode.ElementOut, typeof(JsonAssetBaseMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(JsonAssetBase), MarshalMode.ManagedToUnmanagedRef, typeof(JsonAssetBaseMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(JsonAssetBase), MarshalMode.UnmanagedToManagedRef, typeof(JsonAssetBaseMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(JsonAssetBase), MarshalMode.ElementRef, typeof(JsonAssetBaseMarshaller))]
        internal struct JsonAssetBaseMarshaller
        {
            #pragma warning disable 1591
            public static class NativeToManaged
            {
                public static JsonAssetBase ConvertToManaged(IntPtr unmanaged) => Unsafe.As<JsonAssetBase>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(JsonAssetBase managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public static class ManagedToNative
            {
                public static JsonAssetBase ConvertToManaged(IntPtr unmanaged) => Unsafe.As<JsonAssetBase>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(JsonAssetBase managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public struct Bidirectional
            {
                ManagedHandleMarshaller.Bidirectional marsh;
                public void FromManaged(JsonAssetBase managed) => marsh.FromManaged(managed);
                public IntPtr ToUnmanaged() => marsh.ToUnmanaged();
                public void FromUnmanaged(IntPtr unmanaged) => marsh.FromUnmanaged(unmanaged);
                public JsonAssetBase ToManaged() => Unsafe.As<JsonAssetBase>(marsh.ToManaged());
                public void Free() => marsh.Free();
            }
            internal static JsonAssetBase ConvertToManaged(IntPtr unmanaged) => Unsafe.As<JsonAssetBase>(ManagedHandleMarshaller.ConvertToManaged(unmanaged));
            internal static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.Free(unmanaged);
            internal static JsonAssetBase ToManaged(IntPtr managed) => Unsafe.As<JsonAssetBase>(ManagedHandleMarshaller.ToManaged(managed));
            internal static IntPtr ToNative(JsonAssetBase managed) => ManagedHandleMarshaller.ToNative(managed);
        #pragma warning restore 1591
        }

    }
}

namespace SE
{
    /// <summary>
    /// &lt;summary&gt; Generic type of Json-format asset. It provides the managed representation of this resource data so it can be accessed via C# API. &lt;/summary&gt; &lt;seealso cref="JsonAssetBase" /&gt;
    /// </summary>
    [NativeMarshalling(typeof(JsonAssetMarshaller))]
    public unsafe partial class JsonAsset : SE.JsonAssetBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JsonAsset"/>.
        /// </summary>
        public JsonAsset() : base()
        {
        }


        [CustomMarshaller(typeof(JsonAsset), MarshalMode.ManagedToUnmanagedIn, typeof(JsonAssetMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(JsonAsset), MarshalMode.ElementIn, typeof(JsonAssetMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(JsonAsset), MarshalMode.ManagedToUnmanagedOut, typeof(JsonAssetMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(JsonAsset), MarshalMode.UnmanagedToManagedIn, typeof(JsonAssetMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(JsonAsset), MarshalMode.ElementOut, typeof(JsonAssetMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(JsonAsset), MarshalMode.ManagedToUnmanagedRef, typeof(JsonAssetMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(JsonAsset), MarshalMode.UnmanagedToManagedRef, typeof(JsonAssetMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(JsonAsset), MarshalMode.ElementRef, typeof(JsonAssetMarshaller))]
        internal struct JsonAssetMarshaller
        {
            #pragma warning disable 1591
            public static class NativeToManaged
            {
                public static JsonAsset ConvertToManaged(IntPtr unmanaged) => Unsafe.As<JsonAsset>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(JsonAsset managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public static class ManagedToNative
            {
                public static JsonAsset ConvertToManaged(IntPtr unmanaged) => Unsafe.As<JsonAsset>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(JsonAsset managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public struct Bidirectional
            {
                ManagedHandleMarshaller.Bidirectional marsh;
                public void FromManaged(JsonAsset managed) => marsh.FromManaged(managed);
                public IntPtr ToUnmanaged() => marsh.ToUnmanaged();
                public void FromUnmanaged(IntPtr unmanaged) => marsh.FromUnmanaged(unmanaged);
                public JsonAsset ToManaged() => Unsafe.As<JsonAsset>(marsh.ToManaged());
                public void Free() => marsh.Free();
            }
            internal static JsonAsset ConvertToManaged(IntPtr unmanaged) => Unsafe.As<JsonAsset>(ManagedHandleMarshaller.ConvertToManaged(unmanaged));
            internal static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.Free(unmanaged);
            internal static JsonAsset ToManaged(IntPtr managed) => Unsafe.As<JsonAsset>(ManagedHandleMarshaller.ToManaged(managed));
            internal static IntPtr ToNative(JsonAsset managed) => ManagedHandleMarshaller.ToNative(managed);
        #pragma warning restore 1591
        }

    }
}

