//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Input/KeyboardKeys.h
//-------------------------------------------------------------------------
#pragma warning disable CS0108
#pragma warning disable CS8603
#pragma warning disable CS8625
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using SE.Interop;

namespace SE
{
    /// <summary>
    /// &lt;summary&gt; Enumeration for key codes. &lt;/summary&gt;
    /// </summary>
    public enum KeyboardKeys : int
    {
        /// <summary>
        /// &lt;summary&gt; The 'none' key &lt;/summary&gt;
        /// </summary>
        None = 0,
        /// <summary>
        /// &lt;summary&gt; BACKSPACE key &lt;/summary&gt;
        /// </summary>
        Backspace = 8,
        /// <summary>
        /// &lt;summary&gt; TAB key &lt;/summary&gt;
        /// </summary>
        Tab = 9,
        /// <summary>
        /// &lt;summary&gt; CLEAR key &lt;/summary&gt;
        /// </summary>
        Clear = 12,
        /// <summary>
        /// &lt;summary&gt; ENTER key &lt;/summary&gt;
        /// </summary>
        Return = 13,
        /// <summary>
        /// &lt;summary&gt; Any SHIFT key, right or left &lt;/summary&gt;
        /// </summary>
        Shift = 16,
        /// <summary>
        /// &lt;summary&gt; Any CTRL key, right or left &lt;/summary&gt;
        /// </summary>
        Control = 17,
        /// <summary>
        /// &lt;summary&gt; Any ALT key, right or left &lt;/summary&gt;
        /// </summary>
        Alt = 18,
        /// <summary>
        /// &lt;summary&gt; PAUSE key &lt;/summary&gt;
        /// </summary>
        Pause = 19,
        /// <summary>
        /// &lt;summary&gt; CAPS LOCK key &lt;/summary&gt;
        /// </summary>
        Capital = 20,
        /// <summary>
        /// &lt;summary&gt; IME Kana mode &lt;/summary&gt;
        /// </summary>
        Kana = 21,
        /// <summary>
        /// &lt;summary&gt; IME Hangul mode &lt;/summary&gt;
        /// </summary>
        Hangul = 21,
        /// <summary>
        /// &lt;summary&gt; IME Junja mode &lt;/summary&gt;
        /// </summary>
        Junja = 23,
        /// <summary>
        /// &lt;summary&gt; IME final mode &lt;/summary&gt;
        /// </summary>
        Final = 24,
        /// <summary>
        /// &lt;summary&gt; IME Hanja mode &lt;/summary&gt;
        /// </summary>
        Hanja = 25,
        /// <summary>
        /// &lt;summary&gt; IME Kanji mode &lt;/summary&gt;
        /// </summary>
        Kanji = 25,
        /// <summary>
        /// &lt;summary&gt; ESC key &lt;/summary&gt;
        /// </summary>
        Escape = 27,
        /// <summary>
        /// &lt;summary&gt; IME convert &lt;/summary&gt;
        /// </summary>
        Convert = 28,
        /// <summary>
        /// &lt;summary&gt; IME nonconvert &lt;/summary&gt;
        /// </summary>
        Nonconvert = 29,
        /// <summary>
        /// &lt;summary&gt; IME accept &lt;/summary&gt;
        /// </summary>
        Accept = 30,
        /// <summary>
        /// &lt;summary&gt; IME mode change request &lt;/summary&gt;
        /// </summary>
        Modechange = 31,
        /// <summary>
        /// &lt;summary&gt; SPACEBAR key &lt;/summary&gt;
        /// </summary>
        Spacebar = 32,
        /// <summary>
        /// &lt;summary&gt; PAGE UP key &lt;/summary&gt;
        /// </summary>
        PageUp = 33,
        /// <summary>
        /// &lt;summary&gt; PAGE DOWN key &lt;/summary&gt;
        /// </summary>
        PageDown = 34,
        /// <summary>
        /// &lt;summary&gt; END key &lt;/summary&gt;
        /// </summary>
        End = 35,
        /// <summary>
        /// &lt;summary&gt; HOME key &lt;/summary&gt;
        /// </summary>
        Home = 36,
        /// <summary>
        /// &lt;summary&gt; LEFT ARROW key &lt;/summary&gt;
        /// </summary>
        ArrowLeft = 37,
        /// <summary>
        /// &lt;summary&gt; UP ARROW key &lt;/summary&gt;
        /// </summary>
        ArrowUp = 38,
        /// <summary>
        /// &lt;summary&gt; RIGHT ARROW key &lt;/summary&gt;
        /// </summary>
        ArrowRight = 39,
        /// <summary>
        /// &lt;summary&gt; DOWN ARROW key &lt;/summary&gt;
        /// </summary>
        ArrowDown = 40,
        /// <summary>
        /// &lt;summary&gt; SELECT key &lt;/summary&gt;
        /// </summary>
        Select = 41,
        /// <summary>
        /// &lt;summary&gt; PRINT key &lt;/summary&gt;
        /// </summary>
        Print = 42,
        /// <summary>
        /// &lt;summary&gt; EXECUTE key &lt;/summary&gt;
        /// </summary>
        Execute = 43,
        /// <summary>
        /// &lt;summary&gt; PRINT SCREEN key &lt;/summary&gt;
        /// </summary>
        PrintScreen = 44,
        /// <summary>
        /// &lt;summary&gt; INSERT key &lt;/summary&gt;
        /// </summary>
        Insert = 45,
        /// <summary>
        /// &lt;summary&gt; DELETE key &lt;/summary&gt;
        /// </summary>
        Delete = 46,
        /// <summary>
        /// &lt;summary&gt; HELP key &lt;/summary&gt;
        /// </summary>
        Help = 47,
        /// <summary>
        /// &lt;summary&gt; The '0' key on the top of the alphanumeric keyboard. &lt;/summary&gt;
        /// </summary>
        Alpha0 = 48,
        /// <summary>
        /// &lt;summary&gt; The '1' key on the top of the alphanumeric keyboard. &lt;/summary&gt;
        /// </summary>
        Alpha1 = 49,
        /// <summary>
        /// &lt;summary&gt; The '2' key on the top of the alphanumeric keyboard. &lt;/summary&gt;
        /// </summary>
        Alpha2 = 50,
        /// <summary>
        /// &lt;summary&gt; The '3' key on the top of the alphanumeric keyboard. &lt;/summary&gt;
        /// </summary>
        Alpha3 = 51,
        /// <summary>
        /// &lt;summary&gt; The '4' key on the top of the alphanumeric keyboard. &lt;/summary&gt;
        /// </summary>
        Alpha4 = 52,
        /// <summary>
        /// &lt;summary&gt; The '5' key on the top of the alphanumeric keyboard. &lt;/summary&gt;
        /// </summary>
        Alpha5 = 53,
        /// <summary>
        /// &lt;summary&gt; The '6' key on the top of the alphanumeric keyboard. &lt;/summary&gt;
        /// </summary>
        Alpha6 = 54,
        /// <summary>
        /// &lt;summary&gt; The '7' key on the top of the alphanumeric keyboard. &lt;/summary&gt;
        /// </summary>
        Alpha7 = 55,
        /// <summary>
        /// &lt;summary&gt; The '8' key on the top of the alphanumeric keyboard. &lt;/summary&gt;
        /// </summary>
        Alpha8 = 56,
        /// <summary>
        /// &lt;summary&gt; The '9' key on the top of the alphanumeric keyboard. &lt;/summary&gt;
        /// </summary>
        Alpha9 = 57,
        /// <summary>
        /// &lt;summary&gt; A key &lt;/summary&gt;
        /// </summary>
        A = 65,
        /// <summary>
        /// &lt;summary&gt; B key &lt;/summary&gt;
        /// </summary>
        B = 66,
        /// <summary>
        /// &lt;summary&gt; C key &lt;/summary&gt;
        /// </summary>
        C = 67,
        /// <summary>
        /// &lt;summary&gt; D key &lt;/summary&gt;
        /// </summary>
        D = 68,
        /// <summary>
        /// &lt;summary&gt; E key &lt;/summary&gt;
        /// </summary>
        E = 69,
        /// <summary>
        /// &lt;summary&gt; F key &lt;/summary&gt;
        /// </summary>
        F = 70,
        /// <summary>
        /// &lt;summary&gt; G key &lt;/summary&gt;
        /// </summary>
        G = 71,
        /// <summary>
        /// &lt;summary&gt; H key &lt;/summary&gt;
        /// </summary>
        H = 72,
        /// <summary>
        /// &lt;summary&gt; I key &lt;/summary&gt;
        /// </summary>
        I = 73,
        /// <summary>
        /// &lt;summary&gt; J key &lt;/summary&gt;
        /// </summary>
        J = 74,
        /// <summary>
        /// &lt;summary&gt; K key &lt;/summary&gt;
        /// </summary>
        K = 75,
        /// <summary>
        /// &lt;summary&gt; L key &lt;/summary&gt;
        /// </summary>
        L = 76,
        /// <summary>
        /// &lt;summary&gt; M key &lt;/summary&gt;
        /// </summary>
        M = 77,
        /// <summary>
        /// &lt;summary&gt; N key &lt;/summary&gt;
        /// </summary>
        N = 78,
        /// <summary>
        /// &lt;summary&gt; O key &lt;/summary&gt;
        /// </summary>
        O = 79,
        /// <summary>
        /// &lt;summary&gt; P key &lt;/summary&gt;
        /// </summary>
        P = 80,
        /// <summary>
        /// &lt;summary&gt; Q key &lt;/summary&gt;
        /// </summary>
        Q = 81,
        /// <summary>
        /// &lt;summary&gt; R key &lt;/summary&gt;
        /// </summary>
        R = 82,
        /// <summary>
        /// &lt;summary&gt; S key &lt;/summary&gt;
        /// </summary>
        S = 83,
        /// <summary>
        /// &lt;summary&gt; T key &lt;/summary&gt;
        /// </summary>
        T = 84,
        /// <summary>
        /// &lt;summary&gt; U key &lt;/summary&gt;
        /// </summary>
        U = 85,
        /// <summary>
        /// &lt;summary&gt; V key &lt;/summary&gt;
        /// </summary>
        V = 86,
        /// <summary>
        /// &lt;summary&gt; W key &lt;/summary&gt;
        /// </summary>
        W = 87,
        /// <summary>
        /// &lt;summary&gt; X key &lt;/summary&gt;
        /// </summary>
        X = 88,
        /// <summary>
        /// &lt;summary&gt; Y key &lt;/summary&gt;
        /// </summary>
        Y = 89,
        /// <summary>
        /// &lt;summary&gt; Z key &lt;/summary&gt;
        /// </summary>
        Z = 90,
        /// <summary>
        /// &lt;summary&gt; Left Windows key (Natural keyboard) &lt;/summary&gt;
        /// </summary>
        LeftWindows = 91,
        /// <summary>
        /// &lt;summary&gt; Right Windows key (Natural keyboard) &lt;/summary&gt;
        /// </summary>
        RightWindows = 92,
        /// <summary>
        /// &lt;summary&gt; Applications key (Natural keyboard) &lt;/summary&gt;
        /// </summary>
        Applications = 93,
        /// <summary>
        /// &lt;summary&gt; Computer Sleep key &lt;/summary&gt;
        /// </summary>
        Sleep = 95,
        /// <summary>
        /// &lt;summary&gt; Numeric keypad 0 key &lt;/summary&gt;
        /// </summary>
        Numpad0 = 96,
        /// <summary>
        /// &lt;summary&gt; Numeric keypad 1 key &lt;/summary&gt;
        /// </summary>
        Numpad1 = 97,
        /// <summary>
        /// &lt;summary&gt; Numeric keypad 2 key &lt;/summary&gt;
        /// </summary>
        Numpad2 = 98,
        /// <summary>
        /// &lt;summary&gt; Numeric keypad 3 key &lt;/summary&gt;
        /// </summary>
        Numpad3 = 99,
        /// <summary>
        /// &lt;summary&gt; Numeric keypad 4 key &lt;/summary&gt;
        /// </summary>
        Numpad4 = 100,
        /// <summary>
        /// &lt;summary&gt; Numeric keypad 5 key &lt;/summary&gt;
        /// </summary>
        Numpad5 = 101,
        /// <summary>
        /// &lt;summary&gt; Numeric keypad 6 key &lt;/summary&gt;
        /// </summary>
        Numpad6 = 102,
        /// <summary>
        /// &lt;summary&gt; Numeric keypad 7 key &lt;/summary&gt;
        /// </summary>
        Numpad7 = 103,
        /// <summary>
        /// &lt;summary&gt; Numeric keypad 8 key &lt;/summary&gt;
        /// </summary>
        Numpad8 = 104,
        /// <summary>
        /// &lt;summary&gt; Numeric keypad 9 key &lt;/summary&gt;
        /// </summary>
        Numpad9 = 105,
        /// <summary>
        /// &lt;summary&gt; Numeric keypad Multiply key '*' &lt;/summary&gt;
        /// </summary>
        NumpadMultiply = 106,
        /// <summary>
        /// &lt;summary&gt; Numeric keypad Add key '+' &lt;/summary&gt;
        /// </summary>
        NumpadAdd = 107,
        /// <summary>
        /// &lt;summary&gt; Numeric Separator key &lt;/summary&gt;
        /// </summary>
        NumpadSeparator = 108,
        /// <summary>
        /// &lt;summary&gt; Numeric keypad Subtract key '-' &lt;/summary&gt;
        /// </summary>
        NumpadSubtract = 109,
        /// <summary>
        /// &lt;summary&gt; Numeric keypad Decimal key ',' &lt;/summary&gt;
        /// </summary>
        NumpadDecimal = 110,
        /// <summary>
        /// &lt;summary&gt; Numeric keypad Divide key '/' &lt;/summary&gt;
        /// </summary>
        NumpadDivide = 111,
        /// <summary>
        /// &lt;summary&gt; F1 function key &lt;/summary&gt;
        /// </summary>
        F1 = 112,
        /// <summary>
        /// &lt;summary&gt; F2 function key &lt;/summary&gt;
        /// </summary>
        F2 = 113,
        /// <summary>
        /// &lt;summary&gt; F3 function key &lt;/summary&gt;
        /// </summary>
        F3 = 114,
        /// <summary>
        /// &lt;summary&gt; F4 function key &lt;/summary&gt;
        /// </summary>
        F4 = 115,
        /// <summary>
        /// &lt;summary&gt; F5 function key &lt;/summary&gt;
        /// </summary>
        F5 = 116,
        /// <summary>
        /// &lt;summary&gt; F6 function key &lt;/summary&gt;
        /// </summary>
        F6 = 117,
        /// <summary>
        /// &lt;summary&gt; F7 function key &lt;/summary&gt;
        /// </summary>
        F7 = 118,
        /// <summary>
        /// &lt;summary&gt; F8 function key &lt;/summary&gt;
        /// </summary>
        F8 = 119,
        /// <summary>
        /// &lt;summary&gt; F9 function key &lt;/summary&gt;
        /// </summary>
        F9 = 120,
        /// <summary>
        /// &lt;summary&gt; F10 function key &lt;/summary&gt;
        /// </summary>
        F10 = 121,
        /// <summary>
        /// &lt;summary&gt; F11 function key &lt;/summary&gt;
        /// </summary>
        F11 = 122,
        /// <summary>
        /// &lt;summary&gt; F12 function key &lt;/summary&gt;
        /// </summary>
        F12 = 123,
        /// <summary>
        /// &lt;summary&gt; F13 function key &lt;/summary&gt;
        /// </summary>
        F13 = 124,
        /// <summary>
        /// &lt;summary&gt; F14 function key &lt;/summary&gt;
        /// </summary>
        F14 = 125,
        /// <summary>
        /// &lt;summary&gt; F15 function key &lt;/summary&gt;
        /// </summary>
        F15 = 126,
        /// <summary>
        /// &lt;summary&gt; F16 function key &lt;/summary&gt;
        /// </summary>
        F16 = 127,
        /// <summary>
        /// &lt;summary&gt; F17 function key &lt;/summary&gt;
        /// </summary>
        F17 = 128,
        /// <summary>
        /// &lt;summary&gt; F18 function key &lt;/summary&gt;
        /// </summary>
        F18 = 129,
        /// <summary>
        /// &lt;summary&gt; F19 function key &lt;/summary&gt;
        /// </summary>
        F19 = 130,
        /// <summary>
        /// &lt;summary&gt; F20 function key &lt;/summary&gt;
        /// </summary>
        F20 = 131,
        /// <summary>
        /// &lt;summary&gt; F21 function key &lt;/summary&gt;
        /// </summary>
        F21 = 132,
        /// <summary>
        /// &lt;summary&gt; F22 function key &lt;/summary&gt;
        /// </summary>
        F22 = 133,
        /// <summary>
        /// &lt;summary&gt; F23 function key &lt;/summary&gt;
        /// </summary>
        F23 = 134,
        /// <summary>
        /// &lt;summary&gt; F24 function key &lt;/summary&gt;
        /// </summary>
        F24 = 135,
        /// <summary>
        /// &lt;summary&gt; Numeric keypad NUM LOCK key &lt;/summary&gt;
        /// </summary>
        Numlock = 144,
        /// <summary>
        /// &lt;summary&gt; SCROLL LOCK key &lt;/summary&gt;
        /// </summary>
        Scroll = 145,
        /// <summary>
        /// &lt;summary&gt; Left MENU key &lt;/summary&gt;
        /// </summary>
        LeftMenu = 164,
        /// <summary>
        /// &lt;summary&gt; Right MENU key &lt;/summary&gt;
        /// </summary>
        RightMenu = 165,
        /// <summary>
        /// &lt;summary&gt; Browser Back key &lt;/summary&gt;
        /// </summary>
        BrowserBack = 166,
        /// <summary>
        /// &lt;summary&gt; Browser Forward key &lt;/summary&gt;
        /// </summary>
        BrowserForward = 167,
        /// <summary>
        /// &lt;summary&gt; Browser Refresh key &lt;/summary&gt;
        /// </summary>
        BrowserRefresh = 168,
        /// <summary>
        /// &lt;summary&gt; Browser Stop key &lt;/summary&gt;
        /// </summary>
        BrowserStop = 169,
        /// <summary>
        /// &lt;summary&gt; Browser Search key &lt;/summary&gt;
        /// </summary>
        BrowserSearch = 170,
        /// <summary>
        /// &lt;summary&gt; Browser Favorites key &lt;/summary&gt;
        /// </summary>
        BrowserFavorites = 171,
        /// <summary>
        /// &lt;summary&gt; Browser Start and Home key &lt;/summary&gt;
        /// </summary>
        BrowserHome = 172,
        /// <summary>
        /// &lt;summary&gt; Volume Mute key &lt;/summary&gt;
        /// </summary>
        VolumeMute = 173,
        /// <summary>
        /// &lt;summary&gt; Volume Down key &lt;/summary&gt;
        /// </summary>
        VolumeDown = 174,
        /// <summary>
        /// &lt;summary&gt; Volume Up key &lt;/summary&gt;
        /// </summary>
        VolumeUp = 175,
        /// <summary>
        /// &lt;summary&gt; Next Track key &lt;/summary&gt;
        /// </summary>
        MediaNextTrack = 176,
        /// <summary>
        /// &lt;summary&gt; Previous Track key &lt;/summary&gt;
        /// </summary>
        MediaPrevTrack = 177,
        /// <summary>
        /// &lt;summary&gt; Stop Media key &lt;/summary&gt;
        /// </summary>
        MediaStop = 178,
        /// <summary>
        /// &lt;summary&gt; Play/Pause Media key &lt;/summary&gt;
        /// </summary>
        MediaPlayPause = 179,
        /// <summary>
        /// &lt;summary&gt; Start Mail key &lt;/summary&gt;
        /// </summary>
        LaunchMail = 180,
        /// <summary>
        /// &lt;summary&gt; Select Media key &lt;/summary&gt;
        /// </summary>
        LaunchMediaSelect = 181,
        /// <summary>
        /// &lt;summary&gt; Start Application 1 key &lt;/summary&gt;
        /// </summary>
        LaunchApp1 = 182,
        /// <summary>
        /// &lt;summary&gt; Start Application 2 key &lt;/summary&gt;
        /// </summary>
        LaunchApp2 = 183,
        /// <summary>
        /// &lt;summary&gt; Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard the ';:' key &lt;/summary&gt;
        /// </summary>
        Colon = 186,
        /// <summary>
        /// &lt;summary&gt; For any country/region the '+' key &lt;/summary&gt;
        /// </summary>
        Plus = 187,
        /// <summary>
        /// &lt;summary&gt; For any country/region the ',' key &lt;/summary&gt;
        /// </summary>
        Comma = 188,
        /// <summary>
        /// &lt;summary&gt; For any country/region the '-' key &lt;/summary&gt;
        /// </summary>
        Minus = 189,
        /// <summary>
        /// &lt;summary&gt; For any country/region the '.' key &lt;/summary&gt;
        /// </summary>
        Period = 190,
        /// <summary>
        /// &lt;summary&gt; Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard the '/?' key &lt;/summary&gt;
        /// </summary>
        Slash = 191,
        /// <summary>
        /// &lt;summary&gt; Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard the '`~' key &lt;/summary&gt;
        /// </summary>
        BackQuote = 192,
        /// <summary>
        /// &lt;summary&gt; Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard the '[{' key &lt;/summary&gt;
        /// </summary>
        LeftBracket = 219,
        /// <summary>
        /// &lt;summary&gt; Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard the '\|' key &lt;/summary&gt;
        /// </summary>
        Backslash = 220,
        /// <summary>
        /// &lt;summary&gt; Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard the ']}' key &lt;/summary&gt;
        /// </summary>
        RightBracket = 221,
        /// <summary>
        /// &lt;summary&gt; Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard the 'single-quote/double-quote' key &lt;/summary&gt;
        /// </summary>
        Quote = 222,
        /// <summary>
        /// &lt;summary&gt; Used for miscellaneous characters; it can vary by keyboard. &lt;/summary&gt;
        /// </summary>
        Oem8 = 223,
        /// <summary>
        /// &lt;summary&gt; Either the angle bracket key or the backslash key on the RT 102-key keyboard &lt;/summary&gt;
        /// </summary>
        Oem102 = 226,
        /// <summary>
        /// &lt;summary&gt; IME PROCESS key &lt;/summary&gt;
        /// </summary>
        Processkey = 229,
        /// <summary>
        /// &lt;summary&gt; Used to pass Unicode characters as if they were keystrokes. The PACKET key is the low word of a 32-bit Virtual Key value used for non-keyboard input methods. &lt;/summary&gt;
        /// </summary>
        Packet = 231,
        /// <summary>
        /// &lt;summary&gt; Attn key &lt;/summary&gt;
        /// </summary>
        Attn = 246,
        /// <summary>
        /// &lt;summary&gt; CrSel key &lt;/summary&gt;
        /// </summary>
        Crsel = 247,
        /// <summary>
        /// &lt;summary&gt; ExSel key &lt;/summary&gt;
        /// </summary>
        Exsel = 248,
        /// <summary>
        /// &lt;summary&gt; Erase EOF key &lt;/summary&gt;
        /// </summary>
        Ereof = 249,
        /// <summary>
        /// &lt;summary&gt; Play key &lt;/summary&gt;
        /// </summary>
        Play = 250,
        /// <summary>
        /// &lt;summary&gt; Zoom key &lt;/summary&gt;
        /// </summary>
        Zoom = 251,
        /// <summary>
        /// &lt;summary&gt; PA1 key &lt;/summary&gt;
        /// </summary>
        Pa1 = 253,
        /// <summary>
        /// &lt;summary&gt; Clear key &lt;/summary&gt;
        /// </summary>
        OemClear = 254,
        /// <summary>
        /// &lt;summary&gt; Clear key &lt;/summary&gt;
        /// </summary>
        MAX = 255
    }
}

