//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Level/Level.h
//-------------------------------------------------------------------------
#pragma warning disable CS0108
#pragma warning disable CS8603
#pragma warning disable CS8625
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using SE.Interop;

namespace SE
{
    public unsafe static partial class Level
    {
        [LibraryImport("SERuntime", EntryPoint = "Level_SceneSaving_ManagedBind", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_SceneSaving_Bind([MarshalAs(UnmanagedType.U1)] bool bind);

        public delegate void SceneSavingDelegate(SE.Scene arg0, ref System.Guid arg1);

        private static int _SceneSavingBindCount;
        private static readonly object _SceneSavingSync = new object();
        private static SceneSavingDelegate _SceneSaving;

        /// <summary>
        /// /////////////////// Scene Event &lt;summary&gt; Fired when scene starts saving. &lt;/summary&gt;
        /// </summary>
        public static event SceneSavingDelegate SceneSaving
        {
            add
            {
                if (value == null) return;
                lock (_SceneSavingSync)
                {
                    _SceneSaving += value;
                    if (_SceneSavingBindCount++ != 0) return;
                    Internal_SceneSaving_Bind(true);
                }
            }
            remove
            {
                if (value == null) return;
                lock (_SceneSavingSync)
                {
                    var updated = (SceneSavingDelegate)Delegate.Remove(_SceneSaving, value);
                    if (updated == _SceneSaving) return;
                    _SceneSaving = updated;
                    if (--_SceneSavingBindCount != 0) return;
                    Internal_SceneSaving_Bind(false);
                }
            }
        }

        internal static void Internal_SceneSaving_Invoke(IntPtr arg0, ref System.Guid arg1)
        {
            SceneSavingDelegate handler;
            lock (_SceneSavingSync) handler = _SceneSaving;
            if (handler != null)
            {
                handler.Invoke((SE.Scene)SE.Interop.ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(arg0), ref arg1);
            }
        }

        [LibraryImport("SERuntime", EntryPoint = "Level_SceneSaved_ManagedBind", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_SceneSaved_Bind([MarshalAs(UnmanagedType.U1)] bool bind);

        public delegate void SceneSavedDelegate(SE.Scene arg0, ref System.Guid arg1);

        private static int _SceneSavedBindCount;
        private static readonly object _SceneSavedSync = new object();
        private static SceneSavedDelegate _SceneSaved;

        /// <summary>
        /// &lt;summary&gt; Fired when scene gets saved. &lt;/summary&gt;
        /// </summary>
        public static event SceneSavedDelegate SceneSaved
        {
            add
            {
                if (value == null) return;
                lock (_SceneSavedSync)
                {
                    _SceneSaved += value;
                    if (_SceneSavedBindCount++ != 0) return;
                    Internal_SceneSaved_Bind(true);
                }
            }
            remove
            {
                if (value == null) return;
                lock (_SceneSavedSync)
                {
                    var updated = (SceneSavedDelegate)Delegate.Remove(_SceneSaved, value);
                    if (updated == _SceneSaved) return;
                    _SceneSaved = updated;
                    if (--_SceneSavedBindCount != 0) return;
                    Internal_SceneSaved_Bind(false);
                }
            }
        }

        internal static void Internal_SceneSaved_Invoke(IntPtr arg0, ref System.Guid arg1)
        {
            SceneSavedDelegate handler;
            lock (_SceneSavedSync) handler = _SceneSaved;
            if (handler != null)
            {
                handler.Invoke((SE.Scene)SE.Interop.ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(arg0), ref arg1);
            }
        }

        [LibraryImport("SERuntime", EntryPoint = "Level_SceneSaveError_ManagedBind", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_SceneSaveError_Bind([MarshalAs(UnmanagedType.U1)] bool bind);

        public delegate void SceneSaveErrorDelegate(SE.Scene arg0, ref System.Guid arg1);

        private static int _SceneSaveErrorBindCount;
        private static readonly object _SceneSaveErrorSync = new object();
        private static SceneSaveErrorDelegate _SceneSaveError;

        /// <summary>
        /// &lt;summary&gt; Fired when scene gets saving error. &lt;/summary&gt;
        /// </summary>
        public static event SceneSaveErrorDelegate SceneSaveError
        {
            add
            {
                if (value == null) return;
                lock (_SceneSaveErrorSync)
                {
                    _SceneSaveError += value;
                    if (_SceneSaveErrorBindCount++ != 0) return;
                    Internal_SceneSaveError_Bind(true);
                }
            }
            remove
            {
                if (value == null) return;
                lock (_SceneSaveErrorSync)
                {
                    var updated = (SceneSaveErrorDelegate)Delegate.Remove(_SceneSaveError, value);
                    if (updated == _SceneSaveError) return;
                    _SceneSaveError = updated;
                    if (--_SceneSaveErrorBindCount != 0) return;
                    Internal_SceneSaveError_Bind(false);
                }
            }
        }

        internal static void Internal_SceneSaveError_Invoke(IntPtr arg0, ref System.Guid arg1)
        {
            SceneSaveErrorDelegate handler;
            lock (_SceneSaveErrorSync) handler = _SceneSaveError;
            if (handler != null)
            {
                handler.Invoke((SE.Scene)SE.Interop.ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(arg0), ref arg1);
            }
        }

        [LibraryImport("SERuntime", EntryPoint = "Level_SceneLoading_ManagedBind", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_SceneLoading_Bind([MarshalAs(UnmanagedType.U1)] bool bind);

        public delegate void SceneLoadingDelegate(SE.Scene arg0, ref System.Guid arg1);

        private static int _SceneLoadingBindCount;
        private static readonly object _SceneLoadingSync = new object();
        private static SceneLoadingDelegate _SceneLoading;

        /// <summary>
        /// &lt;summary&gt; Fired when scene starts loading. &lt;/summary&gt;
        /// </summary>
        public static event SceneLoadingDelegate SceneLoading
        {
            add
            {
                if (value == null) return;
                lock (_SceneLoadingSync)
                {
                    _SceneLoading += value;
                    if (_SceneLoadingBindCount++ != 0) return;
                    Internal_SceneLoading_Bind(true);
                }
            }
            remove
            {
                if (value == null) return;
                lock (_SceneLoadingSync)
                {
                    var updated = (SceneLoadingDelegate)Delegate.Remove(_SceneLoading, value);
                    if (updated == _SceneLoading) return;
                    _SceneLoading = updated;
                    if (--_SceneLoadingBindCount != 0) return;
                    Internal_SceneLoading_Bind(false);
                }
            }
        }

        internal static void Internal_SceneLoading_Invoke(IntPtr arg0, ref System.Guid arg1)
        {
            SceneLoadingDelegate handler;
            lock (_SceneLoadingSync) handler = _SceneLoading;
            if (handler != null)
            {
                handler.Invoke((SE.Scene)SE.Interop.ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(arg0), ref arg1);
            }
        }

        [LibraryImport("SERuntime", EntryPoint = "Level_SceneLoaded_ManagedBind", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_SceneLoaded_Bind([MarshalAs(UnmanagedType.U1)] bool bind);

        public delegate void SceneLoadedDelegate(SE.Scene arg0, ref System.Guid arg1);

        private static int _SceneLoadedBindCount;
        private static readonly object _SceneLoadedSync = new object();
        private static SceneLoadedDelegate _SceneLoaded;

        /// <summary>
        /// &lt;summary&gt; Fired when scene gets loaded. &lt;/summary&gt;
        /// </summary>
        public static event SceneLoadedDelegate SceneLoaded
        {
            add
            {
                if (value == null) return;
                lock (_SceneLoadedSync)
                {
                    _SceneLoaded += value;
                    if (_SceneLoadedBindCount++ != 0) return;
                    Internal_SceneLoaded_Bind(true);
                }
            }
            remove
            {
                if (value == null) return;
                lock (_SceneLoadedSync)
                {
                    var updated = (SceneLoadedDelegate)Delegate.Remove(_SceneLoaded, value);
                    if (updated == _SceneLoaded) return;
                    _SceneLoaded = updated;
                    if (--_SceneLoadedBindCount != 0) return;
                    Internal_SceneLoaded_Bind(false);
                }
            }
        }

        internal static void Internal_SceneLoaded_Invoke(IntPtr arg0, ref System.Guid arg1)
        {
            SceneLoadedDelegate handler;
            lock (_SceneLoadedSync) handler = _SceneLoaded;
            if (handler != null)
            {
                handler.Invoke((SE.Scene)SE.Interop.ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(arg0), ref arg1);
            }
        }

        [LibraryImport("SERuntime", EntryPoint = "Level_SceneLoadError_ManagedBind", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_SceneLoadError_Bind([MarshalAs(UnmanagedType.U1)] bool bind);

        public delegate void SceneLoadErrorDelegate(SE.Scene arg0, ref System.Guid arg1);

        private static int _SceneLoadErrorBindCount;
        private static readonly object _SceneLoadErrorSync = new object();
        private static SceneLoadErrorDelegate _SceneLoadError;

        /// <summary>
        /// &lt;summary&gt; Fired when scene cannot be loaded (argument is error number). &lt;/summary&gt;
        /// </summary>
        public static event SceneLoadErrorDelegate SceneLoadError
        {
            add
            {
                if (value == null) return;
                lock (_SceneLoadErrorSync)
                {
                    _SceneLoadError += value;
                    if (_SceneLoadErrorBindCount++ != 0) return;
                    Internal_SceneLoadError_Bind(true);
                }
            }
            remove
            {
                if (value == null) return;
                lock (_SceneLoadErrorSync)
                {
                    var updated = (SceneLoadErrorDelegate)Delegate.Remove(_SceneLoadError, value);
                    if (updated == _SceneLoadError) return;
                    _SceneLoadError = updated;
                    if (--_SceneLoadErrorBindCount != 0) return;
                    Internal_SceneLoadError_Bind(false);
                }
            }
        }

        internal static void Internal_SceneLoadError_Invoke(IntPtr arg0, ref System.Guid arg1)
        {
            SceneLoadErrorDelegate handler;
            lock (_SceneLoadErrorSync) handler = _SceneLoadError;
            if (handler != null)
            {
                handler.Invoke((SE.Scene)SE.Interop.ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(arg0), ref arg1);
            }
        }

        [LibraryImport("SERuntime", EntryPoint = "Level_SceneUnloading_ManagedBind", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_SceneUnloading_Bind([MarshalAs(UnmanagedType.U1)] bool bind);

        public delegate void SceneUnloadingDelegate(SE.Scene arg0, ref System.Guid arg1);

        private static int _SceneUnloadingBindCount;
        private static readonly object _SceneUnloadingSync = new object();
        private static SceneUnloadingDelegate _SceneUnloading;

        /// <summary>
        /// &lt;summary&gt; Fired when scene gets unloading. &lt;/summary&gt;
        /// </summary>
        public static event SceneUnloadingDelegate SceneUnloading
        {
            add
            {
                if (value == null) return;
                lock (_SceneUnloadingSync)
                {
                    _SceneUnloading += value;
                    if (_SceneUnloadingBindCount++ != 0) return;
                    Internal_SceneUnloading_Bind(true);
                }
            }
            remove
            {
                if (value == null) return;
                lock (_SceneUnloadingSync)
                {
                    var updated = (SceneUnloadingDelegate)Delegate.Remove(_SceneUnloading, value);
                    if (updated == _SceneUnloading) return;
                    _SceneUnloading = updated;
                    if (--_SceneUnloadingBindCount != 0) return;
                    Internal_SceneUnloading_Bind(false);
                }
            }
        }

        internal static void Internal_SceneUnloading_Invoke(IntPtr arg0, ref System.Guid arg1)
        {
            SceneUnloadingDelegate handler;
            lock (_SceneUnloadingSync) handler = _SceneUnloading;
            if (handler != null)
            {
                handler.Invoke((SE.Scene)SE.Interop.ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(arg0), ref arg1);
            }
        }

        [LibraryImport("SERuntime", EntryPoint = "Level_SceneUnloaded_ManagedBind", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_SceneUnloaded_Bind([MarshalAs(UnmanagedType.U1)] bool bind);

        public delegate void SceneUnloadedDelegate(SE.Scene arg0, ref System.Guid arg1);

        private static int _SceneUnloadedBindCount;
        private static readonly object _SceneUnloadedSync = new object();
        private static SceneUnloadedDelegate _SceneUnloaded;

        /// <summary>
        /// &lt;summary&gt; Fired when scene gets unloaded. &lt;/summary&gt;
        /// </summary>
        public static event SceneUnloadedDelegate SceneUnloaded
        {
            add
            {
                if (value == null) return;
                lock (_SceneUnloadedSync)
                {
                    _SceneUnloaded += value;
                    if (_SceneUnloadedBindCount++ != 0) return;
                    Internal_SceneUnloaded_Bind(true);
                }
            }
            remove
            {
                if (value == null) return;
                lock (_SceneUnloadedSync)
                {
                    var updated = (SceneUnloadedDelegate)Delegate.Remove(_SceneUnloaded, value);
                    if (updated == _SceneUnloaded) return;
                    _SceneUnloaded = updated;
                    if (--_SceneUnloadedBindCount != 0) return;
                    Internal_SceneUnloaded_Bind(false);
                }
            }
        }

        internal static void Internal_SceneUnloaded_Invoke(IntPtr arg0, ref System.Guid arg1)
        {
            SceneUnloadedDelegate handler;
            lock (_SceneUnloadedSync) handler = _SceneUnloaded;
            if (handler != null)
            {
                handler.Invoke((SE.Scene)SE.Interop.ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(arg0), ref arg1);
            }
        }

        [LibraryImport("SERuntime", EntryPoint = "Level_ActorSpawned_ManagedBind", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_ActorSpawned_Bind([MarshalAs(UnmanagedType.U1)] bool bind);

        private static int _ActorSpawnedBindCount;
        private static readonly object _ActorSpawnedSync = new object();
        private static Action<SE.Actor> _ActorSpawned;

        /// <summary>
        /// /////////////////// Actor Event &lt;summary&gt; Occurs when new actor gets spawned to the game. &lt;/summary&gt;
        /// </summary>
        public static event Action<SE.Actor> ActorSpawned
        {
            add
            {
                if (value == null) return;
                lock (_ActorSpawnedSync)
                {
                    _ActorSpawned += value;
                    if (_ActorSpawnedBindCount++ != 0) return;
                    Internal_ActorSpawned_Bind(true);
                }
            }
            remove
            {
                if (value == null) return;
                lock (_ActorSpawnedSync)
                {
                    var updated = (Action<SE.Actor>)Delegate.Remove(_ActorSpawned, value);
                    if (updated == _ActorSpawned) return;
                    _ActorSpawned = updated;
                    if (--_ActorSpawnedBindCount != 0) return;
                    Internal_ActorSpawned_Bind(false);
                }
            }
        }

        internal static void Internal_ActorSpawned_Invoke(IntPtr arg0)
        {
            Action<SE.Actor> handler;
            lock (_ActorSpawnedSync) handler = _ActorSpawned;
            if (handler != null)
            {
                handler.Invoke((SE.Actor)SE.Interop.ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(arg0));
            }
        }

        [LibraryImport("SERuntime", EntryPoint = "Level_ActorDeleted_ManagedBind", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_ActorDeleted_Bind([MarshalAs(UnmanagedType.U1)] bool bind);

        private static int _ActorDeletedBindCount;
        private static readonly object _ActorDeletedSync = new object();
        private static Action<SE.Actor> _ActorDeleted;

        /// <summary>
        /// &lt;summary&gt; Occurs when actor is removed from the game. &lt;/summary&gt;
        /// </summary>
        public static event Action<SE.Actor> ActorDeleted
        {
            add
            {
                if (value == null) return;
                lock (_ActorDeletedSync)
                {
                    _ActorDeleted += value;
                    if (_ActorDeletedBindCount++ != 0) return;
                    Internal_ActorDeleted_Bind(true);
                }
            }
            remove
            {
                if (value == null) return;
                lock (_ActorDeletedSync)
                {
                    var updated = (Action<SE.Actor>)Delegate.Remove(_ActorDeleted, value);
                    if (updated == _ActorDeleted) return;
                    _ActorDeleted = updated;
                    if (--_ActorDeletedBindCount != 0) return;
                    Internal_ActorDeleted_Bind(false);
                }
            }
        }

        internal static void Internal_ActorDeleted_Invoke(IntPtr arg0)
        {
            Action<SE.Actor> handler;
            lock (_ActorDeletedSync) handler = _ActorDeleted;
            if (handler != null)
            {
                handler.Invoke((SE.Actor)SE.Interop.ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(arg0));
            }
        }

        [LibraryImport("SERuntime", EntryPoint = "Level_ActorParentChanged_ManagedBind", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_ActorParentChanged_Bind([MarshalAs(UnmanagedType.U1)] bool bind);

        private static int _ActorParentChangedBindCount;
        private static readonly object _ActorParentChangedSync = new object();
        private static Action<SE.Actor, SE.Actor> _ActorParentChanged;

        /// <summary>
        /// &lt;summary&gt; Occurs when actor parent gets changed. Arguments: actor and previous parent actor. &lt;/summary&gt;
        /// </summary>
        public static event Action<SE.Actor, SE.Actor> ActorParentChanged
        {
            add
            {
                if (value == null) return;
                lock (_ActorParentChangedSync)
                {
                    _ActorParentChanged += value;
                    if (_ActorParentChangedBindCount++ != 0) return;
                    Internal_ActorParentChanged_Bind(true);
                }
            }
            remove
            {
                if (value == null) return;
                lock (_ActorParentChangedSync)
                {
                    var updated = (Action<SE.Actor, SE.Actor>)Delegate.Remove(_ActorParentChanged, value);
                    if (updated == _ActorParentChanged) return;
                    _ActorParentChanged = updated;
                    if (--_ActorParentChangedBindCount != 0) return;
                    Internal_ActorParentChanged_Bind(false);
                }
            }
        }

        internal static void Internal_ActorParentChanged_Invoke(IntPtr arg0, IntPtr arg1)
        {
            Action<SE.Actor, SE.Actor> handler;
            lock (_ActorParentChangedSync) handler = _ActorParentChanged;
            if (handler != null)
            {
                handler.Invoke((SE.Actor)SE.Interop.ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(arg0), (SE.Actor)SE.Interop.ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(arg1));
            }
        }

        [LibraryImport("SERuntime", EntryPoint = "Level_ActorOrderInParentChanged_ManagedBind", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_ActorOrderInParentChanged_Bind([MarshalAs(UnmanagedType.U1)] bool bind);

        private static int _ActorOrderInParentChangedBindCount;
        private static readonly object _ActorOrderInParentChangedSync = new object();
        private static Action<SE.Actor> _ActorOrderInParentChanged;

        /// <summary>
        /// &lt;summary&gt; Occurs when actor index in parent actor children gets changed. &lt;/summary&gt;
        /// </summary>
        public static event Action<SE.Actor> ActorOrderInParentChanged
        {
            add
            {
                if (value == null) return;
                lock (_ActorOrderInParentChangedSync)
                {
                    _ActorOrderInParentChanged += value;
                    if (_ActorOrderInParentChangedBindCount++ != 0) return;
                    Internal_ActorOrderInParentChanged_Bind(true);
                }
            }
            remove
            {
                if (value == null) return;
                lock (_ActorOrderInParentChangedSync)
                {
                    var updated = (Action<SE.Actor>)Delegate.Remove(_ActorOrderInParentChanged, value);
                    if (updated == _ActorOrderInParentChanged) return;
                    _ActorOrderInParentChanged = updated;
                    if (--_ActorOrderInParentChangedBindCount != 0) return;
                    Internal_ActorOrderInParentChanged_Bind(false);
                }
            }
        }

        internal static void Internal_ActorOrderInParentChanged_Invoke(IntPtr arg0)
        {
            Action<SE.Actor> handler;
            lock (_ActorOrderInParentChangedSync) handler = _ActorOrderInParentChanged;
            if (handler != null)
            {
                handler.Invoke((SE.Actor)SE.Interop.ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(arg0));
            }
        }

        [LibraryImport("SERuntime", EntryPoint = "Level_ActorNameChanged_ManagedBind", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_ActorNameChanged_Bind([MarshalAs(UnmanagedType.U1)] bool bind);

        private static int _ActorNameChangedBindCount;
        private static readonly object _ActorNameChangedSync = new object();
        private static Action<SE.Actor> _ActorNameChanged;

        /// <summary>
        /// &lt;summary&gt; Occurs when actor name gets changed. &lt;/summary&gt;
        /// </summary>
        public static event Action<SE.Actor> ActorNameChanged
        {
            add
            {
                if (value == null) return;
                lock (_ActorNameChangedSync)
                {
                    _ActorNameChanged += value;
                    if (_ActorNameChangedBindCount++ != 0) return;
                    Internal_ActorNameChanged_Bind(true);
                }
            }
            remove
            {
                if (value == null) return;
                lock (_ActorNameChangedSync)
                {
                    var updated = (Action<SE.Actor>)Delegate.Remove(_ActorNameChanged, value);
                    if (updated == _ActorNameChanged) return;
                    _ActorNameChanged = updated;
                    if (--_ActorNameChangedBindCount != 0) return;
                    Internal_ActorNameChanged_Bind(false);
                }
            }
        }

        internal static void Internal_ActorNameChanged_Invoke(IntPtr arg0)
        {
            Action<SE.Actor> handler;
            lock (_ActorNameChangedSync) handler = _ActorNameChanged;
            if (handler != null)
            {
                handler.Invoke((SE.Actor)SE.Interop.ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(arg0));
            }
        }

        [LibraryImport("SERuntime", EntryPoint = "Level_ActorActiveChanged_ManagedBind", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_ActorActiveChanged_Bind([MarshalAs(UnmanagedType.U1)] bool bind);

        private static int _ActorActiveChangedBindCount;
        private static readonly object _ActorActiveChangedSync = new object();
        private static Action<SE.Actor> _ActorActiveChanged;

        /// <summary>
        /// &lt;summary&gt; Occurs when actor active state gets modified. &lt;/summary&gt;
        /// </summary>
        public static event Action<SE.Actor> ActorActiveChanged
        {
            add
            {
                if (value == null) return;
                lock (_ActorActiveChangedSync)
                {
                    _ActorActiveChanged += value;
                    if (_ActorActiveChangedBindCount++ != 0) return;
                    Internal_ActorActiveChanged_Bind(true);
                }
            }
            remove
            {
                if (value == null) return;
                lock (_ActorActiveChangedSync)
                {
                    var updated = (Action<SE.Actor>)Delegate.Remove(_ActorActiveChanged, value);
                    if (updated == _ActorActiveChanged) return;
                    _ActorActiveChanged = updated;
                    if (--_ActorActiveChangedBindCount != 0) return;
                    Internal_ActorActiveChanged_Bind(false);
                }
            }
        }

        internal static void Internal_ActorActiveChanged_Invoke(IntPtr arg0)
        {
            Action<SE.Actor> handler;
            lock (_ActorActiveChangedSync) handler = _ActorActiveChanged;
            if (handler != null)
            {
                handler.Invoke((SE.Actor)SE.Interop.ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(arg0));
            }
        }

        [LibraryImport("SERuntime", EntryPoint = "Level_GetScenesCount", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial int Internal_GetScenesCount();

        [LibraryImport("SERuntime", EntryPoint = "Level_IsAnySceneLoaded", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static partial bool Internal_IsAnySceneLoaded();

        [LibraryImport("SERuntime", EntryPoint = "Level_GetScene", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial IntPtr Internal_GetScene(int index);

        [LibraryImport("SERuntime", EntryPoint = "Level_FindScene", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial IntPtr Internal_FindScene(ref System.Guid id);

        [LibraryImport("SERuntime", EntryPoint = "Level_GetSceneName", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial string Internal_GetSceneName(int index);

        [LibraryImport("SERuntime", EntryPoint = "Level_SaveSceneAt", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static partial bool Internal_SaveSceneAt(int index);

        [LibraryImport("SERuntime", EntryPoint = "Level_SpawnActor", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static partial bool Internal_SpawnActor(IntPtr actor, IntPtr parent);

        [LibraryImport("SERuntime", EntryPoint = "Level_DeleteActor", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static partial bool Internal_DeleteActor(IntPtr actor);

        [LibraryImport("SERuntime", EntryPoint = "Level_LoadSceneAsync", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static partial bool Internal_LoadSceneAsync(ref System.Guid id);

        [LibraryImport("SERuntime", EntryPoint = "Level_SaveScene", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static partial bool Internal_SaveScene(IntPtr scene, [MarshalAs(UnmanagedType.U1)] bool prettyJson);

        [LibraryImport("SERuntime", EntryPoint = "Level_SaveSceneAsync", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_SaveSceneAsync(IntPtr scene);

        /// <summary>
        /// &lt;summary&gt; Gets the scenes count. &lt;/summary&gt;
        /// </summary>
        public static int  GetScenesCount()
        {
            return Internal_GetScenesCount();
        }

        public static bool  IsAnySceneLoaded()
        {
            return Internal_IsAnySceneLoaded();
        }

        /// <summary>
        /// &lt;summary&gt; Gets the scene. &lt;/summary&gt; &lt;param name="index"&gt;The index.&lt;/param&gt; &lt;returns&gt;The scene object (loaded).&lt;/returns&gt;
        /// </summary>
        public static SE.Scene  GetScene(int index)
        {
            return (SE.Scene)SE.Interop.ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(Internal_GetScene(index));
        }

        public static SE.Scene  FindScene(ref System.Guid id)
        {
            return (SE.Scene)SE.Interop.ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(Internal_FindScene(ref id));
        }

        /// <summary>
        /// &lt;summary&gt; Gets a loaded scene name by its current level index. &lt;/summary&gt;
        /// </summary>
        public static string  GetSceneName(int index)
        {
            return Internal_GetSceneName(index);
        }

        /// <summary>
        /// &lt;summary&gt; Queues saving a loaded scene selected by its current level index. &lt;/summary&gt;
        /// </summary>
        public static bool  SaveSceneAt(int index)
        {
            return Internal_SaveSceneAt(index);
        }

        /// <summary>
        /// &lt;summary&gt; Spawns actor on the scene. &lt;/summary&gt; &lt;param name="actor"&gt;The actor to spawn.&lt;/param&gt; &lt;param name="parent"&gt;The parent actor (will link spawned actor with this parent).&lt;/param&gt; &lt;returns&gt;True if action cannot be done, otherwise false.&lt;/returns&gt;
        /// </summary>
        public static bool  SpawnActor(SE.Actor actor, SE.Actor parent)
        {
            return Internal_SpawnActor(Object.GetUnmanagedPtr(actor), Object.GetUnmanagedPtr(parent));
        }

        /// <summary>
        /// &lt;summary&gt; Deletes actor from the scene. &lt;/summary&gt; &lt;param name="actor"&gt;The actor to delete.&lt;/param&gt; &lt;returns&gt;True if action cannot be done, otherwise false.&lt;/returns&gt;
        /// </summary>
        public static bool  DeleteActor(SE.Actor actor)
        {
            return Internal_DeleteActor(Object.GetUnmanagedPtr(actor));
        }

        /// <summary>
        /// &lt;summary&gt; Loads scene from the asset. Done in the background. &lt;/summary&gt; &lt;param name="id"&gt;Scene ID&lt;/param&gt; &lt;returns&gt;True if loading cannot be done, otherwise false.&lt;/returns&gt;
        /// </summary>
        public static bool  LoadSceneAsync(ref System.Guid id)
        {
            return Internal_LoadSceneAsync(ref id);
        }

        public static bool  SaveScene(SE.Scene scene, bool prettyJson = true)
        {
            return Internal_SaveScene(Object.GetUnmanagedPtr(scene), prettyJson);
        }

        public static void  SaveSceneAsync(SE.Scene scene)
        {
            Internal_SaveSceneAsync(Object.GetUnmanagedPtr(scene));
        }

    }
}

