//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Level/Actors/Light.h
//-------------------------------------------------------------------------
#pragma warning disable CS0108
#pragma warning disable CS8603
#pragma warning disable CS8625
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using SE.Interop;

namespace SE
{
    /// <summary>
    /// &lt;summary&gt; Base class for all light types. &lt;/summary&gt;
    /// </summary>
    [NativeMarshalling(typeof(LightMarshaller))]
    public unsafe abstract partial class Light : SE.RenderActor
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Light"/>.
        /// </summary>
        protected Light() : base()
        {
        }


        [CustomMarshaller(typeof(Light), MarshalMode.ManagedToUnmanagedIn, typeof(LightMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Light), MarshalMode.ElementIn, typeof(LightMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Light), MarshalMode.ManagedToUnmanagedOut, typeof(LightMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Light), MarshalMode.UnmanagedToManagedIn, typeof(LightMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Light), MarshalMode.ElementOut, typeof(LightMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Light), MarshalMode.ManagedToUnmanagedRef, typeof(LightMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(Light), MarshalMode.UnmanagedToManagedRef, typeof(LightMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(Light), MarshalMode.ElementRef, typeof(LightMarshaller))]
        internal struct LightMarshaller
        {
            #pragma warning disable 1591
            public static class NativeToManaged
            {
                public static Light ConvertToManaged(IntPtr unmanaged) => Unsafe.As<Light>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(Light managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public static class ManagedToNative
            {
                public static Light ConvertToManaged(IntPtr unmanaged) => Unsafe.As<Light>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(Light managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public struct Bidirectional
            {
                ManagedHandleMarshaller.Bidirectional marsh;
                public void FromManaged(Light managed) => marsh.FromManaged(managed);
                public IntPtr ToUnmanaged() => marsh.ToUnmanaged();
                public void FromUnmanaged(IntPtr unmanaged) => marsh.FromUnmanaged(unmanaged);
                public Light ToManaged() => Unsafe.As<Light>(marsh.ToManaged());
                public void Free() => marsh.Free();
            }
            internal static Light ConvertToManaged(IntPtr unmanaged) => Unsafe.As<Light>(ManagedHandleMarshaller.ConvertToManaged(unmanaged));
            internal static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.Free(unmanaged);
            internal static Light ToManaged(IntPtr managed) => Unsafe.As<Light>(ManagedHandleMarshaller.ToManaged(managed));
            internal static IntPtr ToNative(Light managed) => ManagedHandleMarshaller.ToNative(managed);
        #pragma warning restore 1591
        }

    }
}

namespace SE
{
    /// <summary>
    /// &lt;summary&gt; Base class for all light types that can cast dynamic or static shadow. Contains more shared properties for point/spot/directional lights. &lt;/summary&gt;
    /// </summary>
    [NativeMarshalling(typeof(LightWithShadowMarshaller))]
    public unsafe abstract partial class LightWithShadow : SE.Light
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LightWithShadow"/>.
        /// </summary>
        protected LightWithShadow() : base()
        {
        }


        [CustomMarshaller(typeof(LightWithShadow), MarshalMode.ManagedToUnmanagedIn, typeof(LightWithShadowMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(LightWithShadow), MarshalMode.ElementIn, typeof(LightWithShadowMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(LightWithShadow), MarshalMode.ManagedToUnmanagedOut, typeof(LightWithShadowMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(LightWithShadow), MarshalMode.UnmanagedToManagedIn, typeof(LightWithShadowMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(LightWithShadow), MarshalMode.ElementOut, typeof(LightWithShadowMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(LightWithShadow), MarshalMode.ManagedToUnmanagedRef, typeof(LightWithShadowMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(LightWithShadow), MarshalMode.UnmanagedToManagedRef, typeof(LightWithShadowMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(LightWithShadow), MarshalMode.ElementRef, typeof(LightWithShadowMarshaller))]
        internal struct LightWithShadowMarshaller
        {
            #pragma warning disable 1591
            public static class NativeToManaged
            {
                public static LightWithShadow ConvertToManaged(IntPtr unmanaged) => Unsafe.As<LightWithShadow>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(LightWithShadow managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public static class ManagedToNative
            {
                public static LightWithShadow ConvertToManaged(IntPtr unmanaged) => Unsafe.As<LightWithShadow>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(LightWithShadow managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public struct Bidirectional
            {
                ManagedHandleMarshaller.Bidirectional marsh;
                public void FromManaged(LightWithShadow managed) => marsh.FromManaged(managed);
                public IntPtr ToUnmanaged() => marsh.ToUnmanaged();
                public void FromUnmanaged(IntPtr unmanaged) => marsh.FromUnmanaged(unmanaged);
                public LightWithShadow ToManaged() => Unsafe.As<LightWithShadow>(marsh.ToManaged());
                public void Free() => marsh.Free();
            }
            internal static LightWithShadow ConvertToManaged(IntPtr unmanaged) => Unsafe.As<LightWithShadow>(ManagedHandleMarshaller.ConvertToManaged(unmanaged));
            internal static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.Free(unmanaged);
            internal static LightWithShadow ToManaged(IntPtr managed) => Unsafe.As<LightWithShadow>(ManagedHandleMarshaller.ToManaged(managed));
            internal static IntPtr ToNative(LightWithShadow managed) => ManagedHandleMarshaller.ToNative(managed);
        #pragma warning restore 1591
        }

    }
}

