//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Resource/Assets/Materials/MaterialInstance.h
//-------------------------------------------------------------------------
#pragma warning disable CS0108
#pragma warning disable CS8603
#pragma warning disable CS8625
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using SE.Interop;

namespace SE
{
    /// <summary>
    /// &lt;summary&gt; Instance of the &lt;seealso cref="Material" /&gt; with custom set of material parameter values. &lt;/summary&gt;
    /// </summary>
    [NativeMarshalling(typeof(MaterialInstanceMarshaller))]
    public unsafe partial class MaterialInstance : SE.MaterialBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MaterialInstance"/>.
        /// </summary>
        public MaterialInstance() : base()
        {
        }


        [CustomMarshaller(typeof(MaterialInstance), MarshalMode.ManagedToUnmanagedIn, typeof(MaterialInstanceMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(MaterialInstance), MarshalMode.ElementIn, typeof(MaterialInstanceMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(MaterialInstance), MarshalMode.ManagedToUnmanagedOut, typeof(MaterialInstanceMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(MaterialInstance), MarshalMode.UnmanagedToManagedIn, typeof(MaterialInstanceMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(MaterialInstance), MarshalMode.ElementOut, typeof(MaterialInstanceMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(MaterialInstance), MarshalMode.ManagedToUnmanagedRef, typeof(MaterialInstanceMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(MaterialInstance), MarshalMode.UnmanagedToManagedRef, typeof(MaterialInstanceMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(MaterialInstance), MarshalMode.ElementRef, typeof(MaterialInstanceMarshaller))]
        internal struct MaterialInstanceMarshaller
        {
            #pragma warning disable 1591
            public static class NativeToManaged
            {
                public static MaterialInstance ConvertToManaged(IntPtr unmanaged) => Unsafe.As<MaterialInstance>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(MaterialInstance managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public static class ManagedToNative
            {
                public static MaterialInstance ConvertToManaged(IntPtr unmanaged) => Unsafe.As<MaterialInstance>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(MaterialInstance managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public struct Bidirectional
            {
                ManagedHandleMarshaller.Bidirectional marsh;
                public void FromManaged(MaterialInstance managed) => marsh.FromManaged(managed);
                public IntPtr ToUnmanaged() => marsh.ToUnmanaged();
                public void FromUnmanaged(IntPtr unmanaged) => marsh.FromUnmanaged(unmanaged);
                public MaterialInstance ToManaged() => Unsafe.As<MaterialInstance>(marsh.ToManaged());
                public void Free() => marsh.Free();
            }
            internal static MaterialInstance ConvertToManaged(IntPtr unmanaged) => Unsafe.As<MaterialInstance>(ManagedHandleMarshaller.ConvertToManaged(unmanaged));
            internal static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.Free(unmanaged);
            internal static MaterialInstance ToManaged(IntPtr managed) => Unsafe.As<MaterialInstance>(ManagedHandleMarshaller.ToManaged(managed));
            internal static IntPtr ToNative(MaterialInstance managed) => ManagedHandleMarshaller.ToNative(managed);
        #pragma warning restore 1591
        }

    }
}

