//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Core/Platform/MemoryStats.h
//-------------------------------------------------------------------------
#pragma warning disable CS0108
#pragma warning disable CS8603
#pragma warning disable CS8625
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using SE.Interop;

namespace SE
{
        [CustomMarshaller(typeof(MemoryStats), MarshalMode.ManagedToUnmanagedIn, typeof(MemoryStatsMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(MemoryStats), MarshalMode.UnmanagedToManagedOut, typeof(MemoryStatsMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(MemoryStats), MarshalMode.ElementIn, typeof(MemoryStatsMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(MemoryStats), MarshalMode.ManagedToUnmanagedOut, typeof(MemoryStatsMarshaller.NativeToManaged))]
        [CustomMarshaller(typeof(MemoryStats), MarshalMode.UnmanagedToManagedIn, typeof(MemoryStatsMarshaller.NativeToManaged))]
        [CustomMarshaller(typeof(MemoryStats), MarshalMode.ElementOut, typeof(MemoryStatsMarshaller.NativeToManaged))]
        [CustomMarshaller(typeof(MemoryStats), MarshalMode.ManagedToUnmanagedRef, typeof(MemoryStatsMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(MemoryStats), MarshalMode.UnmanagedToManagedRef, typeof(MemoryStatsMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(MemoryStats), MarshalMode.ElementRef, typeof(MemoryStatsMarshaller))]
        internal static partial class MemoryStatsMarshaller
        {
            [StructLayout(LayoutKind.Sequential)]
            internal unsafe struct MemoryStatsInternal
            {
            }

            public static MemoryStats ConvertToManaged(MemoryStatsInternal unmanaged)
            {
                var result = new MemoryStats();
                return result;
            }

            public static MemoryStatsInternal ConvertToUnmanaged(MemoryStats managed)
            {
                var result = new MemoryStatsInternal();
                return result;
            }

            public static void Free(MemoryStatsInternal unmanaged) { }

            public static class ManagedToNative
            {
                public static MemoryStats ConvertToManaged(MemoryStatsInternal unmanaged) => MemoryStatsMarshaller.ConvertToManaged(unmanaged);
                public static MemoryStatsInternal ConvertToUnmanaged(MemoryStats managed) => MemoryStatsMarshaller.ConvertToUnmanaged(managed);
                public static void Free(MemoryStatsInternal unmanaged) => MemoryStatsMarshaller.Free(unmanaged);
            }

            public static class NativeToManaged
            {
                public static MemoryStats ConvertToManaged(MemoryStatsInternal unmanaged) => MemoryStatsMarshaller.ConvertToManaged(unmanaged);
                public static MemoryStatsInternal ConvertToUnmanaged(MemoryStats managed) => MemoryStatsMarshaller.ConvertToUnmanaged(managed);
                public static void Free(MemoryStatsInternal unmanaged) => MemoryStatsMarshaller.Free(unmanaged);
            }

            public ref struct Bidirectional
            {
                private MemoryStatsInternal unmanaged;
                private MemoryStats managed;

                public Bidirectional(MemoryStats managed)
                {
                    this.managed = managed;
                    unmanaged = MemoryStatsMarshaller.ConvertToUnmanaged(managed);
                }

                public void FromManaged(MemoryStats managed) => this.managed = managed;
                public MemoryStatsInternal ToUnmanaged() { unmanaged = MemoryStatsMarshaller.ConvertToUnmanaged(managed); return unmanaged; }
                public void FromUnmanaged(MemoryStatsInternal unmanaged) => this.unmanaged = unmanaged;
                public MemoryStats ToManaged()
                {
                    managed = MemoryStatsMarshaller.ConvertToManaged(unmanaged);
                    return managed;
                }
                public void Free() { }
            }
        }

    /// <summary>
    /// &lt;summary&gt; Contains information about current memory usage and capacity. &lt;/summary&gt;
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    [NativeMarshalling(typeof(MemoryStatsMarshaller))]
    public unsafe partial struct MemoryStats
    {
        public static MemoryStats Default => new MemoryStats();

    }
}

namespace SE
{
        [CustomMarshaller(typeof(ProcessMemoryStats), MarshalMode.ManagedToUnmanagedIn, typeof(ProcessMemoryStatsMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(ProcessMemoryStats), MarshalMode.UnmanagedToManagedOut, typeof(ProcessMemoryStatsMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(ProcessMemoryStats), MarshalMode.ElementIn, typeof(ProcessMemoryStatsMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(ProcessMemoryStats), MarshalMode.ManagedToUnmanagedOut, typeof(ProcessMemoryStatsMarshaller.NativeToManaged))]
        [CustomMarshaller(typeof(ProcessMemoryStats), MarshalMode.UnmanagedToManagedIn, typeof(ProcessMemoryStatsMarshaller.NativeToManaged))]
        [CustomMarshaller(typeof(ProcessMemoryStats), MarshalMode.ElementOut, typeof(ProcessMemoryStatsMarshaller.NativeToManaged))]
        [CustomMarshaller(typeof(ProcessMemoryStats), MarshalMode.ManagedToUnmanagedRef, typeof(ProcessMemoryStatsMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(ProcessMemoryStats), MarshalMode.UnmanagedToManagedRef, typeof(ProcessMemoryStatsMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(ProcessMemoryStats), MarshalMode.ElementRef, typeof(ProcessMemoryStatsMarshaller))]
        internal static partial class ProcessMemoryStatsMarshaller
        {
            [StructLayout(LayoutKind.Sequential)]
            internal unsafe struct ProcessMemoryStatsInternal
            {
            }

            public static ProcessMemoryStats ConvertToManaged(ProcessMemoryStatsInternal unmanaged)
            {
                var result = new ProcessMemoryStats();
                return result;
            }

            public static ProcessMemoryStatsInternal ConvertToUnmanaged(ProcessMemoryStats managed)
            {
                var result = new ProcessMemoryStatsInternal();
                return result;
            }

            public static void Free(ProcessMemoryStatsInternal unmanaged) { }

            public static class ManagedToNative
            {
                public static ProcessMemoryStats ConvertToManaged(ProcessMemoryStatsInternal unmanaged) => ProcessMemoryStatsMarshaller.ConvertToManaged(unmanaged);
                public static ProcessMemoryStatsInternal ConvertToUnmanaged(ProcessMemoryStats managed) => ProcessMemoryStatsMarshaller.ConvertToUnmanaged(managed);
                public static void Free(ProcessMemoryStatsInternal unmanaged) => ProcessMemoryStatsMarshaller.Free(unmanaged);
            }

            public static class NativeToManaged
            {
                public static ProcessMemoryStats ConvertToManaged(ProcessMemoryStatsInternal unmanaged) => ProcessMemoryStatsMarshaller.ConvertToManaged(unmanaged);
                public static ProcessMemoryStatsInternal ConvertToUnmanaged(ProcessMemoryStats managed) => ProcessMemoryStatsMarshaller.ConvertToUnmanaged(managed);
                public static void Free(ProcessMemoryStatsInternal unmanaged) => ProcessMemoryStatsMarshaller.Free(unmanaged);
            }

            public ref struct Bidirectional
            {
                private ProcessMemoryStatsInternal unmanaged;
                private ProcessMemoryStats managed;

                public Bidirectional(ProcessMemoryStats managed)
                {
                    this.managed = managed;
                    unmanaged = ProcessMemoryStatsMarshaller.ConvertToUnmanaged(managed);
                }

                public void FromManaged(ProcessMemoryStats managed) => this.managed = managed;
                public ProcessMemoryStatsInternal ToUnmanaged() { unmanaged = ProcessMemoryStatsMarshaller.ConvertToUnmanaged(managed); return unmanaged; }
                public void FromUnmanaged(ProcessMemoryStatsInternal unmanaged) => this.unmanaged = unmanaged;
                public ProcessMemoryStats ToManaged()
                {
                    managed = ProcessMemoryStatsMarshaller.ConvertToManaged(unmanaged);
                    return managed;
                }
                public void Free() { }
            }
        }

    /// <summary>
    /// &lt;summary&gt; Contains information about current memory usage by the process. &lt;/summary&gt;
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    [NativeMarshalling(typeof(ProcessMemoryStatsMarshaller))]
    public unsafe partial struct ProcessMemoryStats
    {
        public static ProcessMemoryStats Default => new ProcessMemoryStats();

    }
}

