//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Render/Assets/Geometry/Model.h
//-------------------------------------------------------------------------
#pragma warning disable CS0108
#pragma warning disable CS8603
#pragma warning disable CS8625
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using SE.Interop;

namespace SE
{
    /// <summary>
    /// &lt;summary&gt; Model asset that contains model object made of meshes which can rendered on the GPU. &lt;/summary&gt;
    /// </summary>
    [NativeMarshalling(typeof(ModelMarshaller))]
    public unsafe partial class Model : SE.ModelBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Model"/>.
        /// </summary>
        public Model() : base()
        {
        }


        [CustomMarshaller(typeof(Model), MarshalMode.ManagedToUnmanagedIn, typeof(ModelMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Model), MarshalMode.ElementIn, typeof(ModelMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Model), MarshalMode.ManagedToUnmanagedOut, typeof(ModelMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Model), MarshalMode.UnmanagedToManagedIn, typeof(ModelMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Model), MarshalMode.ElementOut, typeof(ModelMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Model), MarshalMode.ManagedToUnmanagedRef, typeof(ModelMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(Model), MarshalMode.UnmanagedToManagedRef, typeof(ModelMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(Model), MarshalMode.ElementRef, typeof(ModelMarshaller))]
        internal struct ModelMarshaller
        {
            #pragma warning disable 1591
            public static class NativeToManaged
            {
                public static Model ConvertToManaged(IntPtr unmanaged) => Unsafe.As<Model>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(Model managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public static class ManagedToNative
            {
                public static Model ConvertToManaged(IntPtr unmanaged) => Unsafe.As<Model>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(Model managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public struct Bidirectional
            {
                ManagedHandleMarshaller.Bidirectional marsh;
                public void FromManaged(Model managed) => marsh.FromManaged(managed);
                public IntPtr ToUnmanaged() => marsh.ToUnmanaged();
                public void FromUnmanaged(IntPtr unmanaged) => marsh.FromUnmanaged(unmanaged);
                public Model ToManaged() => Unsafe.As<Model>(marsh.ToManaged());
                public void Free() => marsh.Free();
            }
            internal static Model ConvertToManaged(IntPtr unmanaged) => Unsafe.As<Model>(ManagedHandleMarshaller.ConvertToManaged(unmanaged));
            internal static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.Free(unmanaged);
            internal static Model ToManaged(IntPtr managed) => Unsafe.As<Model>(ManagedHandleMarshaller.ToManaged(managed));
            internal static IntPtr ToNative(Model managed) => ManagedHandleMarshaller.ToNative(managed);
        #pragma warning restore 1591
        }

    }
}

