//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Level/Actors/ModelInstance.h
//-------------------------------------------------------------------------
#pragma warning disable CS0108
#pragma warning disable CS8603
#pragma warning disable CS8625
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using SE.Interop;

namespace SE
{
    [NativeMarshalling(typeof(ModelInstanceMarshaller))]
    public unsafe abstract partial class ModelInstance : SE.RenderActor
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ModelInstance"/>.
        /// </summary>
        protected ModelInstance() : base()
        {
        }


        [CustomMarshaller(typeof(ModelInstance), MarshalMode.ManagedToUnmanagedIn, typeof(ModelInstanceMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(ModelInstance), MarshalMode.ElementIn, typeof(ModelInstanceMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(ModelInstance), MarshalMode.ManagedToUnmanagedOut, typeof(ModelInstanceMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(ModelInstance), MarshalMode.UnmanagedToManagedIn, typeof(ModelInstanceMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(ModelInstance), MarshalMode.ElementOut, typeof(ModelInstanceMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(ModelInstance), MarshalMode.ManagedToUnmanagedRef, typeof(ModelInstanceMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(ModelInstance), MarshalMode.UnmanagedToManagedRef, typeof(ModelInstanceMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(ModelInstance), MarshalMode.ElementRef, typeof(ModelInstanceMarshaller))]
        internal struct ModelInstanceMarshaller
        {
            #pragma warning disable 1591
            public static class NativeToManaged
            {
                public static ModelInstance ConvertToManaged(IntPtr unmanaged) => Unsafe.As<ModelInstance>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(ModelInstance managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public static class ManagedToNative
            {
                public static ModelInstance ConvertToManaged(IntPtr unmanaged) => Unsafe.As<ModelInstance>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(ModelInstance managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public struct Bidirectional
            {
                ManagedHandleMarshaller.Bidirectional marsh;
                public void FromManaged(ModelInstance managed) => marsh.FromManaged(managed);
                public IntPtr ToUnmanaged() => marsh.ToUnmanaged();
                public void FromUnmanaged(IntPtr unmanaged) => marsh.FromUnmanaged(unmanaged);
                public ModelInstance ToManaged() => Unsafe.As<ModelInstance>(marsh.ToManaged());
                public void Free() => marsh.Free();
            }
            internal static ModelInstance ConvertToManaged(IntPtr unmanaged) => Unsafe.As<ModelInstance>(ManagedHandleMarshaller.ConvertToManaged(unmanaged));
            internal static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.Free(unmanaged);
            internal static ModelInstance ToManaged(IntPtr managed) => Unsafe.As<ModelInstance>(ManagedHandleMarshaller.ToManaged(managed));
            internal static IntPtr ToNative(ModelInstance managed) => ManagedHandleMarshaller.ToNative(managed);
        #pragma warning restore 1591
        }

    }
}

