//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - native type placeholders.
//-------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;

namespace SE
{
    public unsafe partial class Window
    {
        internal IntPtr __unmanagedPtr = IntPtr.Zero;
        internal static Window FromUnmanaged(IntPtr nativePtr) => nativePtr != IntPtr.Zero ? new Window { __unmanagedPtr = nativePtr } : null;
    }
}

namespace SE
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct ScreenOrientationType
    {
    }
}

namespace SE
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct Rectangle
    {
    }
}

namespace SE
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct Matrix
    {
    }
}

namespace SE
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct Viewport
    {
    }
}

namespace SE
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct Matrix3x3
    {
    }
}

namespace SE
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct Color
    {
    }
}

namespace SE
{
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct AssetRef<T>
    {
    }
}

