#pragma once
//*************************************************************************
// This is an auto-generated file - DO NOT edit
//*************************************************************************
#include "E:/EngineProject/SolarEngine/Src/Engine//Runtime/Core/Platform/Base/PlatformBase.h"
#include "Runtime/Core/Scripting/ManagedCLR/CLRUtils.h"
#include "Runtime/Core/Scripting/ScriptingObject.h"
#include "Runtime/Core/Scripting/Internal/InternalCalls.h"
#include "Runtime/Core/Scripting/ScriptingType.h"

//-------------------------------------------------------------------------
// Bindings
//-------------------------------------------------------------------------
//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Core/Platform/Base/PlatformBase.h
//-------------------------------------------------------------------------
#include "E:/EngineProject/SolarEngine/Src/Engine//Runtime/Core/Platform/Base/PlatformBase.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/BindingsInterop.h"
#include "Runtime/Core/Scripting/ManagedCLR/CLRUtils.h"
#include "Runtime/Core/Scripting/Scripting.h"
#include "Runtime/Core/Scripting/Binary/ManagedBinaryModule.h"
#include "Runtime/Core/Scripting/ScriptingObject.h"
#include "Runtime/Core/Scripting/Internal/InternalCalls.h"
#include "Runtime/Core/Scripting/ScriptingType.h"

namespace SE
{
class PlatformBaseInternal
{
public:
#if defined(_MSC_VER)
    DLLEXPORT static float CustomDpiScale_Get()
#else
    static float CustomDpiScale_Get()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_CustomDpiScale_Get)
#endif
        return ::SE::Platform::CustomDpiScale;
    }
#if defined(_MSC_VER)
    DLLEXPORT static void CustomDpiScale_Set(float value)
#else
    static void CustomDpiScale_Set(float value)
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_CustomDpiScale_Set)
#endif
        ::SE::Platform::CustomDpiScale = value;
    }
#if defined(_MSC_VER)
    DLLEXPORT static ::SE::PlatformType GetPlatformType()
#else
    static ::SE::PlatformType GetPlatformType()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_GetPlatformType)
#endif
        return ::SE::Platform::GetPlatformType();
    }
#if defined(_MSC_VER)
    DLLEXPORT static bool Is64BitApp()
#else
    static bool Is64BitApp()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_Is64BitApp)
#endif
        return ::SE::Platform::Is64BitApp();
    }
#if defined(_MSC_VER)
    DLLEXPORT static bool Is64BitPlatform()
#else
    static bool Is64BitPlatform()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_Is64BitPlatform)
#endif
        return ::SE::Platform::Is64BitPlatform();
    }
#if defined(_MSC_VER)
    DLLEXPORT static ::SE::CPUInfo GetCPUInfo()
#else
    static ::SE::CPUInfo GetCPUInfo()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_GetCPUInfo)
#endif
        return ::SE::Platform::GetCPUInfo();
    }
#if defined(_MSC_VER)
    DLLEXPORT static int32 GetCacheLineSize()
#else
    static int32 GetCacheLineSize()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_GetCacheLineSize)
#endif
        return ::SE::Platform::GetCacheLineSize();
    }
#if defined(_MSC_VER)
    DLLEXPORT static ::SE::MemoryStats GetMemoryStats()
#else
    static ::SE::MemoryStats GetMemoryStats()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_GetMemoryStats)
#endif
        return ::SE::Platform::GetMemoryStats();
    }
#if defined(_MSC_VER)
    DLLEXPORT static ::SE::ProcessMemoryStats GetProcessMemoryStats()
#else
    static ::SE::ProcessMemoryStats GetProcessMemoryStats()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_GetProcessMemoryStats)
#endif
        return ::SE::Platform::GetProcessMemoryStats();
    }
#if defined(_MSC_VER)
    DLLEXPORT static uint64 GetCurrentProcessId()
#else
    static uint64 GetCurrentProcessId()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_GetCurrentProcessId)
#endif
        return ::SE::Platform::GetCurrentProcessId();
    }
#if defined(_MSC_VER)
    DLLEXPORT static uint64 GetCurrentThreadID()
#else
    static uint64 GetCurrentThreadID()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_GetCurrentThreadID)
#endif
        return ::SE::Platform::GetCurrentThreadID();
    }
#if defined(_MSC_VER)
    DLLEXPORT static double GetTimeSeconds()
#else
    static double GetTimeSeconds()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_GetTimeSeconds)
#endif
        return ::SE::Platform::GetTimeSeconds();
    }
#if defined(_MSC_VER)
    DLLEXPORT static uint64 GetTimeCycles()
#else
    static uint64 GetTimeCycles()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_GetTimeCycles)
#endif
        return ::SE::Platform::GetTimeCycles();
    }
#if defined(_MSC_VER)
    DLLEXPORT static uint64 GetClockFrequency()
#else
    static uint64 GetClockFrequency()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_GetClockFrequency)
#endif
        return ::SE::Platform::GetClockFrequency();
    }
#if defined(_MSC_VER)
    DLLEXPORT static int32 GetDpi()
#else
    static int32 GetDpi()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_GetDpi)
#endif
        return ::SE::Platform::GetDpi();
    }
#if defined(_MSC_VER)
    DLLEXPORT static float GetDpiScale()
#else
    static float GetDpiScale()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_GetDpiScale)
#endif
        return ::SE::Platform::GetDpiScale();
    }
#if defined(_MSC_VER)
    DLLEXPORT static ::SE::ScreenOrientationType GetScreenOrientationType()
#else
    static ::SE::ScreenOrientationType GetScreenOrientationType()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_GetScreenOrientationType)
#endif
        return ::SE::Platform::GetScreenOrientationType();
    }
#if defined(_MSC_VER)
    DLLEXPORT static CLRString* GetUserLocaleName()
#else
    static CLRString* GetUserLocaleName()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_GetUserLocaleName)
#endif
        return CLRUtils::ToString(::SE::Platform::GetUserLocaleName());
    }
#if defined(_MSC_VER)
    DLLEXPORT static CLRString* GetComputerName()
#else
    static CLRString* GetComputerName()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_GetComputerName)
#endif
        return CLRUtils::ToString(::SE::Platform::GetComputerName());
    }
#if defined(_MSC_VER)
    DLLEXPORT static CLRString* GetUserName()
#else
    static CLRString* GetUserName()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_GetUserName)
#endif
        return CLRUtils::ToString(::SE::Platform::GetUserName());
    }
#if defined(_MSC_VER)
    DLLEXPORT static bool GetHasFocus()
#else
    static bool GetHasFocus()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_GetHasFocus)
#endif
        return ::SE::Platform::GetHasFocus();
    }
#if defined(_MSC_VER)
    DLLEXPORT static ::SE::Float2 GetMousePosition()
#else
    static ::SE::Float2 GetMousePosition()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_GetMousePosition)
#endif
        return ::SE::Platform::GetMousePosition();
    }
#if defined(_MSC_VER)
    DLLEXPORT static void SetMousePosition(::SE::Float2* position)
#else
    static void SetMousePosition(::SE::Float2* position)
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_SetMousePosition)
#endif
        ::SE::Platform::SetMousePosition(*position);
    }
#if defined(_MSC_VER)
    DLLEXPORT static ::SE::Rectangle GetMonitorBounds(::SE::Float2* screenPos)
#else
    static ::SE::Rectangle GetMonitorBounds(::SE::Float2* screenPos)
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_GetMonitorBounds)
#endif
        return ::SE::Platform::GetMonitorBounds(*screenPos);
    }
#if defined(_MSC_VER)
    DLLEXPORT static ::SE::Float2 GetDesktopSize()
#else
    static ::SE::Float2 GetDesktopSize()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_GetDesktopSize)
#endif
        return ::SE::Platform::GetDesktopSize();
    }
#if defined(_MSC_VER)
    DLLEXPORT static ::SE::Rectangle GetVirtualDesktopBounds()
#else
    static ::SE::Rectangle GetVirtualDesktopBounds()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_GetVirtualDesktopBounds)
#endif
        return ::SE::Platform::GetVirtualDesktopBounds();
    }
#if defined(_MSC_VER)
    DLLEXPORT static ::SE::Float2 GetVirtualDesktopSize()
#else
    static ::SE::Float2 GetVirtualDesktopSize()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_GetVirtualDesktopSize)
#endif
        return ::SE::Platform::GetVirtualDesktopSize();
    }
#if defined(_MSC_VER)
    DLLEXPORT static CLRString* GetMainDirectory()
#else
    static CLRString* GetMainDirectory()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_GetMainDirectory)
#endif
        return CLRUtils::ToString(::SE::Platform::GetMainDirectory());
    }
#if defined(_MSC_VER)
    DLLEXPORT static CLRString* GetExecutableFilePath()
#else
    static CLRString* GetExecutableFilePath()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_GetExecutableFilePath)
#endif
        return CLRUtils::ToString(::SE::Platform::GetExecutableFilePath());
    }
#if defined(_MSC_VER)
    DLLEXPORT static ::SE::UID GetUniqueDeviceId()
#else
    static ::SE::UID GetUniqueDeviceId()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_GetUniqueDeviceId)
#endif
        return ::SE::Platform::GetUniqueDeviceId();
    }
#if defined(_MSC_VER)
    DLLEXPORT static CLRString* GetWorkingDirectory()
#else
    static CLRString* GetWorkingDirectory()
#endif
    {
#if defined(_MSC_VER)
        MSVC_FUNC_EXPORT(PlatformBase_GetWorkingDirectory)
#endif
        return CLRUtils::ToString(::SE::Platform::GetWorkingDirectory());
    }
    static void InitRuntime()
    {
    }
};

ScriptingTypeInitializer PlatformBase::TypeInitializer(
    (BinaryModule*)GetBinaryModuleSERuntime(),
    StringAnsiView("SE.Platform", ARRAY_SIZE("SE.Platform") - 1),
    sizeof(::SE::PlatformBase),
    &PlatformBaseInternal::InitRuntime,
    &ScriptingType::DefaultSpawn, 
    nullptr,
    nullptr,
    nullptr
);

// Plain-C exports
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(float) PlatformBase_CustomDpiScale_Get()
{
    return PlatformBaseInternal::CustomDpiScale_Get();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(void) PlatformBase_CustomDpiScale_Set(float value)
{
    PlatformBaseInternal::CustomDpiScale_Set(value);
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(::SE::PlatformType) PlatformBase_GetPlatformType()
{
    return PlatformBaseInternal::GetPlatformType();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(bool) PlatformBase_Is64BitApp()
{
    return PlatformBaseInternal::Is64BitApp();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(bool) PlatformBase_Is64BitPlatform()
{
    return PlatformBaseInternal::Is64BitPlatform();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(::SE::CPUInfo) PlatformBase_GetCPUInfo()
{
    return PlatformBaseInternal::GetCPUInfo();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(int32) PlatformBase_GetCacheLineSize()
{
    return PlatformBaseInternal::GetCacheLineSize();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(::SE::MemoryStats) PlatformBase_GetMemoryStats()
{
    return PlatformBaseInternal::GetMemoryStats();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(::SE::ProcessMemoryStats) PlatformBase_GetProcessMemoryStats()
{
    return PlatformBaseInternal::GetProcessMemoryStats();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(uint64) PlatformBase_GetCurrentProcessId()
{
    return PlatformBaseInternal::GetCurrentProcessId();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(uint64) PlatformBase_GetCurrentThreadID()
{
    return PlatformBaseInternal::GetCurrentThreadID();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(double) PlatformBase_GetTimeSeconds()
{
    return PlatformBaseInternal::GetTimeSeconds();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(uint64) PlatformBase_GetTimeCycles()
{
    return PlatformBaseInternal::GetTimeCycles();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(uint64) PlatformBase_GetClockFrequency()
{
    return PlatformBaseInternal::GetClockFrequency();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(int32) PlatformBase_GetDpi()
{
    return PlatformBaseInternal::GetDpi();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(float) PlatformBase_GetDpiScale()
{
    return PlatformBaseInternal::GetDpiScale();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(::SE::ScreenOrientationType) PlatformBase_GetScreenOrientationType()
{
    return PlatformBaseInternal::GetScreenOrientationType();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(CLRString*) PlatformBase_GetUserLocaleName()
{
    return PlatformBaseInternal::GetUserLocaleName();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(CLRString*) PlatformBase_GetComputerName()
{
    return PlatformBaseInternal::GetComputerName();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(CLRString*) PlatformBase_GetUserName()
{
    return PlatformBaseInternal::GetUserName();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(bool) PlatformBase_GetHasFocus()
{
    return PlatformBaseInternal::GetHasFocus();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(::SE::Float2) PlatformBase_GetMousePosition()
{
    return PlatformBaseInternal::GetMousePosition();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(void) PlatformBase_SetMousePosition(::SE::Float2* position)
{
    PlatformBaseInternal::SetMousePosition(position);
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(::SE::Rectangle) PlatformBase_GetMonitorBounds(::SE::Float2* screenPos)
{
    return PlatformBaseInternal::GetMonitorBounds(screenPos);
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(::SE::Float2) PlatformBase_GetDesktopSize()
{
    return PlatformBaseInternal::GetDesktopSize();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(::SE::Rectangle) PlatformBase_GetVirtualDesktopBounds()
{
    return PlatformBaseInternal::GetVirtualDesktopBounds();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(::SE::Float2) PlatformBase_GetVirtualDesktopSize()
{
    return PlatformBaseInternal::GetVirtualDesktopSize();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(CLRString*) PlatformBase_GetMainDirectory()
{
    return PlatformBaseInternal::GetMainDirectory();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(CLRString*) PlatformBase_GetExecutableFilePath()
{
    return PlatformBaseInternal::GetExecutableFilePath();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(::SE::UID) PlatformBase_GetUniqueDeviceId()
{
    return PlatformBaseInternal::GetUniqueDeviceId();
}
#endif
#if !defined(_MSC_VER)
DEFINE_INTERNAL_CALL(CLRString*) PlatformBase_GetWorkingDirectory()
{
    return PlatformBaseInternal::GetWorkingDirectory();
}
#endif
}

