//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Level/Actors/PointLight.h
//-------------------------------------------------------------------------
#pragma warning disable CS0108
#pragma warning disable CS8603
#pragma warning disable CS8625
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using SE.Interop;

namespace SE
{
    /// <summary>
    /// &lt;summary&gt; Point light emits light from point in all directions. &lt;/summary&gt;
    /// </summary>
    [NativeMarshalling(typeof(PointLightMarshaller))]
    public unsafe partial class PointLight : SE.LightWithShadow
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PointLight"/>.
        /// </summary>
        public PointLight() : base()
        {
        }


        [LibraryImport("SERuntime", EntryPoint = "PointLight_SourceRadius_Get", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial float Internal_SourceRadius_Get(IntPtr __obj);

        [LibraryImport("SERuntime", EntryPoint = "PointLight_SourceRadius_Set", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_SourceRadius_Set(IntPtr __obj, float value);

        /// <summary>
        /// &lt;summary&gt; Light source bulb radius &lt;/summary&gt; SE_PROPERTY(API(Attributes="EditorOrder(2), DefaultValue(0.0f), EditorDisplay(\"Light"), Limit(0, 1000, 0.01f)"))
        /// </summary>
        public float SourceRadius
        {
            get { return Internal_SourceRadius_Get(__unmanagedPtr); }
            set { Internal_SourceRadius_Set(__unmanagedPtr, value); }
        }

        [LibraryImport("SERuntime", EntryPoint = "PointLight_SourceLength_Get", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial float Internal_SourceLength_Get(IntPtr __obj);

        [LibraryImport("SERuntime", EntryPoint = "PointLight_SourceLength_Set", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_SourceLength_Set(IntPtr __obj, float value);

        /// <summary>
        /// &lt;summary&gt; Light source bulb length &lt;/summary&gt; SE_PROPERTY(API(Attributes="EditorOrder(3), DefaultValue(0.0f), EditorDisplay(\"Light"), Limit(0, 1000, 0.01f)"))
        /// </summary>
        public float SourceLength
        {
            get { return Internal_SourceLength_Get(__unmanagedPtr); }
            set { Internal_SourceLength_Set(__unmanagedPtr, value); }
        }

        [LibraryImport("SERuntime", EntryPoint = "PointLight_UseInverseSquaredFalloff_Get", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static partial bool Internal_UseInverseSquaredFalloff_Get(IntPtr __obj);

        [LibraryImport("SERuntime", EntryPoint = "PointLight_UseInverseSquaredFalloff_Set", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_UseInverseSquaredFalloff_Set(IntPtr __obj, [MarshalAs(UnmanagedType.U1)] bool value);

        /// <summary>
        /// &lt;summary&gt; Whether to use physically based inverse squared distance falloff, where Radius is only clamping the light's contribution. &lt;/summary&gt; SE_PROPERTY(API(Attributes = "EditorOrder(13), DefaultValue(false), EditorDisplay(\"Light")"))
        /// </summary>
        public bool UseInverseSquaredFalloff
        {
            get { return Internal_UseInverseSquaredFalloff_Get(__unmanagedPtr); }
            set { Internal_UseInverseSquaredFalloff_Set(__unmanagedPtr, value); }
        }

        [LibraryImport("SERuntime", EntryPoint = "PointLight_FallOffExponent_Get", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial float Internal_FallOffExponent_Get(IntPtr __obj);

        [LibraryImport("SERuntime", EntryPoint = "PointLight_FallOffExponent_Set", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_FallOffExponent_Set(IntPtr __obj, float value);

        /// <summary>
        /// &lt;summary&gt; Controls the radial falloff of light when UseInverseSquaredFalloff is disabled. &lt;/summary&gt; SE_PROPERTY(API(Attributes="EditorOrder(14), DefaultValue(8.0f), EditorDisplay(\"Light"), Limit(2, 16, 0.01f), VisibleIf(nameof(UseInverseSquaredFalloff), true)"))
        /// </summary>
        public float FallOffExponent
        {
            get { return Internal_FallOffExponent_Get(__unmanagedPtr); }
            set { Internal_FallOffExponent_Set(__unmanagedPtr, value); }
        }

        [CustomMarshaller(typeof(PointLight), MarshalMode.ManagedToUnmanagedIn, typeof(PointLightMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(PointLight), MarshalMode.ElementIn, typeof(PointLightMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(PointLight), MarshalMode.ManagedToUnmanagedOut, typeof(PointLightMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(PointLight), MarshalMode.UnmanagedToManagedIn, typeof(PointLightMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(PointLight), MarshalMode.ElementOut, typeof(PointLightMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(PointLight), MarshalMode.ManagedToUnmanagedRef, typeof(PointLightMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(PointLight), MarshalMode.UnmanagedToManagedRef, typeof(PointLightMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(PointLight), MarshalMode.ElementRef, typeof(PointLightMarshaller))]
        internal struct PointLightMarshaller
        {
            #pragma warning disable 1591
            public static class NativeToManaged
            {
                public static PointLight ConvertToManaged(IntPtr unmanaged) => Unsafe.As<PointLight>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(PointLight managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public static class ManagedToNative
            {
                public static PointLight ConvertToManaged(IntPtr unmanaged) => Unsafe.As<PointLight>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(PointLight managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public struct Bidirectional
            {
                ManagedHandleMarshaller.Bidirectional marsh;
                public void FromManaged(PointLight managed) => marsh.FromManaged(managed);
                public IntPtr ToUnmanaged() => marsh.ToUnmanaged();
                public void FromUnmanaged(IntPtr unmanaged) => marsh.FromUnmanaged(unmanaged);
                public PointLight ToManaged() => Unsafe.As<PointLight>(marsh.ToManaged());
                public void Free() => marsh.Free();
            }
            internal static PointLight ConvertToManaged(IntPtr unmanaged) => Unsafe.As<PointLight>(ManagedHandleMarshaller.ConvertToManaged(unmanaged));
            internal static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.Free(unmanaged);
            internal static PointLight ToManaged(IntPtr managed) => Unsafe.As<PointLight>(ManagedHandleMarshaller.ToManaged(managed));
            internal static IntPtr ToNative(PointLight managed) => ManagedHandleMarshaller.ToNative(managed);
        #pragma warning restore 1591
        }

    }
}

