//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Level/SceneObject.h
//-------------------------------------------------------------------------
#pragma warning disable CS0108
#pragma warning disable CS8603
#pragma warning disable CS8625
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using SE.Interop;

namespace SE
{
    [NativeMarshalling(typeof(SceneObjectMarshaller))]
    public unsafe abstract partial class SceneObject : SE.Object
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SceneObject"/>.
        /// </summary>
        protected SceneObject() : base()
        {
        }


        [LibraryImport("SERuntime", EntryPoint = "SceneObject_GetParent", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial IntPtr Internal_GetParent(IntPtr __obj);

        /// <summary>
        /// &lt;summary&gt; Gets the parent actor (or null if object has no parent). &lt;/summary&gt;
        /// </summary>
        public SE.Actor Parent
        {
            get { return (SE.Actor)SE.Interop.ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(Internal_GetParent(__unmanagedPtr)); }
        }

        [LibraryImport("SERuntime", EntryPoint = "SceneObject_GetSceneObjectId", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_GetSceneObjectId(IntPtr __obj, out System.Guid __resultAsRef);

        /// <summary>
        /// &lt;summary&gt; Gets the scene object ID. &lt;/summary&gt; &lt;returns&gt;The scene object ID.&lt;/returns&gt;
        /// </summary>
        public System.Guid SceneObjectId
        {
            get { System.Guid __resultAsRef; Internal_GetSceneObjectId(__unmanagedPtr, out __resultAsRef); return __resultAsRef; }
        }

        [CustomMarshaller(typeof(SceneObject), MarshalMode.ManagedToUnmanagedIn, typeof(SceneObjectMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(SceneObject), MarshalMode.ElementIn, typeof(SceneObjectMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(SceneObject), MarshalMode.ManagedToUnmanagedOut, typeof(SceneObjectMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(SceneObject), MarshalMode.UnmanagedToManagedIn, typeof(SceneObjectMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(SceneObject), MarshalMode.ElementOut, typeof(SceneObjectMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(SceneObject), MarshalMode.ManagedToUnmanagedRef, typeof(SceneObjectMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(SceneObject), MarshalMode.UnmanagedToManagedRef, typeof(SceneObjectMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(SceneObject), MarshalMode.ElementRef, typeof(SceneObjectMarshaller))]
        internal struct SceneObjectMarshaller
        {
            #pragma warning disable 1591
            public static class NativeToManaged
            {
                public static SceneObject ConvertToManaged(IntPtr unmanaged) => Unsafe.As<SceneObject>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(SceneObject managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public static class ManagedToNative
            {
                public static SceneObject ConvertToManaged(IntPtr unmanaged) => Unsafe.As<SceneObject>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(SceneObject managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public struct Bidirectional
            {
                ManagedHandleMarshaller.Bidirectional marsh;
                public void FromManaged(SceneObject managed) => marsh.FromManaged(managed);
                public IntPtr ToUnmanaged() => marsh.ToUnmanaged();
                public void FromUnmanaged(IntPtr unmanaged) => marsh.FromUnmanaged(unmanaged);
                public SceneObject ToManaged() => Unsafe.As<SceneObject>(marsh.ToManaged());
                public void Free() => marsh.Free();
            }
            internal static SceneObject ConvertToManaged(IntPtr unmanaged) => Unsafe.As<SceneObject>(ManagedHandleMarshaller.ConvertToManaged(unmanaged));
            internal static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.Free(unmanaged);
            internal static SceneObject ToManaged(IntPtr managed) => Unsafe.As<SceneObject>(ManagedHandleMarshaller.ToManaged(managed));
            internal static IntPtr ToNative(SceneObject managed) => ManagedHandleMarshaller.ToNative(managed);
        #pragma warning restore 1591
        }

    }
}

