//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Render/2D/SpriteAtlas.h
//-------------------------------------------------------------------------
#pragma warning disable CS0108
#pragma warning disable CS8603
#pragma warning disable CS8625
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using SE.Interop;

namespace SE
{
        [CustomMarshaller(typeof(Sprite), MarshalMode.ManagedToUnmanagedIn, typeof(SpriteMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Sprite), MarshalMode.UnmanagedToManagedOut, typeof(SpriteMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Sprite), MarshalMode.ElementIn, typeof(SpriteMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Sprite), MarshalMode.ManagedToUnmanagedOut, typeof(SpriteMarshaller.NativeToManaged))]
        [CustomMarshaller(typeof(Sprite), MarshalMode.UnmanagedToManagedIn, typeof(SpriteMarshaller.NativeToManaged))]
        [CustomMarshaller(typeof(Sprite), MarshalMode.ElementOut, typeof(SpriteMarshaller.NativeToManaged))]
        [CustomMarshaller(typeof(Sprite), MarshalMode.ManagedToUnmanagedRef, typeof(SpriteMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(Sprite), MarshalMode.UnmanagedToManagedRef, typeof(SpriteMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(Sprite), MarshalMode.ElementRef, typeof(SpriteMarshaller))]
        internal static partial class SpriteMarshaller
        {
            [StructLayout(LayoutKind.Sequential)]
            internal unsafe struct SpriteInternal
            {
                public SE.Rectangle Area;
                public IntPtr Name;
            }

            public static Sprite ConvertToManaged(SpriteInternal unmanaged)
            {
                var result = new Sprite();
                result.Area = unmanaged.Area;
                result.Name = Interop.StringMarshaller.ToManaged(unmanaged.Name);
                return result;
            }

            public static SpriteInternal ConvertToUnmanaged(Sprite managed)
            {
                var result = new SpriteInternal();
                result.Area = managed.Area;
                result.Name = Interop.StringMarshaller.ManagedToNative.ConvertToUnmanaged(managed.Name);
                return result;
            }

            public static void Free(SpriteInternal unmanaged) { }

            public static class ManagedToNative
            {
                public static Sprite ConvertToManaged(SpriteInternal unmanaged) => SpriteMarshaller.ConvertToManaged(unmanaged);
                public static SpriteInternal ConvertToUnmanaged(Sprite managed) => SpriteMarshaller.ConvertToUnmanaged(managed);
                public static void Free(SpriteInternal unmanaged) => SpriteMarshaller.Free(unmanaged);
            }

            public static class NativeToManaged
            {
                public static Sprite ConvertToManaged(SpriteInternal unmanaged) => SpriteMarshaller.ConvertToManaged(unmanaged);
                public static SpriteInternal ConvertToUnmanaged(Sprite managed) => SpriteMarshaller.ConvertToUnmanaged(managed);
                public static void Free(SpriteInternal unmanaged) => SpriteMarshaller.Free(unmanaged);
            }

            public ref struct Bidirectional
            {
                private SpriteInternal unmanaged;
                private Sprite managed;

                public Bidirectional(Sprite managed)
                {
                    this.managed = managed;
                    unmanaged = SpriteMarshaller.ConvertToUnmanaged(managed);
                }

                public void FromManaged(Sprite managed) => this.managed = managed;
                public SpriteInternal ToUnmanaged() { unmanaged = SpriteMarshaller.ConvertToUnmanaged(managed); return unmanaged; }
                public void FromUnmanaged(SpriteInternal unmanaged) => this.unmanaged = unmanaged;
                public Sprite ToManaged()
                {
                    managed = SpriteMarshaller.ConvertToManaged(unmanaged);
                    return managed;
                }
                public void Free() { }
            }
        }

    /// <summary>
    /// &lt;summary&gt; Contains information about single atlas slot with sprite texture. &lt;/summary&gt;
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    [NativeMarshalling(typeof(SpriteMarshaller))]
    public unsafe partial struct Sprite
    {
        public SE.Rectangle Area;

        [MarshalAs(UnmanagedType.LPUTF8Str)]
        public string Name;

        public static Sprite Default => new Sprite();

    }
}

namespace SE
{
        [CustomMarshaller(typeof(SpriteHandle), MarshalMode.ManagedToUnmanagedIn, typeof(SpriteHandleMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(SpriteHandle), MarshalMode.UnmanagedToManagedOut, typeof(SpriteHandleMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(SpriteHandle), MarshalMode.ElementIn, typeof(SpriteHandleMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(SpriteHandle), MarshalMode.ManagedToUnmanagedOut, typeof(SpriteHandleMarshaller.NativeToManaged))]
        [CustomMarshaller(typeof(SpriteHandle), MarshalMode.UnmanagedToManagedIn, typeof(SpriteHandleMarshaller.NativeToManaged))]
        [CustomMarshaller(typeof(SpriteHandle), MarshalMode.ElementOut, typeof(SpriteHandleMarshaller.NativeToManaged))]
        [CustomMarshaller(typeof(SpriteHandle), MarshalMode.ManagedToUnmanagedRef, typeof(SpriteHandleMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(SpriteHandle), MarshalMode.UnmanagedToManagedRef, typeof(SpriteHandleMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(SpriteHandle), MarshalMode.ElementRef, typeof(SpriteHandleMarshaller))]
        internal static partial class SpriteHandleMarshaller
        {
            [StructLayout(LayoutKind.Sequential)]
            internal unsafe struct SpriteHandleInternal
            {
                public SE.AssetRef<SE.SpriteAtlas> Atlas;
                public int Index;
            }

            public static SpriteHandle ConvertToManaged(SpriteHandleInternal unmanaged)
            {
                var result = new SpriteHandle();
                result.Atlas = unmanaged.Atlas;
                result.Index = unmanaged.Index;
                return result;
            }

            public static SpriteHandleInternal ConvertToUnmanaged(SpriteHandle managed)
            {
                var result = new SpriteHandleInternal();
                result.Atlas = managed.Atlas;
                result.Index = managed.Index;
                return result;
            }

            public static void Free(SpriteHandleInternal unmanaged) { }

            public static class ManagedToNative
            {
                public static SpriteHandle ConvertToManaged(SpriteHandleInternal unmanaged) => SpriteHandleMarshaller.ConvertToManaged(unmanaged);
                public static SpriteHandleInternal ConvertToUnmanaged(SpriteHandle managed) => SpriteHandleMarshaller.ConvertToUnmanaged(managed);
                public static void Free(SpriteHandleInternal unmanaged) => SpriteHandleMarshaller.Free(unmanaged);
            }

            public static class NativeToManaged
            {
                public static SpriteHandle ConvertToManaged(SpriteHandleInternal unmanaged) => SpriteHandleMarshaller.ConvertToManaged(unmanaged);
                public static SpriteHandleInternal ConvertToUnmanaged(SpriteHandle managed) => SpriteHandleMarshaller.ConvertToUnmanaged(managed);
                public static void Free(SpriteHandleInternal unmanaged) => SpriteHandleMarshaller.Free(unmanaged);
            }

            public ref struct Bidirectional
            {
                private SpriteHandleInternal unmanaged;
                private SpriteHandle managed;

                public Bidirectional(SpriteHandle managed)
                {
                    this.managed = managed;
                    unmanaged = SpriteHandleMarshaller.ConvertToUnmanaged(managed);
                }

                public void FromManaged(SpriteHandle managed) => this.managed = managed;
                public SpriteHandleInternal ToUnmanaged() { unmanaged = SpriteHandleMarshaller.ConvertToUnmanaged(managed); return unmanaged; }
                public void FromUnmanaged(SpriteHandleInternal unmanaged) => this.unmanaged = unmanaged;
                public SpriteHandle ToManaged()
                {
                    managed = SpriteHandleMarshaller.ConvertToManaged(unmanaged);
                    return managed;
                }
                public void Free() { }
            }
        }

    /// <summary>
    /// &lt;summary&gt; Handle to sprite atlas slot with a single sprite texture. &lt;/summary&gt;
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    [NativeMarshalling(typeof(SpriteHandleMarshaller))]
    public unsafe partial struct SpriteHandle : SE.ISerializable
    {
        /// <summary>
        /// &lt;summary&gt; The parent atlas. &lt;/summary&gt;
        /// </summary>
        public SE.AssetRef<SE.SpriteAtlas> Atlas;

        /// <summary>
        /// &lt;summary&gt; The atlas sprites array index. &lt;/summary&gt;
        /// </summary>
        public int Index;

        public static SpriteHandle Default => new SpriteHandle();

    }
}

namespace SE
{
    /// <summary>
    /// &lt;summary&gt; Sprite atlas asset that contains collection of sprites combined into a single texture. &lt;/summary&gt; &lt;seealso cref="TextureBase" /&gt;
    /// </summary>
    [NativeMarshalling(typeof(SpriteAtlasMarshaller))]
    public unsafe partial class SpriteAtlas : SE.TextureBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SpriteAtlas"/>.
        /// </summary>
        public SpriteAtlas() : base()
        {
        }


        [LibraryImport("SERuntime", EntryPoint = "SpriteAtlas_GetSpritesCount", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial int Internal_GetSpritesCount(IntPtr __obj);

        [LibraryImport("SERuntime", EntryPoint = "SpriteAtlas_GetSprite", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_GetSprite(IntPtr __obj, int index, [MarshalUsing(typeof(SE.SpriteMarshaller))] out SE.Sprite __resultAsRef);

        [LibraryImport("SERuntime", EntryPoint = "SpriteAtlas_GetSpriteArea", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_GetSpriteArea(IntPtr __obj, int index, ref SE.Rectangle result);

        [LibraryImport("SERuntime", EntryPoint = "SpriteAtlas_SetSprite", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_SetSprite(IntPtr __obj, int index, [MarshalUsing(typeof(SE.SpriteMarshaller))] ref SE.Sprite value);

        [LibraryImport("SERuntime", EntryPoint = "SpriteAtlas_FindSprite", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_FindSprite(IntPtr __obj, string name, [MarshalUsing(typeof(SE.SpriteHandleMarshaller))] out SE.SpriteHandle __resultAsRef);

        [LibraryImport("SERuntime", EntryPoint = "SpriteAtlas_AddSprite", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_AddSprite(IntPtr __obj, [MarshalUsing(typeof(SE.SpriteMarshaller))] ref SE.Sprite sprite, [MarshalUsing(typeof(SE.SpriteHandleMarshaller))] out SE.SpriteHandle __resultAsRef);

        [LibraryImport("SERuntime", EntryPoint = "SpriteAtlas_RemoveSprite", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_RemoveSprite(IntPtr __obj, int index);

        /// <summary>
        /// &lt;summary&gt; Gets the sprites count. &lt;/summary&gt;
        /// </summary>
        public int  GetSpritesCount()
        {
            return Internal_GetSpritesCount(__unmanagedPtr);
        }

        /// <summary>
        /// &lt;summary&gt; Gets the sprite data. &lt;/summary&gt; &lt;param name="index"&gt;The index.&lt;/param&gt; &lt;returns&gt;The sprite data.&lt;/returns&gt;
        /// </summary>
        public SE.Sprite  GetSprite(int index)
        {
            SE.Sprite __resultAsRef;
            Internal_GetSprite(__unmanagedPtr, index, out __resultAsRef);
            return __resultAsRef;
        }

        /// <summary>
        /// &lt;summary&gt; Gets the sprite area. &lt;/summary&gt; &lt;param name="index"&gt;The index.&lt;/param&gt; &lt;param name="result"&gt;The output sprite area.&lt;/param&gt; &lt;returns&gt;The sprite data.&lt;/returns&gt;
        /// </summary>
        public void  GetSpriteArea(int index, ref SE.Rectangle result)
        {
            Internal_GetSpriteArea(__unmanagedPtr, index, ref result);
        }

        /// <summary>
        /// &lt;summary&gt; Sets the sprite data. &lt;/summary&gt; &lt;param name="index"&gt;The index.&lt;/param&gt; &lt;param name="value"&gt;The sprite data.&lt;/param&gt;
        /// </summary>
        public void  SetSprite(int index, ref SE.Sprite value)
        {
            Internal_SetSprite(__unmanagedPtr, index, ref value);
        }

        /// <summary>
        /// &lt;summary&gt; Finds the sprite by the name. &lt;/summary&gt; &lt;param name="name"&gt;The name.&lt;/param&gt; &lt;returns&gt;The sprite handle.&lt;/returns&gt;
        /// </summary>
        public SE.SpriteHandle  FindSprite(string name)
        {
            SE.SpriteHandle __resultAsRef;
            Internal_FindSprite(__unmanagedPtr, name, out __resultAsRef);
            return __resultAsRef;
        }

        /// <summary>
        /// &lt;summary&gt; Adds the sprite. &lt;/summary&gt; &lt;param name="sprite"&gt;The sprite.&lt;/param&gt; &lt;returns&gt;The sprite handle.&lt;/returns&gt;
        /// </summary>
        public SE.SpriteHandle  AddSprite(ref SE.Sprite sprite)
        {
            SE.SpriteHandle __resultAsRef;
            Internal_AddSprite(__unmanagedPtr, ref sprite, out __resultAsRef);
            return __resultAsRef;
        }

        /// <summary>
        /// &lt;summary&gt; Removes the sprite. &lt;/summary&gt; &lt;param name="index"&gt;The sprite index.&lt;/param&gt;
        /// </summary>
        public void  RemoveSprite(int index)
        {
            Internal_RemoveSprite(__unmanagedPtr, index);
        }

        [LibraryImport("SERuntime", EntryPoint = "SpriteAtlas_Sprites_Get", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        [return: MarshalUsing(typeof(SE.Interop.ArrayMarshaller<,>), CountElementName = nameof(__returnCount))]
        internal static partial SE.Sprite[] Internal_Sprites_Get(IntPtr __obj, out int __returnCount);

        [LibraryImport("SERuntime", EntryPoint = "SpriteAtlas_Sprites_Set", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Interop.StringMarshaller))]
        internal static partial void Internal_Sprites_Set(IntPtr __obj, [MarshalUsing(typeof(SE.Interop.ArrayMarshaller<,>), CountElementName = nameof(__valueCount)), In] SE.Sprite[] value, int __valueCount);

        /// <summary>
        /// &lt;summary&gt; List with all tiles in the sprite atlas. &lt;/summary&gt;
        /// </summary>
        public SE.Sprite[] Sprites
        {
            get { return Internal_Sprites_Get(__unmanagedPtr, out _); }
            set { Internal_Sprites_Set(__unmanagedPtr, value, value != null ? value.Length : 0); }
        }

        [CustomMarshaller(typeof(SpriteAtlas), MarshalMode.ManagedToUnmanagedIn, typeof(SpriteAtlasMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(SpriteAtlas), MarshalMode.ElementIn, typeof(SpriteAtlasMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(SpriteAtlas), MarshalMode.ManagedToUnmanagedOut, typeof(SpriteAtlasMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(SpriteAtlas), MarshalMode.UnmanagedToManagedIn, typeof(SpriteAtlasMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(SpriteAtlas), MarshalMode.ElementOut, typeof(SpriteAtlasMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(SpriteAtlas), MarshalMode.ManagedToUnmanagedRef, typeof(SpriteAtlasMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(SpriteAtlas), MarshalMode.UnmanagedToManagedRef, typeof(SpriteAtlasMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(SpriteAtlas), MarshalMode.ElementRef, typeof(SpriteAtlasMarshaller))]
        internal struct SpriteAtlasMarshaller
        {
            #pragma warning disable 1591
            public static class NativeToManaged
            {
                public static SpriteAtlas ConvertToManaged(IntPtr unmanaged) => Unsafe.As<SpriteAtlas>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(SpriteAtlas managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public static class ManagedToNative
            {
                public static SpriteAtlas ConvertToManaged(IntPtr unmanaged) => Unsafe.As<SpriteAtlas>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(SpriteAtlas managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public struct Bidirectional
            {
                ManagedHandleMarshaller.Bidirectional marsh;
                public void FromManaged(SpriteAtlas managed) => marsh.FromManaged(managed);
                public IntPtr ToUnmanaged() => marsh.ToUnmanaged();
                public void FromUnmanaged(IntPtr unmanaged) => marsh.FromUnmanaged(unmanaged);
                public SpriteAtlas ToManaged() => Unsafe.As<SpriteAtlas>(marsh.ToManaged());
                public void Free() => marsh.Free();
            }
            internal static SpriteAtlas ConvertToManaged(IntPtr unmanaged) => Unsafe.As<SpriteAtlas>(ManagedHandleMarshaller.ConvertToManaged(unmanaged));
            internal static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.Free(unmanaged);
            internal static SpriteAtlas ToManaged(IntPtr managed) => Unsafe.As<SpriteAtlas>(ManagedHandleMarshaller.ToManaged(managed));
            internal static IntPtr ToNative(SpriteAtlas managed) => ManagedHandleMarshaller.ToNative(managed);
        #pragma warning restore 1591
        }

    }
}

