//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Runtime/Render/Assets/Texture/Texture.h
//-------------------------------------------------------------------------
#pragma warning disable CS0108
#pragma warning disable CS8603
#pragma warning disable CS8625
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using SE.Interop;

namespace SE
{
    [NativeMarshalling(typeof(TextureMarshaller))]
    public unsafe partial class Texture : SE.TextureBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Texture"/>.
        /// </summary>
        public Texture() : base()
        {
        }


        [CustomMarshaller(typeof(Texture), MarshalMode.ManagedToUnmanagedIn, typeof(TextureMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Texture), MarshalMode.ElementIn, typeof(TextureMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Texture), MarshalMode.ManagedToUnmanagedOut, typeof(TextureMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Texture), MarshalMode.UnmanagedToManagedIn, typeof(TextureMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Texture), MarshalMode.ElementOut, typeof(TextureMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Texture), MarshalMode.ManagedToUnmanagedRef, typeof(TextureMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(Texture), MarshalMode.UnmanagedToManagedRef, typeof(TextureMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(Texture), MarshalMode.ElementRef, typeof(TextureMarshaller))]
        internal struct TextureMarshaller
        {
            #pragma warning disable 1591
            public static class NativeToManaged
            {
                public static Texture ConvertToManaged(IntPtr unmanaged) => Unsafe.As<Texture>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(Texture managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public static class ManagedToNative
            {
                public static Texture ConvertToManaged(IntPtr unmanaged) => Unsafe.As<Texture>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(Texture managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public struct Bidirectional
            {
                ManagedHandleMarshaller.Bidirectional marsh;
                public void FromManaged(Texture managed) => marsh.FromManaged(managed);
                public IntPtr ToUnmanaged() => marsh.ToUnmanaged();
                public void FromUnmanaged(IntPtr unmanaged) => marsh.FromUnmanaged(unmanaged);
                public Texture ToManaged() => Unsafe.As<Texture>(marsh.ToManaged());
                public void Free() => marsh.Free();
            }
            internal static Texture ConvertToManaged(IntPtr unmanaged) => Unsafe.As<Texture>(ManagedHandleMarshaller.ConvertToManaged(unmanaged));
            internal static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.Free(unmanaged);
            internal static Texture ToManaged(IntPtr managed) => Unsafe.As<Texture>(ManagedHandleMarshaller.ToManaged(managed));
            internal static IntPtr ToNative(Texture managed) => ManagedHandleMarshaller.ToNative(managed);
        #pragma warning restore 1591
        }

    }
}

