
#include "AssetsCache.h"
#include "Core/Logging/Logging.h"
#include "Core/Types/TimeSpan.h"
#include "Core/Types/Stopwatch.h"
#include "Core/Types/Collections/Dictionary.h"
#include "Core/Platform/FileSystem.h"
#include "Core/Serialization/FileWriteStream.h"
#include "Core/Serialization/FileReadStream.h"
#include "Core/Profiler/ProfilerCPU.h"
#include "Core/Thread/Threading.h"
#include "Runtime/Resource/Storage/AssetStorages.h"
#include "Runtime/Resource/Storage/JsonStorageProxy.h"
#include "Runtime/EngineContext.h"
//#include "FlaxEngine.Gen.h"

namespace SE
{
	int32 AssetsCache::Size() const
	{
		m_Locker.Lock();
		const int32 result = m_Registry.Count();
		m_Locker.Unlock();
		return result;
	}

	void AssetsCache::Init()
	{
		Entry e;
		int32 count;
		Stopwatch stopwatch;
#if SE_EDITOR
		m_Path = EngineContext::ProjectCacheFolder / SE_TEXT("AssetsCache.dat");
#else
		m_Path = EngineContext::ProjectContentFolder / SE_TEXT("AssetsCache.dat");
#endif
		LOG_INFO("Resource", "Loading Asset Cache {0}...", m_Path);

		// Check if assets registry exists
		if (!FileSystem::FileExists(m_Path))
		{
			m_IsDirty = true;
			LOG_WARNING("Resource", "Cannot find assets cache file");
			return;
		}

		// Open file
		FileReadStream* stream = FileReadStream::Open(m_Path);

		// Load version
		int32 version;
		stream->ReadInt32(&version);
/*		if (version != FLAXENGINE_VERSION_BUILD)
		{
			LOG_WARNING("Resource", "Corrupted or not supported Asset Cache file. Version: {0}", version);
			return;
		}*/

		// Load paths
		String enginePath, projectPath;
		stream->ReadString(&enginePath, -410);
		stream->ReadString(&projectPath, -410);

		// Flags
		EnumFlags<AssetsCacheFlags> flags;
		stream->ReadInt32((int32*)&flags);

		// Check if other workspace instance used this cache
		if (flags.IsFlag(AssetsCacheFlags::RelativePaths) && enginePath != EngineContext::StartupFolder)
		{
			LOG_WARNING("Resource", "Assets cache generated by the different {1} installation in \'{0}\'", enginePath, SE_TEXT("engine"));
			return;
		}
		if (flags.IsFlag(AssetsCacheFlags::RelativePaths) && projectPath != EngineContext::ProjectFolder)
		{
			LOG_WARNING("Resource", "Assets cache generated by the different {1} installation in \'{0}\'", projectPath, SE_TEXT("project"));
			return;
		}

		Threading::ScopeLock lock(m_Locker);
		m_IsDirty = false;

		// Load elements count
		stream->ReadInt32(&count);
		m_Registry.Clear();
		m_Registry.EnsureCapacity(count);

		// Load data
		int32 rejectedCount = 0;
		for (int32 i = 0; i < count; i++)
		{
			stream->Read(e.Info.id);
			String typeString;
			stream->ReadString(&typeString);
			e.Info.typeID = TypeID(typeString);
			stream->ReadString(&e.Info.path, i);
#if ENABLE_ASSETS_DISCOVERY
			stream->Read(e.FileModified);
#else
			DateTime tmp1;
			stream->Read(tmp1);
#endif

			if (flags.IsFlag(AssetsCacheFlags::RelativePaths) && e.Info.path.HasChars())
			{
				// Convert to absolute path
				e.Info.path = EngineContext::StartupFolder / e.Info.path;
			}

			// Use only valid entries
			if (IsEntryValid(e))
				m_Registry.Add(e.Info.id, e);
			else
				rejectedCount++;
		}

		// Paths mapping
		stream->ReadInt32(&count);
		m_PathsMapping.Clear();
		m_PathsMapping.EnsureCapacity(count);
		for (int32 i = 0; i < count; i++)
		{
			UID id;
			stream->Read(id);
			String mappedPath;
			stream->ReadString(&mappedPath, i + 73);

			if (flags.IsFlag(AssetsCacheFlags::RelativePaths) && mappedPath.HasChars())
			{
				// Convert to absolute path
				mappedPath = EngineContext::StartupFolder / mappedPath;
			}

			m_PathsMapping.Add(mappedPath, id);
		}

		// Check errors
		const bool hasError = stream->HasError();
		Delete<FileReadStream>(stream);

		if (hasError)
		{
			m_IsDirty = true;
			m_Registry.Clear();
			LOG_WARNING("Resource", "Asset Cache file has an error. Removing it.");
			if (!FileSystem::DeleteFile(m_Path))
			{
				LOG_ERROR("Resource", "Cannot delete registry file after reading error.");
			}
		}

		stopwatch.Stop();
		LOG_INFO("Resource", "Asset Cache loaded {0} entries in {1}ms ({2} rejected)", m_Registry.Count(), stopwatch.GetMilliseconds(), rejectedCount);
	}

	bool AssetsCache::Save()
	{
		// Registry can be saved only in editor
#if SE_EDITOR
		// Check if registry hasn't been edited
		if (!m_IsDirty && FileSystem::FileExists(m_Path))
		{
			return false;
		}
	
		Threading::ScopeLock lock(m_Locker);
	
		if (!Save(m_Path, m_Registry, m_PathsMapping))
		{
			return false;
		}

		m_IsDirty = false;
#endif
		return true;
	}

	bool AssetsCache::Save(const StringView& outputPath, const RegistryDict& entries, const PathsMappingDict& pathsMapping, const AssetsCacheFlags flags)
	{
		PROFILE_CPU();

		LOG_INFO("Resource", "Saving assets cache to \'{0}\', entries: {1}", outputPath, entries.Count());

		// Open file
		auto stream = FileWriteStream::Open(outputPath);
		if (stream == nullptr)
		{
			return false;
		}

		// Version
//		stream->WriteInt32(FLAXENGINE_VERSION_BUILD);

		// Paths
		stream->WriteString(EngineContext::StartupFolder, -410);
		stream->WriteString(EngineContext::ProjectFolder, -410);

		// Flags
		stream->WriteInt32((int32)flags);

		// Items count
		stream->WriteInt32(entries.Count());

		// Data
		int32 index = 0;
		for (auto i = entries.begin(); i.IsNotEnd(); ++i)
		{
			auto& e = i->Value;
			stream->Write(e.Info.id);
			stream->WriteString(e.Info.typeID.ToString());
			stream->WriteString(e.Info.path, index);
#if ENABLE_ASSETS_DISCOVERY
			stream->Write(e.FileModified);
#else
			stream->WriteInt64(0);
#endif
			index++;
		}

		// Paths mapping
		index = 0;
		stream->WriteInt32(pathsMapping.Count());
		for (auto i = pathsMapping.begin(); i.IsNotEnd(); ++i)
		{
			stream->Write(i->Value);
			stream->WriteString(i->Key, index + 73);
			index++;
		}

		// Cleanup
		stream->Flush();
		Delete(stream);

		return true;
	}

	const String& AssetsCache::GetEditorAssetPath(const UID& id) const
	{
		Threading::ScopeLock lock(m_Locker);
#if SE_EDITOR
		auto e = m_Registry.TryGet(id);
    	return e ? e->Info.path : String::Empty;
#else
		for (auto& e : m_PathsMapping)
		{
			if (e.Value == id)
				return e.Key;
		}
		return String::Empty;
#endif
	}

	bool AssetsCache::FindAsset(const StringView& path, AssetInfo& info)
	{
		PROFILE_CPU();

		bool result = false;

		Threading::ScopeLock lock(m_Locker);

		// Check if asset has direct mapping to id (used for some cooked assets)
		UID id;
		if (m_PathsMapping.TryGet(path, id))
		{
			return FindAsset(id, info);
		}
#if !SE_EDITOR
		if (FileSystem::IsRelative(path))
		{
			// Additional check if user provides path relative to the project folder (eg. Content/SomeAssets/MyFile.json)
			const String absolutePath = Globals::ProjectFolder / *path;
			if (_pathsMapping.TryGet(absolutePath, id))
			{
				return FindAsset(id, info);
			}
		}
#endif

		// Find asset in registry
		for (auto i = m_Registry.begin(); i.IsNotEnd(); ++i)
		{
			auto& e = i->Value;
			if (e.Info.path == path)
			{
				if (!IsEntryValid(e))
				{
					LOG_WARNING("Resource", "Missing file from registry: \'{0}\':{1}:{2}", e.Info.path, e.Info.id, e.Info.typeID);
					m_Registry.Remove(i);
				}
				else
				{
					// Found
					result = true;
					info = e.Info;
				}

				break;
			}
		}

		return result;
	}

	bool AssetsCache::FindAsset(const UID& id, AssetInfo& info)
	{
		PROFILE_CPU();
		bool result = false;
		Threading::ScopeLock lock(m_Locker);
		auto e = m_Registry.TryGet(id);
		if (e != nullptr)
		{
			if (!IsEntryValid(*e))
			{
				LOG_WARNING("Resource", "Missing file from registry: \'{0}\':{1}:{2}", e->Info.path, e->Info.id, e->Info.typeID);
				m_Registry.Remove(id);
			}
			else
			{
				// Found
				result = true;
				info = e->Info;
			}
		}
		return result;
	}

	void AssetsCache::GetAll(List<UID>& result) const
	{
		PROFILE_CPU();
		Threading::ScopeLock lock(m_Locker);
		m_Registry.GetKeys(result);
	}

	void AssetsCache::GetAllByTypeName(const TypeID typeID, List<UID>& result) const
	{
		PROFILE_CPU();
		Threading::ScopeLock lock(m_Locker);
		for (auto i = m_Registry.begin(); i.IsNotEnd(); ++i)
		{
			if (i->Value.Info.typeID == typeID)
				result.Add(i->Key);
		}
	}

	void AssetsCache::RegisterAssets(Storage* storage)
	{
		PROFILE_CPU();

		ENGINE_ASSERT(storage != nullptr);

		// Get all entries
		List<Storage::Entry> entries;
		storage->GetEntries(entries);
		ENGINE_ASSERT(entries.HasItems());

		Threading::ScopeLock lock(m_Locker);
		auto storagePath = storage->GetPath();

		// Remove all old entries from that location
		for (auto i = m_Registry.begin(); i.IsNotEnd(); ++i)
		{
			if (i->Value.Info.path == storagePath)
			{
				m_Registry.Remove(i);
			}
		}

		// Find asset IDs collisions
		AssetInfo info;
		List<int32> duplicatedEntries;
		for (int32 i = 0; i < entries.Count(); i++)
		{
			auto& e = entries[i];
			ENGINE_ASSERT(e.ID.IsValid());

			// Check if storage contains ID which has been already registered
			if (FindAsset(e.ID, info))
			{
#if PLATFORM_WINDOWS
				// On Windows - if you start your project using a shortcut/VS commandline -project, and using a upper/lower drive letter, it could the cache (case doesn't matter on OS)
				if (StringUtils::CompareIgnoreCase(storagePath.GetText(), info.path.GetText()) != 0)
				{
					LOG_WARNING("Resource", "Founded duplicated asset \'{0}\'. Locations: \'{1}\' and \'{2}\'", e.ID, storagePath, info.path);
					duplicatedEntries.Add(i);
				}
				else
				{
					// Remove from registry so we can add it again later with the original ID, so we don't loose relations
					for (auto j = m_Registry.begin(); j.IsNotEnd(); ++j)
					{
						if (StringUtils::CompareIgnoreCase(j->Value.Info.path.GetText(), storagePath.GetText()) == 0)
							m_Registry.Remove(j);
					}
				}
#else
				LOG_WARNING("Resource", "Founded duplicated asset \'{0}\'. Locations: \'{1}\' and \'{2}\'", e.ID, storagePath, info.Path);
            	duplicatedEntries.Add(i);
#endif
			}
		}

		// Check if need to resolve any collisions
		if (duplicatedEntries.HasItems())
		{
			// Check if cannot resolve collision for that container (it must allow to write to)
			// TODO: we could support packages as well but don't have to do it now, maybe in future
			if (storage->AllowDataModifications() == false)
			{
				LOG_ERROR("Resource", "Cannot register \'{0}\'. Founded duplicated asset at \'{1}\' but storage container doesn't allow data modifications.", storagePath, info.path);
				return;
			}

			// Process all duplicated entries
			for (int32 i = 0; i < duplicatedEntries.Count(); i++)
			{
				auto& e = entries[duplicatedEntries[i]];
#if SE_EDITOR
				if (!storage->ChangeAssetID(e, UID::New()))
#endif
				{
					LOG_ERROR("Resource", "Cannot modify duplicated asset ID {2} from \'{0}\'. Founded duplicated asset at \'{1}\'.", storagePath, info.path, e.ID);
					return;
				}
			}
		}

		// Register all entries
		for (int32 i = 0; i < entries.Count(); i++)
		{
			auto& e = entries[i];

			// Send info
			LOG_INFO("Resource", "Register asset {0}:{1} \'{2}\'", e.ID, e.Type, storagePath);

			// Add new asset entry
			m_Registry.Add(e.ID, Entry(e.ID, e.Type, storagePath));
		}

		// Mark registry as draft
		m_IsDirty = true;
	}

	void AssetsCache::RegisterAsset(const AssetHeader& header, const StringView& path)
	{
		RegisterAsset(header.ID, header.TypeID, path);
	}

	void AssetsCache::RegisterAssets(const StorageReference& storage)
	{
		RegisterAssets(storage.Get());
	}

	void AssetsCache::RegisterAsset(const UID& id, const TypeID& typeName, const StringView& path)
	{
		PROFILE_CPU();
		Threading::ScopeLock lock(m_Locker);

		// Check if asset has been already added to the registry
		bool isMissing = true;
		for (auto i = m_Registry.begin(); i.IsNotEnd(); ++i)
		{
			auto& e = i->Value;

			if (e.Info.id == id)
			{
				if (e.Info.path != path)
				{
					e.Info.path = path;
					m_IsDirty = true;
				}
				if (e.Info.typeID != typeName)
				{
					e.Info.typeID = typeName;
					m_IsDirty = true;
				}
				isMissing = false;
				break;
			}

			if (e.Info.path == path)
			{
				if (e.Info.id != id)
				{
					e.Info.path = path;
					m_IsDirty = true;
				}
				if (e.Info.typeID != typeName)
				{
					e.Info.typeID = typeName;
					m_IsDirty = true;
				}
				isMissing = false;
				break;
			}
		}

		if (isMissing)
		{
			LOG_INFO("Resource", "Register asset {0}:{1} \'{2}\'", id, typeName, path);
			m_Registry.Add(id, Entry(id, typeName, path));
			m_IsDirty = true;
		}
	}

	bool AssetsCache::DeleteAsset(const StringView& path, AssetInfo* info)
	{
		bool result = false;
		m_Locker.Lock();

		for (auto i = m_Registry.begin(); i.IsNotEnd(); ++i)
		{
			if (i->Value.Info.path == path)
			{
				if (info)
					*info = i->Value.Info;
				m_Registry.Remove(i);
				m_IsDirty = true;
				result = true;
				break;
			}
		}

		m_Locker.Unlock();
		return result;
	}

	bool AssetsCache::DeleteAsset(const UID& id, AssetInfo* info)
	{
		bool result = false;
		m_Locker.Lock();

		const auto e = m_Registry.TryGet(id);
		if (e != nullptr)
		{
			if (info)
				*info = e->Info;
			m_Registry.Remove(id);
			m_IsDirty = true;
			result = true;
		}

		m_Locker.Unlock();
		return result;
	}

	bool AssetsCache::RenameAsset(const StringView& oldPath, const StringView& newPath)
	{
		bool result = false;
		m_Locker.Lock();

		for (auto i = m_Registry.begin(); i.IsNotEnd(); ++i)
		{
			if (i->Value.Info.path == oldPath)
			{
				i->Value.Info.path = newPath;
				m_IsDirty = true;
				result = true;
				break;
			}
		}

		m_Locker.Unlock();
		return result;
	}

	bool AssetsCache::IsEntryValid(Entry& e)
	{
#if ENABLE_ASSETS_DISCOVERY
		// Check if file exists
		if (FileSystem::FileExists(e.Info.path))
		{
			// Check if file hasn't been modified
			const auto fileModified = FileSystem::GetFileLastEditTime(e.Info.path);
			if (fileModified == e.FileModified)
				return true;

			const auto extension = FileSystem::GetExtension(e.Info.path).ToLower();

			// Check if it's a binary asset
			if (AssetStorages::IsStorageExtension(extension))
			{
				// Validate ID within storage container
				const auto storage = AssetStorages::GetStorage(e.Info.path);
				if (storage)
				{
					// Check if storage at given location contains that asset
					const bool isValid = storage->HasAsset(e.Info);

					// Update entry and mark cache as dirty
					e.FileModified = fileModified;
					m_IsDirty = true;

					return isValid;
				}
			}
			// Check for json resource
			else if (JsonStorageProxy::IsValidExtension(extension))
			{
				// Check Json storage layer
				UID jsonId;
				TypeID jsonTypeID;
				if (JsonStorageProxy::GetAssetInfo(e.Info.path, jsonId, jsonTypeID))
				{
					const bool isValid = e.Info.id == jsonId && e.Info.typeID == jsonTypeID;

					// Update entry and mark cache as dirty
					e.FileModified = fileModified;
					m_IsDirty = true;

					return isValid;
				}
			}
		}

		return false;
#else
		// In game we don't care about it because all cached asset entries are valid (precached)
		// Skip only entries with missing file
		return e.Info.Path.HasChars();
#endif
	}
}