
#include "API.h"
// 通过include AutoGenerated.cpp 将自动生成代码引入编译，当没有走预生成编译会报错
#include "_Generated/AutoGenerated.cpp"

#include "Runtime/Core/Scripting/Binary/NativeBinaryModule.h"

namespace SE
{
	BinaryModule* GetBinaryModuleSERuntime()
	{
		static NativeBinaryModule module("SERuntimeCSharp");
		return &module;
	}

#ifdef SE_EDITOR

	BinaryModule* GetBinaryModuleSEEditor()
	{
		static NativeBinaryModule module("SE.EditorCSharp");
		return &module;
	}
#endif

}
