//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Editor/EditorApp.h
//-------------------------------------------------------------------------
#pragma warning disable CS0108
#pragma warning disable CS8603
#pragma warning disable CS8625
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using SE.Interop;

namespace SE.Editor
{
    [NativeMarshalling(typeof(EditorMarshaller))]
    public unsafe partial class Editor : SE.Object
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Editor"/>.
        /// </summary>
        public Editor() : base()
        {
        }


        [CustomMarshaller(typeof(Editor), MarshalMode.ManagedToUnmanagedIn, typeof(EditorMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Editor), MarshalMode.ElementIn, typeof(EditorMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Editor), MarshalMode.ManagedToUnmanagedOut, typeof(EditorMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Editor), MarshalMode.UnmanagedToManagedIn, typeof(EditorMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Editor), MarshalMode.ElementOut, typeof(EditorMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(Editor), MarshalMode.ManagedToUnmanagedRef, typeof(EditorMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(Editor), MarshalMode.UnmanagedToManagedRef, typeof(EditorMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(Editor), MarshalMode.ElementRef, typeof(EditorMarshaller))]
        internal struct EditorMarshaller
        {
            #pragma warning disable 1591
            public static class NativeToManaged
            {
                public static Editor ConvertToManaged(IntPtr unmanaged) => Unsafe.As<Editor>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(Editor managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public static class ManagedToNative
            {
                public static Editor ConvertToManaged(IntPtr unmanaged) => Unsafe.As<Editor>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(Editor managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public struct Bidirectional
            {
                ManagedHandleMarshaller.Bidirectional marsh;
                public void FromManaged(Editor managed) => marsh.FromManaged(managed);
                public IntPtr ToUnmanaged() => marsh.ToUnmanaged();
                public void FromUnmanaged(IntPtr unmanaged) => marsh.FromUnmanaged(unmanaged);
                public Editor ToManaged() => Unsafe.As<Editor>(marsh.ToManaged());
                public void Free() => marsh.Free();
            }
            internal static Editor ConvertToManaged(IntPtr unmanaged) => Unsafe.As<Editor>(ManagedHandleMarshaller.ConvertToManaged(unmanaged));
            internal static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.Free(unmanaged);
            internal static Editor ToManaged(IntPtr managed) => Unsafe.As<Editor>(ManagedHandleMarshaller.ToManaged(managed));
            internal static IntPtr ToNative(Editor managed) => ManagedHandleMarshaller.ToNative(managed);
        #pragma warning restore 1591
        }

    }
}

