#pragma once
//*************************************************************************
// This is an auto-generated file - DO NOT edit
//*************************************************************************
#include "E:/EngineProject/SolarEngine/Src/Engine//Editor/EditorApp.h"
#include "Runtime/Core/Scripting/ManagedCLR/CLRUtils.h"
#include "Runtime/Core/Scripting/ScriptingObject.h"
#include "Runtime/Core/Scripting/Internal/InternalCalls.h"
#include "Runtime/Core/Scripting/ScriptingType.h"

//-------------------------------------------------------------------------
// Bindings
//-------------------------------------------------------------------------
//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Editor/EditorApp.h
//-------------------------------------------------------------------------
#include "E:/EngineProject/SolarEngine/Src/Engine//Editor/EditorApp.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/BindingsInterop.h"
#include "Runtime/Core/Scripting/ManagedCLR/CLRUtils.h"
#include "Runtime/Core/Scripting/Scripting.h"
#include "Runtime/Core/Scripting/Binary/ManagedBinaryModule.h"
#include "Runtime/Core/Scripting/ScriptingObject.h"
#include "Runtime/Core/Scripting/Internal/InternalCalls.h"
#include "Runtime/Core/Scripting/ScriptingType.h"

namespace SE::Editor
{
class ManagedEditorInternal
{
public:
    static void InitRuntime()
    {
    }
};

ScriptingTypeInitializer Editor::ManagedEditor::TypeInitializer(
    (BinaryModule*)GetBinaryModuleSEEditor(),
    StringAnsiView("SE.Editor.Editor", ARRAY_SIZE("SE.Editor.Editor") - 1),
    sizeof(::SE::Editor::ManagedEditor),
    &ManagedEditorInternal::InitRuntime,
    &ScriptingType::DefaultSpawn, 
    &::SE::ScriptingObject::TypeInitializer,
    nullptr,
    nullptr
);
}

