//-------------------------------------------------------------------------
// Auto-generated by BindingsGenerator - do not edit manually.
// Source: E:/EngineProject/SolarEngine/Src/Engine//Editor/Resource/Thumbnails/PreviewsCache.h
//-------------------------------------------------------------------------
#pragma warning disable CS0108
#pragma warning disable CS8603
#pragma warning disable CS8625
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using SE.Interop;

namespace SE.Editor
{
    /// <summary>
    /// &lt;/summary&gt;
    /// </summary>
    [NativeMarshalling(typeof(PreviewsCacheMarshaller))]
    public unsafe partial class PreviewsCache : SE.SpriteAtlas
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PreviewsCache"/>.
        /// </summary>
        public PreviewsCache() : base()
        {
        }


        [CustomMarshaller(typeof(PreviewsCache), MarshalMode.ManagedToUnmanagedIn, typeof(PreviewsCacheMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(PreviewsCache), MarshalMode.ElementIn, typeof(PreviewsCacheMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(PreviewsCache), MarshalMode.ManagedToUnmanagedOut, typeof(PreviewsCacheMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(PreviewsCache), MarshalMode.UnmanagedToManagedIn, typeof(PreviewsCacheMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(PreviewsCache), MarshalMode.ElementOut, typeof(PreviewsCacheMarshaller.ManagedToNative))]
        [CustomMarshaller(typeof(PreviewsCache), MarshalMode.ManagedToUnmanagedRef, typeof(PreviewsCacheMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(PreviewsCache), MarshalMode.UnmanagedToManagedRef, typeof(PreviewsCacheMarshaller.Bidirectional))]
        [CustomMarshaller(typeof(PreviewsCache), MarshalMode.ElementRef, typeof(PreviewsCacheMarshaller))]
        internal struct PreviewsCacheMarshaller
        {
            #pragma warning disable 1591
            public static class NativeToManaged
            {
                public static PreviewsCache ConvertToManaged(IntPtr unmanaged) => Unsafe.As<PreviewsCache>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(PreviewsCache managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public static class ManagedToNative
            {
                public static PreviewsCache ConvertToManaged(IntPtr unmanaged) => Unsafe.As<PreviewsCache>(ManagedHandleMarshaller.NativeToManaged.ConvertToManaged(unmanaged));
                public static IntPtr ConvertToUnmanaged(PreviewsCache managed) => ManagedHandleMarshaller.ManagedToNative.ConvertToUnmanaged(managed);
                public static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.NativeToManaged.Free(unmanaged);
            }
            public struct Bidirectional
            {
                ManagedHandleMarshaller.Bidirectional marsh;
                public void FromManaged(PreviewsCache managed) => marsh.FromManaged(managed);
                public IntPtr ToUnmanaged() => marsh.ToUnmanaged();
                public void FromUnmanaged(IntPtr unmanaged) => marsh.FromUnmanaged(unmanaged);
                public PreviewsCache ToManaged() => Unsafe.As<PreviewsCache>(marsh.ToManaged());
                public void Free() => marsh.Free();
            }
            internal static PreviewsCache ConvertToManaged(IntPtr unmanaged) => Unsafe.As<PreviewsCache>(ManagedHandleMarshaller.ConvertToManaged(unmanaged));
            internal static void Free(IntPtr unmanaged) => ManagedHandleMarshaller.Free(unmanaged);
            internal static PreviewsCache ToManaged(IntPtr managed) => Unsafe.As<PreviewsCache>(ManagedHandleMarshaller.ToManaged(managed));
            internal static IntPtr ToNative(PreviewsCache managed) => ManagedHandleMarshaller.ToNative(managed);
        #pragma warning restore 1591
        }

    }
}

