//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit";
//-------------------------------------------------------------------------
#include "Runtime/Core/TypeSystem/Types.h"
#include "Runtime/Core/TypeSystem/Info/TypeEnumInfo.h"
//-------------------------------------------------------------------------

//-------------------------------------------------------------------------
// Includes

#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Actor.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Asset.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/AssetContent.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/AssetInfo.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/AssetTask.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/BinaryAsset.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Button.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Camera.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/ContainerControl.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Control.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/CreateWindowSettings.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/CubeTexture.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/CustomEditorAliasAttribute.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/CustomEditorAttribute.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/DirectionalLight.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/DragData.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/EditorDisplayAttribute.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/EditorOrderAttribute.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Enums.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Font.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/FontAsset.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/FontTextureAtlas.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/GlobalSettings_GPU.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/GlobalSettings_Resource.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/GPUBuffer.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/GPUBufferDescription.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/GPUEnums.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/GPUPipelineState.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/GPUResource.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/GPUSampler.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/GPUSamplerDescription.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/GPUShader.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/GPUTexture.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/GPUTextureDescription.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/HeaderAttribute.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/HideInEditorAttribute.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/HScrollBar.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/IBrush.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Image.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/JsonAsset.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Label.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Light.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Material.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/MaterialBase.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/MaterialInstance.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Model.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/ModelBase.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/ModelInstance.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Object.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Panel.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/PixelFormat.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/PointLight.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/PostProcessSettings.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Prefab.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/ReadOnlyAttribute.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Render2D.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/RootControl.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Scene.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/SceneAsset.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/SceneObject.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/ScriptingObject.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/ScrollableControl.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/ScrollBar.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Settings.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Shader.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Sky.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/SpaceAttribute.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/SpriteAtlas.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/StaticModel.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/StreamingSettings.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/TestMeta.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/TextBox.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/TextBoxBase.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/TextLayoutOptions.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Texture.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/TextureBase.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/TextureBrush.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/TextureGroup.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/TextureUtils.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Tooltip.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/TypeMacro.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Types.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Variable.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Vector2.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Vector3.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/Vector4.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/VisibleIfAttribute.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/VScrollBar.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/WindowBase.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Runtime/_Generated/AutoGenerated/WindowRootControl.typeinfo.h"

//-------------------------------------------------------------------------
// Registration functions

namespace SE
{
    class SERuntimeTyper final : public ITyper
    {
    protected:
        void RegisterTypes() override
        {
            // Meta
        

            // Type
            Types::RegisterTypeID(StableID::Generate<::SE::Object>(), TypeID(SE_TEXT("SE::Object")));
            TTypeCompositeInfo<::SE::Object>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::ScriptingObject>(), TypeID(SE_TEXT("SE::ScriptingObject")));
            TTypeCompositeInfo<::SE::ScriptingObject>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::ManagedScriptingObject>(), TypeID(SE_TEXT("SE::ManagedScriptingObject")));
            TTypeCompositeInfo<::SE::ManagedScriptingObject>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::IBrush>(), TypeID(SE_TEXT("SE::IBrush")));
            TTypeCompositeInfo<::SE::IBrush>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::TextureBrush>(), TypeID(SE_TEXT("SE::TextureBrush")));
            TTypeCompositeInfo<::SE::TextureBrush>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Control>(), TypeID(SE_TEXT("SE::Control")));
            TTypeCompositeInfo<::SE::Control>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::ContainerControl>(), TypeID(SE_TEXT("SE::ContainerControl")));
            TTypeCompositeInfo<::SE::ContainerControl>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Button>(), TypeID(SE_TEXT("SE::Button")));
            TTypeCompositeInfo<::SE::Button>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Label>(), TypeID(SE_TEXT("SE::Label")));
            TTypeCompositeInfo<::SE::Label>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Image>(), TypeID(SE_TEXT("SE::Image")));
            TTypeCompositeInfo<::SE::Image>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::TextBoxBase>(), TypeID(SE_TEXT("SE::TextBoxBase")));
            TTypeCompositeInfo<::SE::TextBoxBase>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::TextBox>(), TypeID(SE_TEXT("SE::TextBox")));
            TTypeCompositeInfo<::SE::TextBox>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::ScrollableControl>(), TypeID(SE_TEXT("SE::ScrollableControl")));
            TTypeCompositeInfo<::SE::ScrollableControl>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Panel>(), TypeID(SE_TEXT("SE::Panel")));
            TTypeCompositeInfo<::SE::Panel>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::ScrollBar>(), TypeID(SE_TEXT("SE::ScrollBar")));
            TTypeCompositeInfo<::SE::ScrollBar>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::VScrollBar>(), TypeID(SE_TEXT("SE::VScrollBar")));
            TTypeCompositeInfo<::SE::VScrollBar>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::HScrollBar>(), TypeID(SE_TEXT("SE::HScrollBar")));
            TTypeCompositeInfo<::SE::HScrollBar>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::RootControl>(), TypeID(SE_TEXT("SE::RootControl")));
            TTypeCompositeInfo<::SE::RootControl>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::WindowRootControl>(), TypeID(SE_TEXT("SE::WindowRootControl")));
            TTypeCompositeInfo<::SE::WindowRootControl>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::DragData>(), TypeID(SE_TEXT("SE::DragData")));
            TTypeCompositeInfo<::SE::DragData>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::DragDataText>(), TypeID(SE_TEXT("SE::DragDataText")));
            TTypeCompositeInfo<::SE::DragDataText>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::DragDataFiles>(), TypeID(SE_TEXT("SE::DragDataFiles")));
            TTypeCompositeInfo<::SE::DragDataFiles>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Tooltip>(), TypeID(SE_TEXT("SE::Tooltip")));
            TTypeCompositeInfo<::SE::Tooltip>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::ISettings>(), TypeID(SE_TEXT("SE::ISettings")));
            TTypeCompositeInfo<::SE::ISettings>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::GlobalSettings>(), TypeID(SE_TEXT("SE::GlobalSettings")));
            TTypeCompositeInfo<::SE::GlobalSettings>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::ResourceGlobalSettings>(), TypeID(SE_TEXT("SE::ResourceGlobalSettings")));
            TTypeCompositeInfo<::SE::ResourceGlobalSettings>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Asset>(), TypeID(SE_TEXT("SE::Asset")));
            TTypeCompositeInfo<::SE::Asset>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::JsonAssetBase>(), TypeID(SE_TEXT("SE::JsonAssetBase")));
            TTypeCompositeInfo<::SE::JsonAssetBase>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::JsonAsset>(), TypeID(SE_TEXT("SE::JsonAsset")));
            TTypeCompositeInfo<::SE::JsonAsset>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::SceneAsset>(), TypeID(SE_TEXT("SE::SceneAsset")));
            TTypeCompositeInfo<::SE::SceneAsset>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::SceneObject>(), TypeID(SE_TEXT("SE::SceneObject")));
            TTypeCompositeInfo<::SE::SceneObject>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Actor>(), TypeID(SE_TEXT("SE::Actor")));
            TTypeCompositeInfo<::SE::Actor>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Scene>(), TypeID(SE_TEXT("SE::Scene")));
            TTypeCompositeInfo<::SE::Scene>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Camera>(), TypeID(SE_TEXT("SE::Camera")));
            TTypeCompositeInfo<::SE::Camera>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::RenderActor>(), TypeID(SE_TEXT("SE::RenderActor")));
            TTypeCompositeInfo<::SE::RenderActor>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::ModelInstance>(), TypeID(SE_TEXT("SE::ModelInstance")));
            TTypeCompositeInfo<::SE::ModelInstance>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::StaticModel>(), TypeID(SE_TEXT("SE::StaticModel")));
            TTypeCompositeInfo<::SE::StaticModel>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Light>(), TypeID(SE_TEXT("SE::Light")));
            TTypeCompositeInfo<::SE::Light>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::LightWithShadow>(), TypeID(SE_TEXT("SE::LightWithShadow")));
            TTypeCompositeInfo<::SE::LightWithShadow>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::DirectionalLight>(), TypeID(SE_TEXT("SE::DirectionalLight")));
            TTypeCompositeInfo<::SE::DirectionalLight>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::PointLight>(), TypeID(SE_TEXT("SE::PointLight")));
            TTypeCompositeInfo<::SE::PointLight>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Sky>(), TypeID(SE_TEXT("SE::Sky")));
            TTypeCompositeInfo<::SE::Sky>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Prefab>(), TypeID(SE_TEXT("SE::Prefab")));
            TTypeCompositeInfo<::SE::Prefab>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::GPUBufferDescription>(), TypeID(SE_TEXT("SE::GPUBufferDescription")));
            TTypeCompositeInfo<::SE::GPUBufferDescription>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::GPUGlobalSettings>(), TypeID(SE_TEXT("SE::GPUGlobalSettings")));
            TTypeCompositeInfo<::SE::GPUGlobalSettings>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::BinaryAsset>(), TypeID(SE_TEXT("SE::BinaryAsset")));
            TTypeCompositeInfo<::SE::BinaryAsset>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::ModelBase>(), TypeID(SE_TEXT("SE::ModelBase")));
            TTypeCompositeInfo<::SE::ModelBase>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Model>(), TypeID(SE_TEXT("SE::Model")));
            TTypeCompositeInfo<::SE::Model>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::TextureBase>(), TypeID(SE_TEXT("SE::TextureBase")));
            TTypeCompositeInfo<::SE::TextureBase>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Texture>(), TypeID(SE_TEXT("SE::Texture")));
            TTypeCompositeInfo<::SE::Texture>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::CubeTexture>(), TypeID(SE_TEXT("SE::CubeTexture")));
            TTypeCompositeInfo<::SE::CubeTexture>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::FontAsset>(), TypeID(SE_TEXT("SE::FontAsset")));
            TTypeCompositeInfo<::SE::FontAsset>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::FontTextureAtlas>(), TypeID(SE_TEXT("SE::FontTextureAtlas")));
            TTypeCompositeInfo<::SE::FontTextureAtlas>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::SpriteAtlas>(), TypeID(SE_TEXT("SE::SpriteAtlas")));
            TTypeCompositeInfo<::SE::SpriteAtlas>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::ToneMappingSettings>(), TypeID(SE_TEXT("SE::ToneMappingSettings")));
            TTypeCompositeInfo<::SE::ToneMappingSettings>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::ColorGradingSettings>(), TypeID(SE_TEXT("SE::ColorGradingSettings")));
            TTypeCompositeInfo<::SE::ColorGradingSettings>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::PostProcessSettings>(), TypeID(SE_TEXT("SE::PostProcessSettings")));
            TTypeCompositeInfo<::SE::PostProcessSettings>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::MaterialBase>(), TypeID(SE_TEXT("SE::MaterialBase")));
            TTypeCompositeInfo<::SE::MaterialBase>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Material>(), TypeID(SE_TEXT("SE::Material")));
            TTypeCompositeInfo<::SE::Material>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Shader>(), TypeID(SE_TEXT("SE::Shader")));
            TTypeCompositeInfo<::SE::Shader>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::MaterialInstance>(), TypeID(SE_TEXT("SE::MaterialInstance")));
            TTypeCompositeInfo<::SE::MaterialInstance>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::TextureGroup>(), TypeID(SE_TEXT("SE::TextureGroup")));
            TTypeCompositeInfo<::SE::TextureGroup>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::AssetInfo>(), TypeID(SE_TEXT("SE::AssetInfo")));
            TTypeCompositeInfo<::SE::AssetInfo>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::ContentStats>(), TypeID(SE_TEXT("SE::ContentStats")));
            TTypeCompositeInfo<::SE::ContentStats>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::TextureUtils::Options>(), TypeID(SE_TEXT("SE::TextureUtils::Options")));
            TTypeCompositeInfo<::SE::TextureUtils::Options>::RegisterType();

            // Enum
            Types::RegisterTypeID(StableID::Generate<::SE::CursorLockMode>(), TypeID(SE_TEXT("SE::CursorLockMode")));
            TTypeEnumInfo<::SE::CursorLockMode>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::MouseButton>(), TypeID(SE_TEXT("SE::MouseButton")));
            TTypeEnumInfo<::SE::MouseButton>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::GamepadAxis>(), TypeID(SE_TEXT("SE::GamepadAxis")));
            TTypeEnumInfo<::SE::GamepadAxis>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::GamepadButton>(), TypeID(SE_TEXT("SE::GamepadButton")));
            TTypeEnumInfo<::SE::GamepadButton>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::InputActionMode>(), TypeID(SE_TEXT("SE::InputActionMode")));
            TTypeEnumInfo<::SE::InputActionMode>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::InputActionState>(), TypeID(SE_TEXT("SE::InputActionState")));
            TTypeEnumInfo<::SE::InputActionState>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::InputGamepadIndex>(), TypeID(SE_TEXT("SE::InputGamepadIndex")));
            TTypeEnumInfo<::SE::InputGamepadIndex>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::InputAxisType>(), TypeID(SE_TEXT("SE::InputAxisType")));
            TTypeEnumInfo<::SE::InputAxisType>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::SkyType>(), TypeID(SE_TEXT("SE::SkyType")));
            TTypeEnumInfo<::SE::SkyType>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::GPUResourceUsage>(), TypeID(SE_TEXT("SE::GPUResourceUsage")));
            TTypeEnumInfo<::SE::GPUResourceUsage>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::GPUResourceMapMode>(), TypeID(SE_TEXT("SE::GPUResourceMapMode")));
            TTypeEnumInfo<::SE::GPUResourceMapMode>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::MSAALevel>(), TypeID(SE_TEXT("SE::MSAALevel")));
            TTypeEnumInfo<::SE::MSAALevel>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::GPURendererType>(), TypeID(SE_TEXT("SE::GPURendererType")));
            TTypeEnumInfo<::SE::GPURendererType>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::RHIShaderModel>(), TypeID(SE_TEXT("SE::RHIShaderModel")));
            TTypeEnumInfo<::SE::RHIShaderModel>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::RHIFilter>(), TypeID(SE_TEXT("SE::RHIFilter")));
            TTypeEnumInfo<::SE::RHIFilter>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::PixelFormat>(), TypeID(SE_TEXT("SE::PixelFormat")));
            TTypeEnumInfo<::SE::PixelFormat>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::GPUResourceType>(), TypeID(SE_TEXT("SE::GPUResourceType")));
            TTypeEnumInfo<::SE::GPUResourceType>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::StencilOperation>(), TypeID(SE_TEXT("SE::StencilOperation")));
            TTypeEnumInfo<::SE::StencilOperation>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::GPUSamplerFilter>(), TypeID(SE_TEXT("SE::GPUSamplerFilter")));
            TTypeEnumInfo<::SE::GPUSamplerFilter>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::GPUSamplerAddressMode>(), TypeID(SE_TEXT("SE::GPUSamplerAddressMode")));
            TTypeEnumInfo<::SE::GPUSamplerAddressMode>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::GPUSamplerCompareFunction>(), TypeID(SE_TEXT("SE::GPUSamplerCompareFunction")));
            TTypeEnumInfo<::SE::GPUSamplerCompareFunction>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::GPUSamplerBorderColor>(), TypeID(SE_TEXT("SE::GPUSamplerBorderColor")));
            TTypeEnumInfo<::SE::GPUSamplerBorderColor>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::TextureFormatType>(), TypeID(SE_TEXT("SE::TextureFormatType")));
            TTypeEnumInfo<::SE::TextureFormatType>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::TextureDimensions>(), TypeID(SE_TEXT("SE::TextureDimensions")));
            TTypeEnumInfo<::SE::TextureDimensions>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::ToneMappingMode>(), TypeID(SE_TEXT("SE::ToneMappingMode")));
            TTypeEnumInfo<::SE::ToneMappingMode>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::AssetTask::Result>(), TypeID(SE_TEXT("SE::AssetTask::Result")));
            TTypeEnumInfo<::SE::AssetTask::Result>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::CreateAssetResult>(), TypeID(SE_TEXT("SE::CreateAssetResult")));
            TTypeEnumInfo<::SE::CreateAssetResult>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Asset::LoadResult>(), TypeID(SE_TEXT("SE::Asset::LoadResult")));
            TTypeEnumInfo<::SE::Asset::LoadResult>::RegisterType();
        }

        void UnregisterTypes() override
        {
            // Meta
        

            // Type
            TTypeCompositeInfo<::SE::Object>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Object>(), TypeID(SE_TEXT("SE::Object")));
            TTypeCompositeInfo<::SE::ScriptingObject>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::ScriptingObject>(), TypeID(SE_TEXT("SE::ScriptingObject")));
            TTypeCompositeInfo<::SE::ManagedScriptingObject>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::ManagedScriptingObject>(), TypeID(SE_TEXT("SE::ManagedScriptingObject")));
            TTypeCompositeInfo<::SE::IBrush>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::IBrush>(), TypeID(SE_TEXT("SE::IBrush")));
            TTypeCompositeInfo<::SE::TextureBrush>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::TextureBrush>(), TypeID(SE_TEXT("SE::TextureBrush")));
            TTypeCompositeInfo<::SE::Control>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Control>(), TypeID(SE_TEXT("SE::Control")));
            TTypeCompositeInfo<::SE::ContainerControl>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::ContainerControl>(), TypeID(SE_TEXT("SE::ContainerControl")));
            TTypeCompositeInfo<::SE::Button>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Button>(), TypeID(SE_TEXT("SE::Button")));
            TTypeCompositeInfo<::SE::Label>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Label>(), TypeID(SE_TEXT("SE::Label")));
            TTypeCompositeInfo<::SE::Image>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Image>(), TypeID(SE_TEXT("SE::Image")));
            TTypeCompositeInfo<::SE::TextBoxBase>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::TextBoxBase>(), TypeID(SE_TEXT("SE::TextBoxBase")));
            TTypeCompositeInfo<::SE::TextBox>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::TextBox>(), TypeID(SE_TEXT("SE::TextBox")));
            TTypeCompositeInfo<::SE::ScrollableControl>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::ScrollableControl>(), TypeID(SE_TEXT("SE::ScrollableControl")));
            TTypeCompositeInfo<::SE::Panel>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Panel>(), TypeID(SE_TEXT("SE::Panel")));
            TTypeCompositeInfo<::SE::ScrollBar>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::ScrollBar>(), TypeID(SE_TEXT("SE::ScrollBar")));
            TTypeCompositeInfo<::SE::VScrollBar>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::VScrollBar>(), TypeID(SE_TEXT("SE::VScrollBar")));
            TTypeCompositeInfo<::SE::HScrollBar>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::HScrollBar>(), TypeID(SE_TEXT("SE::HScrollBar")));
            TTypeCompositeInfo<::SE::RootControl>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::RootControl>(), TypeID(SE_TEXT("SE::RootControl")));
            TTypeCompositeInfo<::SE::WindowRootControl>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::WindowRootControl>(), TypeID(SE_TEXT("SE::WindowRootControl")));
            TTypeCompositeInfo<::SE::DragData>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::DragData>(), TypeID(SE_TEXT("SE::DragData")));
            TTypeCompositeInfo<::SE::DragDataText>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::DragDataText>(), TypeID(SE_TEXT("SE::DragDataText")));
            TTypeCompositeInfo<::SE::DragDataFiles>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::DragDataFiles>(), TypeID(SE_TEXT("SE::DragDataFiles")));
            TTypeCompositeInfo<::SE::Tooltip>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Tooltip>(), TypeID(SE_TEXT("SE::Tooltip")));
            TTypeCompositeInfo<::SE::ISettings>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::ISettings>(), TypeID(SE_TEXT("SE::ISettings")));
            TTypeCompositeInfo<::SE::GlobalSettings>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::GlobalSettings>(), TypeID(SE_TEXT("SE::GlobalSettings")));
            TTypeCompositeInfo<::SE::ResourceGlobalSettings>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::ResourceGlobalSettings>(), TypeID(SE_TEXT("SE::ResourceGlobalSettings")));
            TTypeCompositeInfo<::SE::Asset>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Asset>(), TypeID(SE_TEXT("SE::Asset")));
            TTypeCompositeInfo<::SE::JsonAssetBase>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::JsonAssetBase>(), TypeID(SE_TEXT("SE::JsonAssetBase")));
            TTypeCompositeInfo<::SE::JsonAsset>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::JsonAsset>(), TypeID(SE_TEXT("SE::JsonAsset")));
            TTypeCompositeInfo<::SE::SceneAsset>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::SceneAsset>(), TypeID(SE_TEXT("SE::SceneAsset")));
            TTypeCompositeInfo<::SE::SceneObject>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::SceneObject>(), TypeID(SE_TEXT("SE::SceneObject")));
            TTypeCompositeInfo<::SE::Actor>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Actor>(), TypeID(SE_TEXT("SE::Actor")));
            TTypeCompositeInfo<::SE::Scene>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Scene>(), TypeID(SE_TEXT("SE::Scene")));
            TTypeCompositeInfo<::SE::Camera>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Camera>(), TypeID(SE_TEXT("SE::Camera")));
            TTypeCompositeInfo<::SE::RenderActor>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::RenderActor>(), TypeID(SE_TEXT("SE::RenderActor")));
            TTypeCompositeInfo<::SE::ModelInstance>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::ModelInstance>(), TypeID(SE_TEXT("SE::ModelInstance")));
            TTypeCompositeInfo<::SE::StaticModel>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::StaticModel>(), TypeID(SE_TEXT("SE::StaticModel")));
            TTypeCompositeInfo<::SE::Light>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Light>(), TypeID(SE_TEXT("SE::Light")));
            TTypeCompositeInfo<::SE::LightWithShadow>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::LightWithShadow>(), TypeID(SE_TEXT("SE::LightWithShadow")));
            TTypeCompositeInfo<::SE::DirectionalLight>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::DirectionalLight>(), TypeID(SE_TEXT("SE::DirectionalLight")));
            TTypeCompositeInfo<::SE::PointLight>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::PointLight>(), TypeID(SE_TEXT("SE::PointLight")));
            TTypeCompositeInfo<::SE::Sky>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Sky>(), TypeID(SE_TEXT("SE::Sky")));
            TTypeCompositeInfo<::SE::Prefab>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Prefab>(), TypeID(SE_TEXT("SE::Prefab")));
            TTypeCompositeInfo<::SE::GPUBufferDescription>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::GPUBufferDescription>(), TypeID(SE_TEXT("SE::GPUBufferDescription")));
            TTypeCompositeInfo<::SE::GPUGlobalSettings>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::GPUGlobalSettings>(), TypeID(SE_TEXT("SE::GPUGlobalSettings")));
            TTypeCompositeInfo<::SE::BinaryAsset>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::BinaryAsset>(), TypeID(SE_TEXT("SE::BinaryAsset")));
            TTypeCompositeInfo<::SE::ModelBase>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::ModelBase>(), TypeID(SE_TEXT("SE::ModelBase")));
            TTypeCompositeInfo<::SE::Model>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Model>(), TypeID(SE_TEXT("SE::Model")));
            TTypeCompositeInfo<::SE::TextureBase>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::TextureBase>(), TypeID(SE_TEXT("SE::TextureBase")));
            TTypeCompositeInfo<::SE::Texture>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Texture>(), TypeID(SE_TEXT("SE::Texture")));
            TTypeCompositeInfo<::SE::CubeTexture>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::CubeTexture>(), TypeID(SE_TEXT("SE::CubeTexture")));
            TTypeCompositeInfo<::SE::FontAsset>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::FontAsset>(), TypeID(SE_TEXT("SE::FontAsset")));
            TTypeCompositeInfo<::SE::FontTextureAtlas>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::FontTextureAtlas>(), TypeID(SE_TEXT("SE::FontTextureAtlas")));
            TTypeCompositeInfo<::SE::SpriteAtlas>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::SpriteAtlas>(), TypeID(SE_TEXT("SE::SpriteAtlas")));
            TTypeCompositeInfo<::SE::ToneMappingSettings>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::ToneMappingSettings>(), TypeID(SE_TEXT("SE::ToneMappingSettings")));
            TTypeCompositeInfo<::SE::ColorGradingSettings>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::ColorGradingSettings>(), TypeID(SE_TEXT("SE::ColorGradingSettings")));
            TTypeCompositeInfo<::SE::PostProcessSettings>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::PostProcessSettings>(), TypeID(SE_TEXT("SE::PostProcessSettings")));
            TTypeCompositeInfo<::SE::MaterialBase>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::MaterialBase>(), TypeID(SE_TEXT("SE::MaterialBase")));
            TTypeCompositeInfo<::SE::Material>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Material>(), TypeID(SE_TEXT("SE::Material")));
            TTypeCompositeInfo<::SE::Shader>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Shader>(), TypeID(SE_TEXT("SE::Shader")));
            TTypeCompositeInfo<::SE::MaterialInstance>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::MaterialInstance>(), TypeID(SE_TEXT("SE::MaterialInstance")));
            TTypeCompositeInfo<::SE::TextureGroup>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::TextureGroup>(), TypeID(SE_TEXT("SE::TextureGroup")));
            TTypeCompositeInfo<::SE::AssetInfo>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::AssetInfo>(), TypeID(SE_TEXT("SE::AssetInfo")));
            TTypeCompositeInfo<::SE::ContentStats>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::ContentStats>(), TypeID(SE_TEXT("SE::ContentStats")));
            TTypeCompositeInfo<::SE::TextureUtils::Options>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::TextureUtils::Options>(), TypeID(SE_TEXT("SE::TextureUtils::Options")));

            // Enum
            TTypeEnumInfo<::SE::CursorLockMode>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::CursorLockMode>(), TypeID(SE_TEXT("SE::CursorLockMode")));
            TTypeEnumInfo<::SE::MouseButton>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::MouseButton>(), TypeID(SE_TEXT("SE::MouseButton")));
            TTypeEnumInfo<::SE::GamepadAxis>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::GamepadAxis>(), TypeID(SE_TEXT("SE::GamepadAxis")));
            TTypeEnumInfo<::SE::GamepadButton>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::GamepadButton>(), TypeID(SE_TEXT("SE::GamepadButton")));
            TTypeEnumInfo<::SE::InputActionMode>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::InputActionMode>(), TypeID(SE_TEXT("SE::InputActionMode")));
            TTypeEnumInfo<::SE::InputActionState>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::InputActionState>(), TypeID(SE_TEXT("SE::InputActionState")));
            TTypeEnumInfo<::SE::InputGamepadIndex>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::InputGamepadIndex>(), TypeID(SE_TEXT("SE::InputGamepadIndex")));
            TTypeEnumInfo<::SE::InputAxisType>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::InputAxisType>(), TypeID(SE_TEXT("SE::InputAxisType")));
            TTypeEnumInfo<::SE::SkyType>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::SkyType>(), TypeID(SE_TEXT("SE::SkyType")));
            TTypeEnumInfo<::SE::GPUResourceUsage>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::GPUResourceUsage>(), TypeID(SE_TEXT("SE::GPUResourceUsage")));
            TTypeEnumInfo<::SE::GPUResourceMapMode>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::GPUResourceMapMode>(), TypeID(SE_TEXT("SE::GPUResourceMapMode")));
            TTypeEnumInfo<::SE::MSAALevel>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::MSAALevel>(), TypeID(SE_TEXT("SE::MSAALevel")));
            TTypeEnumInfo<::SE::GPURendererType>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::GPURendererType>(), TypeID(SE_TEXT("SE::GPURendererType")));
            TTypeEnumInfo<::SE::RHIShaderModel>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::RHIShaderModel>(), TypeID(SE_TEXT("SE::RHIShaderModel")));
            TTypeEnumInfo<::SE::RHIFilter>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::RHIFilter>(), TypeID(SE_TEXT("SE::RHIFilter")));
            TTypeEnumInfo<::SE::PixelFormat>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::PixelFormat>(), TypeID(SE_TEXT("SE::PixelFormat")));
            TTypeEnumInfo<::SE::GPUResourceType>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::GPUResourceType>(), TypeID(SE_TEXT("SE::GPUResourceType")));
            TTypeEnumInfo<::SE::StencilOperation>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::StencilOperation>(), TypeID(SE_TEXT("SE::StencilOperation")));
            TTypeEnumInfo<::SE::GPUSamplerFilter>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::GPUSamplerFilter>(), TypeID(SE_TEXT("SE::GPUSamplerFilter")));
            TTypeEnumInfo<::SE::GPUSamplerAddressMode>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::GPUSamplerAddressMode>(), TypeID(SE_TEXT("SE::GPUSamplerAddressMode")));
            TTypeEnumInfo<::SE::GPUSamplerCompareFunction>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::GPUSamplerCompareFunction>(), TypeID(SE_TEXT("SE::GPUSamplerCompareFunction")));
            TTypeEnumInfo<::SE::GPUSamplerBorderColor>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::GPUSamplerBorderColor>(), TypeID(SE_TEXT("SE::GPUSamplerBorderColor")));
            TTypeEnumInfo<::SE::TextureFormatType>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::TextureFormatType>(), TypeID(SE_TEXT("SE::TextureFormatType")));
            TTypeEnumInfo<::SE::TextureDimensions>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::TextureDimensions>(), TypeID(SE_TEXT("SE::TextureDimensions")));
            TTypeEnumInfo<::SE::ToneMappingMode>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::ToneMappingMode>(), TypeID(SE_TEXT("SE::ToneMappingMode")));
            TTypeEnumInfo<::SE::AssetTask::Result>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::AssetTask::Result>(), TypeID(SE_TEXT("SE::AssetTask::Result")));
            TTypeEnumInfo<::SE::CreateAssetResult>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::CreateAssetResult>(), TypeID(SE_TEXT("SE::CreateAssetResult")));
            TTypeEnumInfo<::SE::Asset::LoadResult>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Asset::LoadResult>(), TypeID(SE_TEXT("SE::Asset::LoadResult")));
        }
    };

    SE_TYPER_REGISTER(SERuntimeTyper);
}
