//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit";
//-------------------------------------------------------------------------
#include "Runtime/Core/TypeSystem/Types.h"
#include "Runtime/Core/TypeSystem/Info/TypeEnumInfo.h"
//-------------------------------------------------------------------------

//-------------------------------------------------------------------------
// Includes

#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/ActorGraphNode.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/ActorTreeNode.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/AssetItem.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/AssetOperate.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/BinaryAssetItem.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/BinaryAssetOperate.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/CameraGraphNode.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/ComboBox.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/ContentFolder.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/ContentItem.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/ContentNavigationButton.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/ContentOperate.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/ContentTreeNode.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/ContentView.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/ContentWindow.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/ContextMenu.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/ContextMenuBase.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/ContextMenuButton.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/ContextMenuChildMenu.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/ContextMenuItem.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/ContextMenuSeparator.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/CustomEditor.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/CustomEditorPresenter.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/DirectionalLightGraphNode.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/DockPanel.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/DockPanelProxy.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/DockWindow.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/DragEventArgs.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/EditorWindow.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/FileItem.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/FloatValueElement.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/FloatWindowDockPanel.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/GenericEditor.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/JsonAssetItem.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/LayoutElement.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/LayoutElements.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/LayoutElementsContainer.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/MainContentTreeNode.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/MainMenu.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/MainMenuButton.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/ManagedEditor.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/MasterDockPanel.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/ModelOperate.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/NavigationBar.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/NavigationButton.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/NewItem.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/PointLightGraphNode.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/PreviewsCache.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/ProjectTreeNode.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/PropertiesListElement.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/SceneGraphNode.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/SceneItem.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/SceneOperate.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/ScenesGraphNode.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/SearchBox.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/SkyGraphNode.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/StaticModelGraphNode.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/TextureOperate.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/ToolStrip.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/ToolStripButton.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/ToolStripSeparator.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/Tree.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/TreeNode.typeinfo.h"
#include "E:/EngineProject/SolarEngine/Src/Engine/Editor/_Generated/AutoGenerated/UndoStack.typeinfo.h"

//-------------------------------------------------------------------------
// Registration functions

namespace SE
{
    class SEEditorTyper final : public ITyper
    {
    protected:
        void RegisterTypes() override
        {
            // Meta
        

            // Type
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::IUndoableAction>(), TypeID(SE_TEXT("SE::Editor::IUndoableAction")));
            TTypeCompositeInfo<::SE::Editor::IUndoableAction>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::CompoundStackAction>(), TypeID(SE_TEXT("SE::Editor::CompoundStackAction")));
            TTypeCompositeInfo<::SE::Editor::CompoundStackAction>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ContextMenuBase>(), TypeID(SE_TEXT("SE::Editor::ContextMenuBase")));
            TTypeCompositeInfo<::SE::Editor::ContextMenuBase>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ContextMenu>(), TypeID(SE_TEXT("SE::Editor::ContextMenu")));
            TTypeCompositeInfo<::SE::Editor::ContextMenu>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ContextMenuItem>(), TypeID(SE_TEXT("SE::Editor::ContextMenuItem")));
            TTypeCompositeInfo<::SE::Editor::ContextMenuItem>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ContextMenuButton>(), TypeID(SE_TEXT("SE::Editor::ContextMenuButton")));
            TTypeCompositeInfo<::SE::Editor::ContextMenuButton>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ContextMenuChildMenu>(), TypeID(SE_TEXT("SE::Editor::ContextMenuChildMenu")));
            TTypeCompositeInfo<::SE::Editor::ContextMenuChildMenu>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ContextMenuSeparator>(), TypeID(SE_TEXT("SE::Editor::ContextMenuSeparator")));
            TTypeCompositeInfo<::SE::Editor::ContextMenuSeparator>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::DockPanel>(), TypeID(SE_TEXT("SE::Editor::DockPanel")));
            TTypeCompositeInfo<::SE::Editor::DockPanel>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::DockPanelProxy>(), TypeID(SE_TEXT("SE::Editor::DockPanelProxy")));
            TTypeCompositeInfo<::SE::Editor::DockPanelProxy>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::DockWindow>(), TypeID(SE_TEXT("SE::Editor::DockWindow")));
            TTypeCompositeInfo<::SE::Editor::DockWindow>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::MasterDockPanel>(), TypeID(SE_TEXT("SE::Editor::MasterDockPanel")));
            TTypeCompositeInfo<::SE::Editor::MasterDockPanel>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::FloatWindowDockPanel>(), TypeID(SE_TEXT("SE::Editor::FloatWindowDockPanel")));
            TTypeCompositeInfo<::SE::Editor::FloatWindowDockPanel>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::Tree>(), TypeID(SE_TEXT("SE::Editor::Tree")));
            TTypeCompositeInfo<::SE::Editor::Tree>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::TreeNode>(), TypeID(SE_TEXT("SE::Editor::TreeNode")));
            TTypeCompositeInfo<::SE::Editor::TreeNode>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ActorTreeNode>(), TypeID(SE_TEXT("SE::Editor::ActorTreeNode")));
            TTypeCompositeInfo<::SE::Editor::ActorTreeNode>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::DragEventArgs>(), TypeID(SE_TEXT("SE::Editor::DragEventArgs")));
            TTypeCompositeInfo<::SE::Editor::DragEventArgs>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::SearchBox>(), TypeID(SE_TEXT("SE::Editor::SearchBox")));
            TTypeCompositeInfo<::SE::Editor::SearchBox>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::MainMenu>(), TypeID(SE_TEXT("SE::Editor::MainMenu")));
            TTypeCompositeInfo<::SE::Editor::MainMenu>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::MainMenuButton>(), TypeID(SE_TEXT("SE::Editor::MainMenuButton")));
            TTypeCompositeInfo<::SE::Editor::MainMenuButton>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ToolStripButton>(), TypeID(SE_TEXT("SE::Editor::ToolStripButton")));
            TTypeCompositeInfo<::SE::Editor::ToolStripButton>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ToolStrip>(), TypeID(SE_TEXT("SE::Editor::ToolStrip")));
            TTypeCompositeInfo<::SE::Editor::ToolStrip>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ToolStripSeparator>(), TypeID(SE_TEXT("SE::Editor::ToolStripSeparator")));
            TTypeCompositeInfo<::SE::Editor::ToolStripSeparator>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ComboBox>(), TypeID(SE_TEXT("SE::Editor::ComboBox")));
            TTypeCompositeInfo<::SE::Editor::ComboBox>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::NavigationBar>(), TypeID(SE_TEXT("SE::Editor::NavigationBar")));
            TTypeCompositeInfo<::SE::Editor::NavigationBar>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::NavigationButton>(), TypeID(SE_TEXT("SE::Editor::NavigationButton")));
            TTypeCompositeInfo<::SE::Editor::NavigationButton>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::CustomEditor>(), TypeID(SE_TEXT("SE::Editor::CustomEditor")));
            TTypeCompositeInfo<::SE::Editor::CustomEditor>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::GenericEditor>(), TypeID(SE_TEXT("SE::Editor::GenericEditor")));
            TTypeCompositeInfo<::SE::Editor::GenericEditor>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::LayoutElement>(), TypeID(SE_TEXT("SE::Editor::LayoutElement")));
            TTypeCompositeInfo<::SE::Editor::LayoutElement>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::LayoutElementsContainer>(), TypeID(SE_TEXT("SE::Editor::LayoutElementsContainer")));
            TTypeCompositeInfo<::SE::Editor::LayoutElementsContainer>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::PropertiesListElement>(), TypeID(SE_TEXT("SE::Editor::PropertiesListElement")));
            TTypeCompositeInfo<::SE::Editor::PropertiesListElement>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ButtonElement>(), TypeID(SE_TEXT("SE::Editor::ButtonElement")));
            TTypeCompositeInfo<::SE::Editor::ButtonElement>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::SpaceElement>(), TypeID(SE_TEXT("SE::Editor::SpaceElement")));
            TTypeCompositeInfo<::SE::Editor::SpaceElement>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::TextBoxElement>(), TypeID(SE_TEXT("SE::Editor::TextBoxElement")));
            TTypeCompositeInfo<::SE::Editor::TextBoxElement>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::CheckBoxElement>(), TypeID(SE_TEXT("SE::Editor::CheckBoxElement")));
            TTypeCompositeInfo<::SE::Editor::CheckBoxElement>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::DoubleValueElement>(), TypeID(SE_TEXT("SE::Editor::DoubleValueElement")));
            TTypeCompositeInfo<::SE::Editor::DoubleValueElement>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::IntegerValueElement>(), TypeID(SE_TEXT("SE::Editor::IntegerValueElement")));
            TTypeCompositeInfo<::SE::Editor::IntegerValueElement>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::SliderElement>(), TypeID(SE_TEXT("SE::Editor::SliderElement")));
            TTypeCompositeInfo<::SE::Editor::SliderElement>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ComboBoxElement>(), TypeID(SE_TEXT("SE::Editor::ComboBoxElement")));
            TTypeCompositeInfo<::SE::Editor::ComboBoxElement>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::EnumElement>(), TypeID(SE_TEXT("SE::Editor::EnumElement")));
            TTypeCompositeInfo<::SE::Editor::EnumElement>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ImageElement>(), TypeID(SE_TEXT("SE::Editor::ImageElement")));
            TTypeCompositeInfo<::SE::Editor::ImageElement>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::FloatValueElement>(), TypeID(SE_TEXT("SE::Editor::FloatValueElement")));
            TTypeCompositeInfo<::SE::Editor::FloatValueElement>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::GroupElement>(), TypeID(SE_TEXT("SE::Editor::GroupElement")));
            TTypeCompositeInfo<::SE::Editor::GroupElement>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::HorizontalPanelElement>(), TypeID(SE_TEXT("SE::Editor::HorizontalPanelElement")));
            TTypeCompositeInfo<::SE::Editor::HorizontalPanelElement>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::VerticalPanelElement>(), TypeID(SE_TEXT("SE::Editor::VerticalPanelElement")));
            TTypeCompositeInfo<::SE::Editor::VerticalPanelElement>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::CustomEditorPresenter>(), TypeID(SE_TEXT("SE::Editor::CustomEditorPresenter")));
            TTypeCompositeInfo<::SE::Editor::CustomEditorPresenter>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ContentOperate>(), TypeID(SE_TEXT("SE::Editor::ContentOperate")));
            TTypeCompositeInfo<::SE::Editor::ContentOperate>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::AssetOperate>(), TypeID(SE_TEXT("SE::Editor::AssetOperate")));
            TTypeCompositeInfo<::SE::Editor::AssetOperate>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::BinaryAssetOperate>(), TypeID(SE_TEXT("SE::Editor::BinaryAssetOperate")));
            TTypeCompositeInfo<::SE::Editor::BinaryAssetOperate>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::TextureOperate>(), TypeID(SE_TEXT("SE::Editor::TextureOperate")));
            TTypeCompositeInfo<::SE::Editor::TextureOperate>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ModelOperate>(), TypeID(SE_TEXT("SE::Editor::ModelOperate")));
            TTypeCompositeInfo<::SE::Editor::ModelOperate>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::SceneOperate>(), TypeID(SE_TEXT("SE::Editor::SceneOperate")));
            TTypeCompositeInfo<::SE::Editor::SceneOperate>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ContentItem>(), TypeID(SE_TEXT("SE::Editor::ContentItem")));
            TTypeCompositeInfo<::SE::Editor::ContentItem>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ContentFolder>(), TypeID(SE_TEXT("SE::Editor::ContentFolder")));
            TTypeCompositeInfo<::SE::Editor::ContentFolder>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::AssetItem>(), TypeID(SE_TEXT("SE::Editor::AssetItem")));
            TTypeCompositeInfo<::SE::Editor::AssetItem>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::BinaryAssetItem>(), TypeID(SE_TEXT("SE::Editor::BinaryAssetItem")));
            TTypeCompositeInfo<::SE::Editor::BinaryAssetItem>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::TextureAssetItem>(), TypeID(SE_TEXT("SE::Editor::TextureAssetItem")));
            TTypeCompositeInfo<::SE::Editor::TextureAssetItem>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ModelItem>(), TypeID(SE_TEXT("SE::Editor::ModelItem")));
            TTypeCompositeInfo<::SE::Editor::ModelItem>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::FileItem>(), TypeID(SE_TEXT("SE::Editor::FileItem")));
            TTypeCompositeInfo<::SE::Editor::FileItem>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::NewItem>(), TypeID(SE_TEXT("SE::Editor::NewItem")));
            TTypeCompositeInfo<::SE::Editor::NewItem>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::JsonAssetItem>(), TypeID(SE_TEXT("SE::Editor::JsonAssetItem")));
            TTypeCompositeInfo<::SE::Editor::JsonAssetItem>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::SceneItem>(), TypeID(SE_TEXT("SE::Editor::SceneItem")));
            TTypeCompositeInfo<::SE::Editor::SceneItem>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ContentTreeNode>(), TypeID(SE_TEXT("SE::Editor::ContentTreeNode")));
            TTypeCompositeInfo<::SE::Editor::ContentTreeNode>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::RootContentTreeNode>(), TypeID(SE_TEXT("SE::Editor::RootContentTreeNode")));
            TTypeCompositeInfo<::SE::Editor::RootContentTreeNode>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::MainContentTreeNode>(), TypeID(SE_TEXT("SE::Editor::MainContentTreeNode")));
            TTypeCompositeInfo<::SE::Editor::MainContentTreeNode>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ProjectTreeNode>(), TypeID(SE_TEXT("SE::Editor::ProjectTreeNode")));
            TTypeCompositeInfo<::SE::Editor::ProjectTreeNode>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::PreviewsCache>(), TypeID(SE_TEXT("SE::Editor::PreviewsCache")));
            TTypeCompositeInfo<::SE::Editor::PreviewsCache>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ContentView>(), TypeID(SE_TEXT("SE::Editor::ContentView")));
            TTypeCompositeInfo<::SE::Editor::ContentView>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ContentNavigationButton>(), TypeID(SE_TEXT("SE::Editor::ContentNavigationButton")));
            TTypeCompositeInfo<::SE::Editor::ContentNavigationButton>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ContentNavigationSeparator>(), TypeID(SE_TEXT("SE::Editor::ContentNavigationSeparator")));
            TTypeCompositeInfo<::SE::Editor::ContentNavigationSeparator>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::EditorWindow>(), TypeID(SE_TEXT("SE::Editor::EditorWindow")));
            TTypeCompositeInfo<::SE::Editor::EditorWindow>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ContentWindow::ViewDropdown>(), TypeID(SE_TEXT("SE::Editor::ContentWindow::ViewDropdown")));
            TTypeCompositeInfo<::SE::Editor::ContentWindow::ViewDropdown>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ScenesGraphNode>(), TypeID(SE_TEXT("SE::Editor::ScenesGraphNode")));
            TTypeCompositeInfo<::SE::Editor::ScenesGraphNode>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ActorGraphNode>(), TypeID(SE_TEXT("SE::Editor::ActorGraphNode")));
            TTypeCompositeInfo<::SE::Editor::ActorGraphNode>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::SceneGraphNode>(), TypeID(SE_TEXT("SE::Editor::SceneGraphNode")));
            TTypeCompositeInfo<::SE::Editor::SceneGraphNode>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::CameraGraphNode>(), TypeID(SE_TEXT("SE::Editor::CameraGraphNode")));
            TTypeCompositeInfo<::SE::Editor::CameraGraphNode>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::StaticModelGraphNode>(), TypeID(SE_TEXT("SE::Editor::StaticModelGraphNode")));
            TTypeCompositeInfo<::SE::Editor::StaticModelGraphNode>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::SkyGraphNode>(), TypeID(SE_TEXT("SE::Editor::SkyGraphNode")));
            TTypeCompositeInfo<::SE::Editor::SkyGraphNode>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::DirectionalLightGraphNode>(), TypeID(SE_TEXT("SE::Editor::DirectionalLightGraphNode")));
            TTypeCompositeInfo<::SE::Editor::DirectionalLightGraphNode>::RegisterType();
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::PointLightGraphNode>(), TypeID(SE_TEXT("SE::Editor::PointLightGraphNode")));
            TTypeCompositeInfo<::SE::Editor::PointLightGraphNode>::RegisterType();

            // Enum
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ContentItemSearchFilter>(), TypeID(SE_TEXT("SE::Editor::ContentItemSearchFilter")));
            TTypeEnumInfo<::SE::Editor::ContentItemSearchFilter>::RegisterType();
        }

        void UnregisterTypes() override
        {
            // Meta
        

            // Type
            TTypeCompositeInfo<::SE::Editor::IUndoableAction>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::IUndoableAction>(), TypeID(SE_TEXT("SE::Editor::IUndoableAction")));
            TTypeCompositeInfo<::SE::Editor::CompoundStackAction>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::CompoundStackAction>(), TypeID(SE_TEXT("SE::Editor::CompoundStackAction")));
            TTypeCompositeInfo<::SE::Editor::ContextMenuBase>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ContextMenuBase>(), TypeID(SE_TEXT("SE::Editor::ContextMenuBase")));
            TTypeCompositeInfo<::SE::Editor::ContextMenu>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ContextMenu>(), TypeID(SE_TEXT("SE::Editor::ContextMenu")));
            TTypeCompositeInfo<::SE::Editor::ContextMenuItem>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ContextMenuItem>(), TypeID(SE_TEXT("SE::Editor::ContextMenuItem")));
            TTypeCompositeInfo<::SE::Editor::ContextMenuButton>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ContextMenuButton>(), TypeID(SE_TEXT("SE::Editor::ContextMenuButton")));
            TTypeCompositeInfo<::SE::Editor::ContextMenuChildMenu>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ContextMenuChildMenu>(), TypeID(SE_TEXT("SE::Editor::ContextMenuChildMenu")));
            TTypeCompositeInfo<::SE::Editor::ContextMenuSeparator>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ContextMenuSeparator>(), TypeID(SE_TEXT("SE::Editor::ContextMenuSeparator")));
            TTypeCompositeInfo<::SE::Editor::DockPanel>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::DockPanel>(), TypeID(SE_TEXT("SE::Editor::DockPanel")));
            TTypeCompositeInfo<::SE::Editor::DockPanelProxy>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::DockPanelProxy>(), TypeID(SE_TEXT("SE::Editor::DockPanelProxy")));
            TTypeCompositeInfo<::SE::Editor::DockWindow>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::DockWindow>(), TypeID(SE_TEXT("SE::Editor::DockWindow")));
            TTypeCompositeInfo<::SE::Editor::MasterDockPanel>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::MasterDockPanel>(), TypeID(SE_TEXT("SE::Editor::MasterDockPanel")));
            TTypeCompositeInfo<::SE::Editor::FloatWindowDockPanel>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::FloatWindowDockPanel>(), TypeID(SE_TEXT("SE::Editor::FloatWindowDockPanel")));
            TTypeCompositeInfo<::SE::Editor::Tree>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::Tree>(), TypeID(SE_TEXT("SE::Editor::Tree")));
            TTypeCompositeInfo<::SE::Editor::TreeNode>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::TreeNode>(), TypeID(SE_TEXT("SE::Editor::TreeNode")));
            TTypeCompositeInfo<::SE::Editor::ActorTreeNode>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ActorTreeNode>(), TypeID(SE_TEXT("SE::Editor::ActorTreeNode")));
            TTypeCompositeInfo<::SE::Editor::DragEventArgs>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::DragEventArgs>(), TypeID(SE_TEXT("SE::Editor::DragEventArgs")));
            TTypeCompositeInfo<::SE::Editor::SearchBox>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::SearchBox>(), TypeID(SE_TEXT("SE::Editor::SearchBox")));
            TTypeCompositeInfo<::SE::Editor::MainMenu>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::MainMenu>(), TypeID(SE_TEXT("SE::Editor::MainMenu")));
            TTypeCompositeInfo<::SE::Editor::MainMenuButton>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::MainMenuButton>(), TypeID(SE_TEXT("SE::Editor::MainMenuButton")));
            TTypeCompositeInfo<::SE::Editor::ToolStripButton>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ToolStripButton>(), TypeID(SE_TEXT("SE::Editor::ToolStripButton")));
            TTypeCompositeInfo<::SE::Editor::ToolStrip>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ToolStrip>(), TypeID(SE_TEXT("SE::Editor::ToolStrip")));
            TTypeCompositeInfo<::SE::Editor::ToolStripSeparator>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ToolStripSeparator>(), TypeID(SE_TEXT("SE::Editor::ToolStripSeparator")));
            TTypeCompositeInfo<::SE::Editor::ComboBox>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ComboBox>(), TypeID(SE_TEXT("SE::Editor::ComboBox")));
            TTypeCompositeInfo<::SE::Editor::NavigationBar>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::NavigationBar>(), TypeID(SE_TEXT("SE::Editor::NavigationBar")));
            TTypeCompositeInfo<::SE::Editor::NavigationButton>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::NavigationButton>(), TypeID(SE_TEXT("SE::Editor::NavigationButton")));
            TTypeCompositeInfo<::SE::Editor::CustomEditor>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::CustomEditor>(), TypeID(SE_TEXT("SE::Editor::CustomEditor")));
            TTypeCompositeInfo<::SE::Editor::GenericEditor>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::GenericEditor>(), TypeID(SE_TEXT("SE::Editor::GenericEditor")));
            TTypeCompositeInfo<::SE::Editor::LayoutElement>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::LayoutElement>(), TypeID(SE_TEXT("SE::Editor::LayoutElement")));
            TTypeCompositeInfo<::SE::Editor::LayoutElementsContainer>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::LayoutElementsContainer>(), TypeID(SE_TEXT("SE::Editor::LayoutElementsContainer")));
            TTypeCompositeInfo<::SE::Editor::PropertiesListElement>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::PropertiesListElement>(), TypeID(SE_TEXT("SE::Editor::PropertiesListElement")));
            TTypeCompositeInfo<::SE::Editor::ButtonElement>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ButtonElement>(), TypeID(SE_TEXT("SE::Editor::ButtonElement")));
            TTypeCompositeInfo<::SE::Editor::SpaceElement>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::SpaceElement>(), TypeID(SE_TEXT("SE::Editor::SpaceElement")));
            TTypeCompositeInfo<::SE::Editor::TextBoxElement>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::TextBoxElement>(), TypeID(SE_TEXT("SE::Editor::TextBoxElement")));
            TTypeCompositeInfo<::SE::Editor::CheckBoxElement>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::CheckBoxElement>(), TypeID(SE_TEXT("SE::Editor::CheckBoxElement")));
            TTypeCompositeInfo<::SE::Editor::DoubleValueElement>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::DoubleValueElement>(), TypeID(SE_TEXT("SE::Editor::DoubleValueElement")));
            TTypeCompositeInfo<::SE::Editor::IntegerValueElement>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::IntegerValueElement>(), TypeID(SE_TEXT("SE::Editor::IntegerValueElement")));
            TTypeCompositeInfo<::SE::Editor::SliderElement>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::SliderElement>(), TypeID(SE_TEXT("SE::Editor::SliderElement")));
            TTypeCompositeInfo<::SE::Editor::ComboBoxElement>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ComboBoxElement>(), TypeID(SE_TEXT("SE::Editor::ComboBoxElement")));
            TTypeCompositeInfo<::SE::Editor::EnumElement>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::EnumElement>(), TypeID(SE_TEXT("SE::Editor::EnumElement")));
            TTypeCompositeInfo<::SE::Editor::ImageElement>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ImageElement>(), TypeID(SE_TEXT("SE::Editor::ImageElement")));
            TTypeCompositeInfo<::SE::Editor::FloatValueElement>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::FloatValueElement>(), TypeID(SE_TEXT("SE::Editor::FloatValueElement")));
            TTypeCompositeInfo<::SE::Editor::GroupElement>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::GroupElement>(), TypeID(SE_TEXT("SE::Editor::GroupElement")));
            TTypeCompositeInfo<::SE::Editor::HorizontalPanelElement>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::HorizontalPanelElement>(), TypeID(SE_TEXT("SE::Editor::HorizontalPanelElement")));
            TTypeCompositeInfo<::SE::Editor::VerticalPanelElement>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::VerticalPanelElement>(), TypeID(SE_TEXT("SE::Editor::VerticalPanelElement")));
            TTypeCompositeInfo<::SE::Editor::CustomEditorPresenter>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::CustomEditorPresenter>(), TypeID(SE_TEXT("SE::Editor::CustomEditorPresenter")));
            TTypeCompositeInfo<::SE::Editor::ContentOperate>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ContentOperate>(), TypeID(SE_TEXT("SE::Editor::ContentOperate")));
            TTypeCompositeInfo<::SE::Editor::AssetOperate>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::AssetOperate>(), TypeID(SE_TEXT("SE::Editor::AssetOperate")));
            TTypeCompositeInfo<::SE::Editor::BinaryAssetOperate>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::BinaryAssetOperate>(), TypeID(SE_TEXT("SE::Editor::BinaryAssetOperate")));
            TTypeCompositeInfo<::SE::Editor::TextureOperate>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::TextureOperate>(), TypeID(SE_TEXT("SE::Editor::TextureOperate")));
            TTypeCompositeInfo<::SE::Editor::ModelOperate>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ModelOperate>(), TypeID(SE_TEXT("SE::Editor::ModelOperate")));
            TTypeCompositeInfo<::SE::Editor::SceneOperate>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::SceneOperate>(), TypeID(SE_TEXT("SE::Editor::SceneOperate")));
            TTypeCompositeInfo<::SE::Editor::ContentItem>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ContentItem>(), TypeID(SE_TEXT("SE::Editor::ContentItem")));
            TTypeCompositeInfo<::SE::Editor::ContentFolder>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ContentFolder>(), TypeID(SE_TEXT("SE::Editor::ContentFolder")));
            TTypeCompositeInfo<::SE::Editor::AssetItem>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::AssetItem>(), TypeID(SE_TEXT("SE::Editor::AssetItem")));
            TTypeCompositeInfo<::SE::Editor::BinaryAssetItem>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::BinaryAssetItem>(), TypeID(SE_TEXT("SE::Editor::BinaryAssetItem")));
            TTypeCompositeInfo<::SE::Editor::TextureAssetItem>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::TextureAssetItem>(), TypeID(SE_TEXT("SE::Editor::TextureAssetItem")));
            TTypeCompositeInfo<::SE::Editor::ModelItem>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ModelItem>(), TypeID(SE_TEXT("SE::Editor::ModelItem")));
            TTypeCompositeInfo<::SE::Editor::FileItem>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::FileItem>(), TypeID(SE_TEXT("SE::Editor::FileItem")));
            TTypeCompositeInfo<::SE::Editor::NewItem>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::NewItem>(), TypeID(SE_TEXT("SE::Editor::NewItem")));
            TTypeCompositeInfo<::SE::Editor::JsonAssetItem>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::JsonAssetItem>(), TypeID(SE_TEXT("SE::Editor::JsonAssetItem")));
            TTypeCompositeInfo<::SE::Editor::SceneItem>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::SceneItem>(), TypeID(SE_TEXT("SE::Editor::SceneItem")));
            TTypeCompositeInfo<::SE::Editor::ContentTreeNode>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ContentTreeNode>(), TypeID(SE_TEXT("SE::Editor::ContentTreeNode")));
            TTypeCompositeInfo<::SE::Editor::RootContentTreeNode>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::RootContentTreeNode>(), TypeID(SE_TEXT("SE::Editor::RootContentTreeNode")));
            TTypeCompositeInfo<::SE::Editor::MainContentTreeNode>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::MainContentTreeNode>(), TypeID(SE_TEXT("SE::Editor::MainContentTreeNode")));
            TTypeCompositeInfo<::SE::Editor::ProjectTreeNode>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ProjectTreeNode>(), TypeID(SE_TEXT("SE::Editor::ProjectTreeNode")));
            TTypeCompositeInfo<::SE::Editor::PreviewsCache>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::PreviewsCache>(), TypeID(SE_TEXT("SE::Editor::PreviewsCache")));
            TTypeCompositeInfo<::SE::Editor::ContentView>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ContentView>(), TypeID(SE_TEXT("SE::Editor::ContentView")));
            TTypeCompositeInfo<::SE::Editor::ContentNavigationButton>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ContentNavigationButton>(), TypeID(SE_TEXT("SE::Editor::ContentNavigationButton")));
            TTypeCompositeInfo<::SE::Editor::ContentNavigationSeparator>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ContentNavigationSeparator>(), TypeID(SE_TEXT("SE::Editor::ContentNavigationSeparator")));
            TTypeCompositeInfo<::SE::Editor::EditorWindow>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::EditorWindow>(), TypeID(SE_TEXT("SE::Editor::EditorWindow")));
            TTypeCompositeInfo<::SE::Editor::ContentWindow::ViewDropdown>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ContentWindow::ViewDropdown>(), TypeID(SE_TEXT("SE::Editor::ContentWindow::ViewDropdown")));
            TTypeCompositeInfo<::SE::Editor::ScenesGraphNode>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ScenesGraphNode>(), TypeID(SE_TEXT("SE::Editor::ScenesGraphNode")));
            TTypeCompositeInfo<::SE::Editor::ActorGraphNode>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ActorGraphNode>(), TypeID(SE_TEXT("SE::Editor::ActorGraphNode")));
            TTypeCompositeInfo<::SE::Editor::SceneGraphNode>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::SceneGraphNode>(), TypeID(SE_TEXT("SE::Editor::SceneGraphNode")));
            TTypeCompositeInfo<::SE::Editor::CameraGraphNode>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::CameraGraphNode>(), TypeID(SE_TEXT("SE::Editor::CameraGraphNode")));
            TTypeCompositeInfo<::SE::Editor::StaticModelGraphNode>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::StaticModelGraphNode>(), TypeID(SE_TEXT("SE::Editor::StaticModelGraphNode")));
            TTypeCompositeInfo<::SE::Editor::SkyGraphNode>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::SkyGraphNode>(), TypeID(SE_TEXT("SE::Editor::SkyGraphNode")));
            TTypeCompositeInfo<::SE::Editor::DirectionalLightGraphNode>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::DirectionalLightGraphNode>(), TypeID(SE_TEXT("SE::Editor::DirectionalLightGraphNode")));
            TTypeCompositeInfo<::SE::Editor::PointLightGraphNode>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::PointLightGraphNode>(), TypeID(SE_TEXT("SE::Editor::PointLightGraphNode")));

            // Enum
            TTypeEnumInfo<::SE::Editor::ContentItemSearchFilter>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ContentItemSearchFilter>(), TypeID(SE_TEXT("SE::Editor::ContentItemSearchFilter")));
        }
    };

    SE_TYPER_REGISTER(SEEditorTyper);
}
