//-------------------------------------------------------------------------
// This is an auto-generated file - DO NOT edit";
//-------------------------------------------------------------------------
#include "Core/TypeSystem/Types.h"
#include "Core/TypeSystem/Info/TypeEnumInfo.h"
//-------------------------------------------------------------------------

//-------------------------------------------------------------------------
// Includes

#include "e:/engineproject/solarengine/src/engine/editor/_Generated/AutoGenerated/contentitem.typeinfo.h"
#include "e:/engineproject/solarengine/src/engine/editor/_Generated/AutoGenerated/managededitor.typeinfo.h"
#include "e:/engineproject/solarengine/src/engine/editor/_Generated/AutoGenerated/previewscache.typeinfo.h"

//-------------------------------------------------------------------------
// Registration functions

namespace SE
{
    class SEEditorTyper final : public ITyper
    {
    protected:
        void RegisterTypes() override
        {
            // Meta
        

            // Type
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::PreviewsCache>(), TypeID(SE_TEXT("SE::Editor::PreviewsCache")));
            TTypeCompositeInfo<::SE::Editor::PreviewsCache>::RegisterType();

            // Enum
            Types::RegisterTypeID(StableID::Generate<::SE::Editor::ContentItemSearchFilter>(), TypeID(SE_TEXT("SE::Editor::ContentItemSearchFilter")));
            TTypeEnumInfo<::SE::Editor::ContentItemSearchFilter>::RegisterType();
        }

        void UnregisterTypes() override
        {
            // Meta
        

            // Type
            TTypeCompositeInfo<::SE::Editor::PreviewsCache>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::PreviewsCache>(), TypeID(SE_TEXT("SE::Editor::PreviewsCache")));

            // Enum
            TTypeEnumInfo<::SE::Editor::ContentItemSearchFilter>::UnregisterType();
            Types::UnRegisterTypeID(StableID::Generate<::SE::Editor::ContentItemSearchFilter>(), TypeID(SE_TEXT("SE::Editor::ContentItemSearchFilter")));
        }
    };

    SE_TYPER_REGISTER(SEEditorTyper);
}
