#pragma once

#include "Core/Types/Strings/String.h"

//-------------------------------------------------------------------------

namespace SE::ReflectTool
{
    enum class ReflectionMacroType
    {
        ReflectModule = 0,
        ReflectEnum = 1,
        ReflectType = 2,
        ReflectProperty = 3,
        ReflectFUNC = 4,
        ReflectMeta = 5,

        NumMacros,
        Unknown = NumMacros,
    };

    Char const* GetReflectionMacroText( ReflectionMacroType macro );
    //-------------------------------------------------------------------------

    namespace Settings
    {
        constexpr static Char const* const g_engineNamespace = SE_TEXT("SE");
        constexpr static char const* const g_engineNamespacePlusDelimiter = "SE::";
        constexpr static Char const* const g_moduleHeaderParentDirectoryName = SE_TEXT("_Generated");
        constexpr static Char const* const g_moduleHeaderSuffix = SE_TEXT("Module.h");
        constexpr static Char const* const g_autogeneratedDirectory = SE_TEXT("_Generated\\AutoGenerated\\");
        constexpr static Char const* const g_autogeneratedModuleFileSuffix = SE_TEXT("AutoGenerated.cpp");
        constexpr static Char const* const g_engineTypeRegistrationHeaderPath = SE_TEXT("EngineTypeRegistration.h");
        constexpr static Char const* const g_toolsTypeRegistrationHeaderPath = SE_TEXT("ToolsTypeRegistration.h");
        constexpr static Char const* const g_temporaryDirectoryPath = SE_TEXT("\\..\\_Temp\\");


        constexpr static char const* const g_devToolsExclusionDefine = "-D ENGINE_SHIPPING";

        //-------------------------------------------------------------------------
        // Projects
        //-------------------------------------------------------------------------

        constexpr static char const* const g_moduleNameExclusionFilters[] = { ("ThirdParty") };


        Char const* const g_allowedProjectNames[] =
        {
			SE_TEXT("SE.Core"),
			SE_TEXT("SE.Runtime"),
			SE_TEXT("SE.Editor")
        };

        constexpr static int const g_numAllowedProjects = std::size(g_allowedProjectNames);

        //-------------------------------------------------------------------------
        // Core class and type names
        //-------------------------------------------------------------------------

        constexpr static Char const* const g_reflectedTypeInterfaceClassName = SE_TEXT("IType");
        constexpr static Char const* const g_baseEntityClassName = SE_TEXT("Entity");
        constexpr static Char const* const g_baseEntityComponentClassName = SE_TEXT("EntityComponent");
        constexpr static Char const* const g_baseEntitySystemClassName = SE_TEXT("IEntitySystem");

        constexpr static Char const* const g_baseResourceFullTypeName = SE_TEXT("SE::IResource");

        //-------------------------------------------------------------------------
        // Clang Parser Settings
        //-------------------------------------------------------------------------

        Char const* const g_includePaths[] =
        {
			SE_TEXT(""),
			SE_TEXT("Engine"),
            SE_TEXT("Engine/Core/ThirdParty"),
            SE_TEXT("Engine/Runtime/ThirdParty"),
            SE_TEXT("Engine/Editor/ThirdParty"),
            SE_TEXT("Libraries/fmt/include"),
            SE_TEXT("Libraries/sqlite3"),
        };
    }

    //-------------------------------------------------------------------------

    namespace Utils
    {
        inline bool IsFileUnderToolsProject(String const& filePath )
        {
            if ( filePath.Find(SE_TEXT("\\EngineTools\\")) != INVALID_INDEX )
            {
                return true;
            }

            if ( filePath.Find(SE_TEXT("\\GameTools\\")) != INVALID_INDEX )
            {
                return true;
            }

            return false;
        }
    }
}