#pragma once

#include "String.h"
#include "StringID.h"

#include <fmt/args.h>
#include <fmt/format.h>

//-------------------------------------------------------------------------

namespace SE::BuildTool
{
    enum class ReflectionMacroType
    {
        ReflectMeta,

        SEClass,                // SE_CLASS(Reflect, API, ...)
        SEStruct,               // SE_STRUCT(...)
        SEInterface,            // SE_INTERFACE(...)
        SEEnum,                 // SE_ENUM(Reflect, API, ...)
        SEProperty,             // SE_PROPERTY(Reflect, API, ...)
        SEFunction,             // SE_FUNCTION(Reflect, API, ...)
        SEEvent,                // SE_EVENT(API, ...)
        SETypeDef,              // SE_TYPEDEF(...)
        APIInjectCode,          // API_INJECT_CODE(cpp|csharp, "code")

        NumMacros,
        Unknown = NumMacros,
    };

    char const* GetMarkMacroText(ReflectionMacroType macro);

    //-------------------------------------------------------------------------

    namespace Settings
    {
        constexpr static char const* const g_engineNamespace = "SE";
        constexpr static char const* const g_engineNamespacePlusDelimiter = "SE::";
        constexpr static char const* const g_moduleHeaderParentDirectoryName = "_Generated";
        constexpr static char const* const g_autogeneratedDirectory = "_Generated\\AutoGenerated\\";
        constexpr static char const* const g_autogeneratedModuleFileSuffix = "AutoGenerated.cpp";
        constexpr static char const* const g_engineTypeRegistrationHeaderPath = "EngineTypeRegistration.h";
        constexpr static char const* const g_toolsTypeRegistrationHeaderPath = "ToolsTypeRegistration.h";
        constexpr static char const* const g_temporaryDirectoryPath = "\\..\\_Temp\\";

        constexpr static char const* const g_ApiGeneratedDirectory = "\\_Generated\\APIGenerated";

        //-------------------------------------------------------------------------
        // Projects
        //-------------------------------------------------------------------------

        constexpr static char const* const g_moduleNameExclusionFilters[] = { ("ThirdParty") };

        //-------------------------------------------------------------------------
        // Core class and type names
        //-------------------------------------------------------------------------

        constexpr static char const* const g_reflectedTypeInterfaceClassName = "IType";
        constexpr static char const* const g_baseEntityClassName = "Entity";
        constexpr static char const* const g_baseEntityComponentClassName = "EntityComponent";
        constexpr static char const* const g_baseEntitySystemClassName = "IEntitySystem";

        constexpr static char const* const g_baseResourceFullTypeName = "SE::IResource";

        //-------------------------------------------------------------------------
        // Clang Parser Settings
        //-------------------------------------------------------------------------

        char const* const g_includePaths[] =
        {
            "",
            "Engine",
            "Engine/Runtime/ThirdParty",
            "Engine/Editor/ThirdParty",
            "Libraries/fmt/include",
            "Libraries/sqlite3",
        };
    }

    //-------------------------------------------------------------------------

    using TypeID = StringID;

    namespace Utils
    {
        namespace String
        {
            int32 Length(const char* text);
            int32 Length(std::string_view text);
            const char* CStr(const char* text);
            const char* CStr(const std::string& text);
            std::string ToString(std::string_view text);
            std::string ToLowerCopy(std::string_view text);
            bool StartsWith(std::string_view text, std::string_view prefix);
            bool EndsWith(std::string_view text, std::string_view suffix);
            bool EndsWith(std::string_view text, char suffix);
            int32 Find(std::string_view text, std::string_view needle, int32 start = 0);
            int32 Find(std::string_view text, char needle, int32 start = 0);
            int32 FindLast(std::string_view text, char needle);
            bool Contains(std::string_view text, std::string_view needle);
            void ReplaceAll(std::string& text, std::string_view from, std::string_view to);
            void TrimStart(std::string& text);
            void TrimEnd(std::string& text);
            void Split(std::string_view text, std::string_view delimiter, std::vector<std::string>& out);
            void Split(std::string_view text, char delimiter, std::vector<std::string>& out);
            bool TryReadFormatArgumentIndex(std::string_view fmt, size_t openBraceIndex, size_t& closeBraceIndex, size_t& argumentIndex);
            void AppendEscapedFormatLiteral(std::string& result, std::string_view text, size_t start, size_t length);

            template<typename... Args>
            std::string Format(std::string_view fmt, Args&&... args)
            {
                return fmt::format(fmt, std::forward<Args>(args)...);
            }

        }

        namespace Vector
        {
            template<typename T, typename Predicate>
            void QuickSort(std::vector<T>& values, Predicate predicate)
            {
                std::sort(values.begin(), values.end(), predicate);
            }

            template<typename T>
            int32 FindIndex(const std::vector<T>& values, const T& value)
            {
                auto iter = std::find(values.begin(), values.end(), value);
                return iter == values.end() ? INVALID_INDEX : (int32)std::distance(values.begin(), iter);
            }

            template<typename T, typename Predicate>
            int32 FindIndexIf(const std::vector<T>& values, Predicate predicate)
            {
                auto iter = std::find_if(values.begin(), values.end(), predicate);
                return iter == values.end() ? INVALID_INDEX : (int32)std::distance(values.begin(), iter);
            }

            template<typename T>
            bool Contains(const std::vector<T>& values, const T& value)
            {
                return FindIndex(values, value) != INVALID_INDEX;
            }

            template<typename T>
            T& AddOne(std::vector<T>& values)
            {
                values.emplace_back();
                return values.back();
            }

            template<typename T>
            void RemoveAt(std::vector<T>& values, size_t index)
            {
                ENGINE_ASSERT(index < values.size());
                values.erase(values.begin() + index);
            }

            template<typename T>
            T* Data(std::vector<T>& values)
            {
                return values.empty() ? nullptr : values.data();
            }

            template<typename T>
            const T* Data(const std::vector<T>& values)
            {
                return values.empty() ? nullptr : values.data();
            }
        }

        bool IsFileUnderToolsProject(std::string const& filePath);

        std::vector<std::string> SplitString(const char* nameSpaces, const char* combine);

        std::string CombineStringList(const std::vector<std::string>& nameSpaceList, const char* combine);

        bool ReadAllText(const std::string& path, std::string& outText);

        bool WriteAllText(const std::string& path, const std::string& text);

        enum class TypeIDCore
        {
            Bool = 0,
            Uint8,
            Int8,
            Uint16,
            Int16,
            Uint32,
            Int32,
            Uint64,
            Int64,
            Float,
            Double,
            UUID,
            StringID,
            TypeID,
            String,
            Color,
            Float2,
            Float3,
            Float4,
            Int2,
            Int3,
            Int4,
            Double2,
            Double3,
            Double4,
            Quaternion,
            Transform,
            Matrix,
            Microseconds,
            Milliseconds,
            Seconds,
            FloatRange,
            FloatCurve,

            TBitFlags,
            TBitMovedFlags,

            List,
            NumTypes,
        };

        TypeID GetCoreTypeID(TypeIDCore type);

        bool IsCoreType(TypeID type);
    }
}
